### ISSUE TITLE
Error "AttributeError: module 'glfw' has no attribute 'set_window_size_limits" on startup

### ISSUE THREAD

**Issue by kamyanskiy** [kitao/pyxel#1]
I've tried to start application but got an error : "AttributeError: module 'glfw' has no attribute 'set_window_size_limits"

all details I added to gist:
https://gist.github.com/kamyanskiy/2f2eac45656ae1575c59422841c242bf

**Comment by kitao** [comment]
Hi,
Which OS do you use?
If you use MacOS, you need to install GLFW itself before installing Pyxel, which install pyGLFW automatically.
And if you installed the old version GLFW before, an API mismatch may happen.
So please check the installed GLFW is the latest version or not.

On the other hand, if you use Windows, pyGLFW includes Windows versions of GLFW binary and I'dont know the reason of error.

**Comment by lungdart** [comment]
Using Linux mint 18.1 (Ubuntu 16.04) and following the installation steps in the README for Debian, I get this same error. Appears the libglfw3 package in Ubuntu's repositories are too old, but I can't find any required version information about it here.

Your commit about screen size changing, and subsequent closing of this ticket seem unrelated. Could you provide more information?

**Comment by Mec-iS** [comment]
NOTE: GLFW3 latest version (`3.2.1`) is needed. see my https://github.com/kitao/pyxel/issues/19#issuecomment-410328634
