### ISSUE TITLE
Can't figure out how to install?

### ISSUE THREAD

**Issue by legoman8304** [kitao/pyxel#101]
Hello, I have found myself to be too dumb to figure out how to install Pyxel. Can somebody send help?

**Comment by timbledum** [comment]
Hey! What platform are you on? What have you tried so far?

**Comment by legoman8304** [comment]
I'm on windows 10 and I've tried running the "setup" .py file directly from my desktop as well as simply typing "pip install Pyxel" after downloading the repo

**Comment by timbledum** [comment]
Sounds like you may have some python installation issues. Maybe try installing it into a virtual environment? Or make sure it's installing into the version of python you're using by running `python -m pip install pyxel`

**Comment by legoman8304** [comment]
I just ran the '''python -m pip install pyxel''' and got thrown this
![error](https://user-images.githubusercontent.com/43346988/48663096-17f94080-ea59-11e8-8493-a215f927826c.png)
am I running it in the right spot?

**Comment by timbledum** [comment]
There’s the issue! You can’t install packages at the python prompt (at least using pip install). Try using that command just at your standard command line.

**Comment by legoman8304** [comment]
Perfect! Thank you for your trouble, it worked great!
