### ISSUE TITLE
[mac] It don't be drawn until move the window.

### ISSUE THREAD

**Issue by kurehajime** [kitao/pyxel#104]
**Describe the bug**
It don't be drawn until move the window on Mac.

**To Reproduce**
1. Run sample. (01,02,03...)
2. It don't be drawn.But,Music is played.
3. Move the window.
4. It be drawn.

**Screenshots**
![pyxel](https://user-images.githubusercontent.com/4569916/48974706-bfeabb80-f0a2-11e8-8383-a3c929f156ea.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version  10.14（18A391）
 - MacBook Pro (Retina, 13-inch, Early 2015)

**Additional context**
```
$ pip3 install pyxel
Requirement already satisfied: pyxel in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (0.9.4)
Requirement already satisfied: glfw in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from pyxel) (1.7.0)
Requirement already satisfied: numpy in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from pyxel) (1.15.4)
Requirement already satisfied: PyOpenGL in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from pyxel) (3.1.0)
Requirement already satisfied: Pillow in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from pyxel) (5.3.0)
Requirement already satisfied: sounddevice in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from pyxel) (0.3.12)
Requirement already satisfied: CFFI>=1.0 in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from sounddevice->pyxel) (1.11.5)
Requirement already satisfied: pycparser in /Users/username/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from CFFI>=1.0->sounddevice->pyxel) (2.19)
```

**Comment by kitao** [comment]
I've started investigation of this issue, but on my MacBook, I couldn't reproduce it.
If there's someone who knows some information about this, please let me know.

**Comment by LulzsecHackz** [comment]
seems like this bug is only on Mac OS 10.14(Mojave). Im running mac OS High Sierra 10.13 and everything seems ok, i dont need to move windows in order to work.... but everything is laggy and even the music sounds decalibrated and laggy :/ i may test this on windows

**Comment by kitao** [comment]
This seems to be  the bug of GLFW on Mac OS 10.14
https://github.com/glfw/glfw/issues/1334

I'll think about workaround.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.

**Comment by kurehajime** [comment]
Thank you. 👍 
I confirmed that all the samples work properly.

---

OS: Mac OS
Version 10.14.5 (18F132)
MacBook Pro (Retina, 13-inch, Early 2015)
