### ISSUE TITLE
[Jupyter Notebook] Cannot load img with relative path

### ISSUE THREAD

**Issue by dannyso16** [kitao/pyxel#105]
**Describe the bug**
I cannot load image with relative path in Jupyter Notebook.  
> pyxel.image(0).load(0, 0, "asset\cat_16x16.png")
>> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\my_user_name\\Anaconda3\\envs\\pyxel\\lib\\asset\\cat_16x16.png'

when I use pwd,
> 'C:\\code\\..\\pyxel

Is it possible read img in current directory in Jupyter Notebook?

I can load image with absolute path, and example codes work successful.

**Comment by qingfengzxr** [comment]
With use the Jupyter Notebook.If you want to read img in current directory in Jupyter Notebook,you must move the img into the working directory where Jupyter Notebook create.

**Comment by qingfengzxr** [comment]
> **Describe the bug**
> I cannot load image with relative path in Jupyter Notebook.
> 
> > pyxel.image(0).load(0, 0, "asset\cat_16x16.png")
> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\my_user_name\Anaconda3\envs\pyxel\lib\asset\cat_16x16.png'
> 
> when I use pwd,
> 
> > 'C:\code\..\pyxel
> 
> Is it possible read img in current directory in Jupyter Notebook?
> 
> I can load image with absolute path, and example codes work successful.

With use the Jupyter Notebook.If you want to read img in current directory in Jupyter Notebook,you must move the img into the working directory where Jupyter Notebook create.

**Comment by dannyso16** [comment]
Yes, notebook file and 'asset' directory(png image is in it) is in a current working directory.
I can show image like below, but if I do the same in `pyxel.image.load`, err occurs.
> from PIL import Image
> Image.open("asset\cat_16x16.png")  

My working directory is not `C:\Users\my_user_name\Anaconda3\envs\pyxel\lib\`, but `pyxel.load` search in it.

**Comment by kitao** [comment]
I modified the way of searching the path for the resource in the latest Pyxel, 1.1.1.
Does it change the situation?

**Comment by dannyso16** [comment]
I found this problem occured becouse of default setting of Jupyter notebook. 
Initially the currnet working directory of your notebook is placed in `C:\use_name`.  
So this problem is just fault on my setting.  It works well on Atom. Thank you.
