### ISSUE TITLE
some can not be displayed

### ISSUE THREAD

**Issue by neuqzxy** [kitao/pyxel#106]
**Describe the bug**
some can not be displayed
<img width="719" alt="2018-11-29 7 32 58" src="https://user-images.githubusercontent.com/26994055/49219489-6f5ebf80-f40e-11e8-8bb9-e4447a1bf52e.png">
<img width="722" alt="2018-11-29 7 39 35" src="https://user-images.githubusercontent.com/26994055/49219640-d3818380-f40e-11e8-9b28-d2b08a24330e.png">

<img width="718" alt="2018-11-29 7 39 43" src="https://user-images.githubusercontent.com/26994055/49219651-dc725500-f40e-11e8-89c7-20d58ad52f0b.png">

 - OS: 
 macOS High Sierra v10.13.6
<img width="343" alt="2018-11-29 7 34 13" src="https://user-images.githubusercontent.com/26994055/49219659-e5632680-f40e-11e8-88d0-b2149659941e.png">

**Comment by kitao** [comment]
This issue is the same as #103
