### ISSUE TITLE
【win】Runtime error occurs when sample game is activated

### ISSUE THREAD

**Issue by tak4** [kitao/pyxel#110]
I tried 01_hello_pyxel.py and the following error occurred
Can you tell me how to solve it?

----
PS D:\develop\python\pyxel\pyxel_examples> python .\01_hello_pyxel.py
Traceback (most recent call last):
  File ".\01_hello_pyxel.py", line 20, in <module>
    App()
  File ".\01_hello_pyxel.py", line 6, in __init__
    pyxel.init(160, 120, caption="Hello Pyxel")
  File "D:\Program Files\Python37\lib\site-packages\pyxel\__init__.py", line 181, in init
    App(module, width, height, caption, scale, palette, fps, border_width, border_color)
  File "D:\Program Files\Python37\lib\site-packages\pyxel\app.py", line 169, in __init__
    self._renderer = Renderer(width, height)
  File "D:\Program Files\Python37\lib\site-packages\pyxel\renderer.py", line 48, in __init__
    self._draw_shader = GLShader(DRAWING_VERTEX_SHADER, DRAWING_FRAGMENT_SHADER)
  File "D:\Program Files\Python37\lib\site-packages\pyxel\gl_wrapper.py", line 11, in __init__
    shaders.compileShader(vertex_shader, gl.GL_VERTEX_SHADER),
  File "D:\Program Files\Python37\lib\site-packages\OpenGL\GL\shaders.py", line 226, in compileShader
    shaderType,
RuntimeError: ('Shader compile failure (0): b"Vertex shader failed to compile with the following errors:\\nERROR: 0:162: error(#143) Undeclared identifier undefined\\nERROR: 0:162: error(#132) Syntax error: \';\' parse error\\nERROR: error(#273) 2 compilation errors.  No code generated\\n"', [b'\n#version 120\n\n#define unpack_4ui_1(x) int(mod(x / 0x1, 0x10))\n#define unpack_4ui_2(x) int(mod(x / 0x10, 0x10))\n#define unpack_4ui_3(x) int(mod(x / 0x100, 0x10))\n#define unpack_4ui_4(x) int(mod(x / 0x1000, 0x10))\n\nconst int TYPE_PIX = 0;\nconst int TYPE_LINE = 1;\nconst int TYPE_RECT = 2;\nconst int TYPE_RECTB = 3;\nconst int TYPE_CIRC = 4;\nconst int TYPE_CIRCB = 5;\nconst int TYPE_BLT = 6;\nconst int TYPE_TEXT = 7;\n\nuniform vec2 u_framebuffer_size;\n\nattribute vec3 a_mode;\nattribute vec4 a_pos;\nattribute vec2 a_size;\nattribute vec4 a_clip;\nattribute vec4 a_pal;\n\nvarying float v_type;\nvarying float v_col;\nvarying float v_image;\nvarying vec2 v_pos1;\nvarying vec2 v_pos2;\nvarying vec2 v_min_pos;\nvarying vec2 v_max_pos;\nvarying vec2 v_size;\nvarying vec2 v_min_clip;\nvarying vec2 v_max_clip;\nvarying float v_pal[16];\n\nvec4 pixelToScreen(vec2 pos)\n{\n    return vec4((pos + 0.5 + u_framebuffer_size) * 2.0 / (u_framebuffer_size * 3.0) - 1.0, 0.0, 1.0);\n}\n\nvoid pix()\n{\n    vec2 p = floor(a_pos.xy + 0.5);\n\n    v_min_pos = v_max_pos = p;\n\n    gl_PointSize = 1.0;\n    gl_Position = pixelToScreen(p);\n}\n\nvoid line()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n\n    v_min_pos = min(p1, p2);\n    v_max_pos = max(p1, p2);\n\n    vec2 d = v_max_pos - v_min_pos;\n\n    if (d.x > d.y)\n    {\n        if (p1.x < p2.x) {\n            v_pos1 = p1;\n            v_pos2 = p2;\n        }\n        else\n        {\n            v_pos1 = p2;\n            v_pos2 = p1;\n        }\n    }\n    else\n    {\n        if (p1.y < p2.y)\n        {\n            v_pos1 = p1;\n            v_pos2 = p2;\n        }\n        else\n        {\n            v_pos1 = p2;\n            v_pos2 = p1;\n        }\n    }\n\n    gl_PointSize = max(d.x, d.y) + 1.0;\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid rect_rectb()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n\n    v_min_pos = min(p1, p2);\n    v_max_pos = max(p1, p2);\n\n    vec2 s = v_max_pos - v_min_pos + 1.0;\n\n    gl_PointSize = max(s.x, s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid circ_circb()\n{\n    vec2 p = floor(a_pos.xy + 0.5);\n    float r = floor(a_size.x + 0.5);\n\n    v_pos1 = p;\n    v_min_pos = p - r;\n    v_max_pos = p + r;\n    v_size.x = r;\n\n    gl_PointSize = r * 2.0 + 1.0;\n    gl_Position = pixelToScreen(p);\n}\n\nvoid blt()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n    vec2 s = floor(a_size + 0.5);\n    vec2 abs_s = abs(s);\n\n    v_pos1 = p1;\n    v_pos2 = p2;\n    v_min_pos = p1;\n    v_max_pos = p1 + abs_s - 1.0;\n    v_size = s;\n\n    gl_PointSize = max(abs_s.x, abs_s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid text()\n{\n    v_image = 4 - 1;\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = vec2(mod(a_pos.z, 64) * 4, floor(a_pos.z / 64) * 6);\n    vec2 s = vec2(4, 6);\n    vec2 abs_s = abs(s);\n\n    v_pos1 = p1;\n    v_pos2 = p2;\n    v_min_pos = p1;\n    v_max_pos = p1 + abs_s - 1.0;\n    v_size = s;\n\n    gl_PointSize = max(abs_s.x, abs_s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid main()\n{\n    v_type = a_mode.x;\n    v_col = a_mode.y;\n    v_image = a_mode.z;\n\n    v_pal[0] = unpack_4ui_1(a_pal.x);\n    v_pal[1] = unpack_4ui_2(a_pal.x);\n    v_pal[2] = unpack_4ui_3(a_pal.x);\n    v_pal[3] = unpack_4ui_4(a_pal.x);\n    v_pal[4] = unpack_4ui_1(a_pal.y);\n    v_pal[5] = unpack_4ui_2(a_pal.y);\n    v_pal[6] = unpack_4ui_3(a_pal.y);\n    v_pal[7] = unpack_4ui_4(a_pal.y);\n    v_pal[8] = unpack_4ui_1(a_pal.z);\n    v_pal[9] = unpack_4ui_2(a_pal.z);\n    v_pal[10] = unpack_4ui_3(a_pal.z);\n    v_pal[11] = unpack_4ui_4(a_pal.z);\n    v_pal[12] = unpack_4ui_1(a_pal.w);\n    v_pal[13] = unpack_4ui_2(a_pal.w);\n    v_pal[14] = unpack_4ui_3(a_pal.w);\n    v_pal[15] = unpack_4ui_4(a_pal.w);\n\n    if (v_type == TYPE_PIX) { pix(); }\n    else if (v_type == TYPE_LINE) { line(); }\n    else if (v_type == TYPE_RECT || v_type == TYPE_RECTB) { rect_rectb(); }\n    else if (v_type == TYPE_CIRC || v_type == TYPE_CIRCB) { circ_circb(); }\n    else if (v_type == TYPE_BLT) { blt(); }\n    else if (v_type == TYPE_TEXT) { text(); }\n    else { gl_Position = vec4(0.0, 0.0, 0.0, 1.0); }\n\n    vec2 p1 = floor(a_clip.xy + 0.5);\n    vec2 p2 = floor(a_clip.zw + 0.5);\n\n    v_min_clip = max(min(p1, p2), v_min_pos);\n    v_max_clip = min(max(p1, p2), v_max_pos);\n}\n'], GL_VERTEX_SHADER)

----
The operating environment is below
Windows10 Pro
Version 1803
Python 3.7.1

Python Package Version
astroid           2.1.0
cffi              1.11.5
colorama          0.4.1
glfw              1.7.0
isort             4.3.4
lazy-object-proxy 1.3.1
mccabe            0.6.1
numpy             1.15.4
Pillow            5.3.0
pip               18.1
pycparser         2.19
pylint            2.2.2
PyOpenGL          3.1.0
pyxel             0.9.5
setuptools        40.6.3
six               1.12.0
sounddevice       0.3.12
wrapt             1.10.11

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.

**Comment by tak4** [comment]
Sorry for the late confirmation.
Thank you very much.
Confirmed that the problem was solved in 1.3.1.
