### ISSUE TITLE
GLFWError on windows but works fine on Linux on the same machine

### ISSUE THREAD

**Issue by seipy** [kitao/pyxel#111]
**GLFWError on windows, but pyxel works fine on my Linux on the same machine**

i can't run pyxel on windows ,not even a simple window but it works fine under Linux on the same machine, i got the same problem with Windows 7 and Windows 10 too, although my Intel HD Graphics 3000 is properly installed under windows

**Screenshots**
![image](https://user-images.githubusercontent.com/14264086/50124622-c4e7f880-0265-11e9-86d0-1a20f9c1c0b5.png)

**Desktop :**
 - OS: Windows 10 64bit
 - Python: 3.7.1

**Comment by augustobrit** [comment]
I have this error too... I'm try to run pyxel in WSL with Ubuntu 18.04.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
