### ISSUE TITLE
Sounds broken and Laggy UI on Mac OS 10.13

### ISSUE THREAD

**Issue by KnightSec-Official** [kitao/pyxel#112]
I run sound_api.py but when it starts, the music sounds like my audio card is broken.... and the Map tiles UI its supper laggy for every project and almost crash..

1.python3.7 04_sound_api.py (sounds bad for me idk whats the deal)
2.No error tho

I expected to work everything fine... idk if music is a problem as the laggy UI
No need for screenshots cause everythings looks good(just doesnt sound and work..)

 - OS: Mac OS High Sierra 10.13
 - Browser: Safari, Chrome
 - Version:10.13

Every other UI works fine but the map tiles 0.25 FPS... :/ and also when i start sound_api.py
Is it the laptop or the script ? :/

**Comment by kitao** [comment]
Hi.
Could you let me know which version of Mac you use?
The current version of Pyxel has some performance overhead to render graphic and play sound. So I'd like to check the performance of hardware is enough or not first.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its sound engine entirely.
So this issue should not occur anymore. If there's something wrong with sound, please let me know.
