### ISSUE TITLE
Description of installation method for Linux

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#113]
Hi, everyone.

I confirmed Pyxel works on my Ubuntu environment and the way to install Pyxel is:

```bash
sudo apt install python3 python3-pip libglfw3 libportaudio2
sudo pip3 install pyxel
```
Now I'm planning to update the manual to write this instruction.

And I also would like to add installation methods for other Linux environment that was confirmed with the latest version of Pyxel.  Because unfortunately I'm not sure the current instructions on the Manual works with the latest Pyxel or not.

So could you please tell me the installation method for Linux that was confirmed in other environments with **the latest version of Pyxel (>= 0.9.5)**?

Thank you!

**Comment by eliheuer** [comment]
Works for me on Ubuntu 18.4.1. Thanks!

**Comment by kitao** [comment]
I confirmed operation on Fedora and Debian, and updated the instruction.
