### ISSUE TITLE
I started developing the native version of Pyxel with SDL2. Is there any hints or comments?

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#114]
Hi, everyone.

The current Pyxel implementation is using OpenGL's point sprite and GLFW for Python.
Those libraries are very useful and has great flexibility, but as a result, the overhead of speed comes out, and the operation becomes strange depending on the environment.

So I started developing the native (maybe c-lang) version of Pyxel graphics/sound engine with SDL2 to get performance improvement and stability, and support for many environments including smartphones.

But actually I never used SDL2 before and don't know the standard way and folder structure to include native libraries (so) for Python package.

So please tell me if there's some good python or SDL2 project for reference.

Comments about the features which should be supported by new native runtime engine are also welcome!

**Comment by hex007** [comment]
Try checking out RetroPie/EmulationStation

It is a good reference project for c++ and SDL2

**Comment by kitao** [comment]
Thank you!

I noticed that [go-sdl](https://github.com/veandco/go-sdl2) includes static binaries of SDL for every platforms and looks very easy to use. So I may try golang with go-sdl to make shared library for python.

**Comment by kitao** [comment]
I may be able to use only [these files] directly, static libraries of SDL2 for go-sdl, without using golang.
I'll continue to investigate.

**Comment by blacktm** [comment]
Hi @kitao. I'm quite experienced with SDL and would be happy to help. I'm the author of [Simple 2D](https://github.com/simple2d/simple2d), a simple 2D engine and wrapper over SDL2. It provides a direct C API for all the most common 2D graphics things, music, sound, input, etc. We can also build iOS and tvOS apps, and WebAssembly coming soon. We use this native engine for [Ruby 2D](http://www.ruby2d.com). Similar to Pyxel, it's an interpreted library (Ruby in this case) to create native graphics and games.

It's great to hear you're considering SDL2 — I think you'll see many benefits and enjoy having a large community to lean on. That said, there are still a lot of possible paths to take to integrate it with Pyxel. For example, you could write a custom C wrapper to SDL2, or use PySDL2, or only interface with Simple 2D if you don't want to deal with the intricacies of SDL or rendering backends at all. Also, and I'm not primarily a Python dev, but looks like there are several ways to interact with native libraries, like through [Python's C API](https://docs.python.org/3/c-api/) (similar what we do [in Ruby](https://github.com/ruby2d/ruby2d/blob/v0.7.0/ext/ruby2d/ruby2d.c)), or [ctypes](https://docs.python.org/3/library/ctypes.html). At any rate, happy to help!

**Comment by kitao** [comment]
@blacktm Thank you for the information! I checked your project and very surprised that it's very sophisticated. I'll refer to how to install and use SDL2 in your project.

**Comment by electrolys** [comment]
will the sdl2 version of pyxel have the ability to compile to exe

**Comment by kitao** [comment]
@electrolys I'm planning to support that feature though specific way is not decided.

**Comment by Cran3kill** [comment]
@kitao what is the state of SDL2 pyxel?

**Comment by electrolys** [comment]
could you release a beta for the sdl2 library

**Comment by kitao** [comment]
SDL2 version of Pyxel is developed in the feature-core branch.
But the current version only makes window and draw some test graphics with SDL2 because I have been busy working for this month.
Now the work settles down and I am back to development of the SDL 2 version, so I will accelerate development. Please wait a little more!

**Comment by jminor** [comment]
You might also find this project a useful reference: http://www.amulet.xyz
It is using SDL2, is cross platform, uses the same license and has similar goals to Pyxel - but is Lua based instead of Python.

**Comment by kitao** [comment]
@jminor Thank you for the information!

**Comment by kitao** [comment]
Finished!
