### ISSUE TITLE
No err when set integer over 15  as color

### ISSUE THREAD

**Issue by dannyso16** [kitao/pyxel#115]
**Describe the bug**
pyxel's color pallete is defined [0 - 15],  but I can set integers over 15 with no error.  
`pyxel.cls(20) # this raise no error`    

**Screenshots**
When I set col=16, a bar like rainbow appears in left side.  When col=20, noisy animation looks like mirror ball.  I feel this noise can be used as animation..
![col 16](https://user-images.githubusercontent.com/44456860/50504718-de354400-0ab2-11e9-9223-98154aa30a86.PNG)
![col 20](https://user-images.githubusercontent.com/44456860/50504723-e4c3bb80-0ab2-11e9-961f-0481c079ff52.PNG)

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
