### ISSUE TITLE
pyxel not running on Raspberry Pi

### ISSUE THREAD

**Issue by rkrishnasanka** [kitao/pyxel#116]
**Describe the bug**

So I've been trying to get pyxel to work on the Raspberry Pi with pretty bad luck so far. Initially it seemed like an issue with GLFW so I ended up doing the following:

1. Compile GLFW on the Raspberry Pi with the extensions
2. Enable OpenGL in Raspbian [(Source)](https://www.raspberrypi.org/forums/viewtopic.php?t=222264#p1363568)
3. Edit `pyxel` as suggested in #23 and installed the modified version of `pyxel`
 
```
Traceback (most recent call last):
  File "game.py", line 104, in <module>
    App()
  File "game.py", line 17, in __init__
    pyxel.init(200, 200, caption='cat game')
  File "/usr/local/lib/python3.5/dist-packages/pyxel-0.9.5-py3.5.egg/pyxel/__init__.py", line 181, in init
    App(module, width, height, caption, scale, palette, fps, border_width, border_color)
  File "/usr/local/lib/python3.5/dist-packages/pyxel-0.9.5-py3.5.egg/pyxel/app.py", line 169, in __init__
    self._renderer = Renderer(width, height)
  File "/usr/local/lib/python3.5/dist-packages/pyxel-0.9.5-py3.5.egg/pyxel/renderer.py", line 48, in __init__
    self._draw_shader = GLShader(DRAWING_VERTEX_SHADER, DRAWING_FRAGMENT_SHADER)
  File "/usr/local/lib/python3.5/dist-packages/pyxel-0.9.5-py3.5.egg/pyxel/gl_wrapper.py", line 12, in __init__
    shaders.compileShader(fragment_shader, gl.GL_FRAGMENT_SHADER),validate= False
  File "/home/pi/.local/lib/python3.5/site-packages/OpenGL/GL/shaders.py", line 196, in compileProgram
    program.check_validate()
  File "/home/pi/.local/lib/python3.5/site-packages/OpenGL/GL/shaders.py", line 108, in check_validate
    glGetProgramInfoLog( self ),
RuntimeError: Validation failure (0): 
O

```

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Device: Raspberry Pi

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
Now it depends on only SDL2. So please try the new version and let me know if there's some trouble.

**Comment by rkrishnasanka** [comment]
Awesome @kitao I'll let you know once I try it over the weekend

**Comment by rkrishnasanka** [comment]
@rkrishnasanka I finally got around to testing the system on the raspberry pi. Its finally working !! Thanks a lot for making the fixes. The only thing now is that I need to test out the framerates and see what I can do about it. I have a feeling that I need to move from the PiZero to something beefier.

**Comment by kitao** [comment]
@rkrishnasanka 
Great news!
Is it the same way of #149 ?

**Comment by rkrishnasanka** [comment]
Yup, its the same as #149 . I was looking to see if there's a way to detect processor architecture last night for a grand total of 2 minutes, that way you can load the correct shared library. Also, I figured that you need to kill the desktop and run from the command line to get a decent framerate:

![36wikb](https://user-images.githubusercontent.com/855696/62248843-14bf9e00-b3b7-11e9-81c5-4b72020de43c.gif)

Now I need to figure an application launcher for this. But thanks for the help !
