### ISSUE TITLE
GIF video capture doesn't work under Linux

### ISSUE THREAD

**Issue by marespiaut** [kitao/pyxel#118]
**Describe the bug**
The GIF video capture only produce a video of less than 1 second under Arch Linux, using Python 3.7.2 and pyxel 1.0.0.

**To Reproduce**
1. Launch game
2. Press Alt + Shift + 3 (on AZERTY keyboards)
3. End game after more than 30 seconds
4. Play the GIF

**Expected behavior**
The GIF animation should be longer than 0 seconds.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
