### ISSUE TITLE
Some elements not drawn in Pyxel 1.0.0

### ISSUE THREAD

**Issue by tamurashingo** [kitao/pyxel#119]
**Describe the bug**
Running 03_draw_api.py, some elements not drawn.
same as #45 

**To Reproduce**
1. run 'python 03_draw_api.py'
2. See error
- text not drawn
- dot not drawn
- circle not drawn

**Expected behavior**
- text drawn
- dot drawn
- circle drawn

**Screenshots**

<img width="795" alt="2019-01-27 10 05 01" src="https://user-images.githubusercontent.com/1601198/51850192-9a10ba00-2364-11e9-83d4-6b31d10be4d3.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6

- OpenGL 4.1
- Python 3.6.3
- glfw 1.7.0
- PyOpenGL 3.1.0

**Additional context**
I rewrote `shaders.py`, it seemed dots, circles, texts were shown correctly

```diff
diff --git a/pyxel/shaders.py b/pyxel/shaders.py
index 20868cc..8222d32 100644
--- a/pyxel/shaders.py
+++ b/pyxel/shaders.py
@@ -202,8 +202,8 @@ void main()
     vec2 p1 = floor(a_clip.xy + 0.5);
     vec2 p2 = floor(a_clip.zw + 0.5);

-    v_min_clip = max(min(p1, p2), v_min_pos);
-    v_max_clip = min(max(p1, p2), v_max_pos);
+    v_min_clip = v_min_pos;//max(min(p1, p2), v_min_pos);
+    v_max_clip = v_max_pos;//min(max(p1, p2), v_max_pos);
 }}
 """.format(
     RENDERER_IMAGE_COUNT,
```

<img width="795" alt="2019-01-28 17 51 02" src="https://user-images.githubusercontent.com/1601198/51850735-b2350900-2365-11e9-94ba-8556cfd5d160.png">

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.

**Comment by tamurashingo** [comment]
Greeeeeaaaaat!!!!!

Elements were drawn correctly!

<img width="944" alt="スクリーンショット 2019-06-19 21 11 38" src="https://user-images.githubusercontent.com/1601198/59765035-0a9a8200-92d8-11e9-8d09-c0dd49d1c326.png">
