### ISSUE TITLE
pyxeleditor "aborted (core dump)" on linux

### ISSUE THREAD

**Issue by FishFenly** [kitao/pyxel#120]
**Description**
pyxeleditor opens but then after a few seconds it crashes. If I run it from a terminal it outputs "aborted (core dump)"

**To Reproduce**
1. From a terminal run "pyxeleditor"
2. Move the mouse pointer over the pyxeleditor window
3. See error

**Screenshots**
![2019-01-31-145107_1920x1080_scrot](https://user-images.githubusercontent.com/5603501/52062608-bc732500-2568-11e9-9ef6-97a5eec311f5.png)
![2019-01-31-145058_1920x1080_scrot](https://user-images.githubusercontent.com/5603501/52062616-bf6e1580-2568-11e9-9674-7373f7fde691.png)

**Desktop:**
 - Archlinux 
 - i3wm

**Comment by FishFenly** [comment]
This is also happening when running pyxel applications. However, it is intermittent.

**Comment by FishFenly** [comment]
Stack trace:

                                                 Stack trace of thread 1562:
                                                 #0  0x00007fa16c9c7d7f raise (libc.so.6)
                                                 #1  0x00007fa16c9b2672 abort (libc.so.6)
                                                 #2  0x00007fa16c9b2548 __assert_fail_base.cold.0 (libc.so.6)
                                                 #3  0x00007fa16c9c0396 __assert_fail (libc.so.6)
                                                 #4  0x00007fa15e475204 n/a (libportaudio.so.2)
                                                 #5  0x00007fa15e47af3c n/a (libportaudio.so.2)
                                                 #6  0x00007fa15e47b701 n/a (libportaudio.so.2)
                                                 #7  0x00007fa16cb5ba9d start_thread (libpthread.so.0)
                                                 #8  0x00007fa16ca8bb23 __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 1550:
                                                 #0  0x00007fa16caefcb3 __memmove_avx_unaligned_erms (libc.so.6)
                                                 #1  0x00007fa16c75ce30 PyBytes_FromStringAndSize (libpython3.7m.so.1.0)
                                                 #2  0x00007fa16a6d68a7 array_tobytes (_multiarray_umath.cpython-37m-x86_64-linux-gnu.so)
                                                 #3  0x00007fa16c76cbb4 _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                                                 #4  0x00007fa16c7980ff _PyMethodDescr_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #5  0x00007fa16c7e3479 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #6  0x00007fa16c76c2eb _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #7  0x00007fa16c7dec42 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #8  0x00007fa16c76c2eb _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #9  0x00007fa16c7dec42 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #10 0x00007fa16c76c2eb _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #11 0x00007fa16c7dec42 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #12 0x00007fa16c76c2eb _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #13 0x00007fa16c7dec42 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #14 0x00007fa16c725b99 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                 #15 0x00007fa16c76c492 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #16 0x00007fa16c7dedfa _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #17 0x00007fa16c725b99 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                 #18 0x00007fa16c76c492 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #19 0x00007fa16c7e32b3 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #20 0x00007fa16c726c0b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                 #21 0x00007fa16c736908 _PyObject_Call_Prepend (libpython3.7m.so.1.0)
                                                 #22 0x00007fa16c784a73 n/a (libpython3.7m.so.1.0)
                                                 #23 0x00007fa16c7983ac _PyObject_FastCallKeywords (libpython3.7m.so.1.0)
                                                 #24 0x00007fa16c7e3cca _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                 #25 0x00007fa16c725b99 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                 #26 0x00007fa16c726ab4 PyEval_EvalCodeEx (libpython3.7m.so.1.0)
                                                 #27 0x00007fa16c726adc PyEval_EvalCode (libpython3.7m.so.1.0)
                                                 #28 0x00007fa16c850c94 n/a (libpython3.7m.so.1.0)
                                                 #29 0x00007fa16c8528be PyRun_FileExFlags (libpython3.7m.so.1.0)
                                                 #30 0x00007fa16c853c75 PyRun_SimpleFileExFlags (libpython3.7m.so.1.0)
                                                 #31 0x00007fa16c855eb7 n/a (libpython3.7m.so.1.0)
                                                 #32 0x00007fa16c8560fc _Py_UnixMain (libpython3.7m.so.1.0)
                                                 #33 0x00007fa16c9b4223 __libc_start_main (libc.so.6)
                                                 #34 0x000055ecceaf405e _start (python3.7)
                                                 
                                                 Stack trace of thread 1561:
                                                 #0  0x00007fa16cb61afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                 #1  0x00007fa15cbd7be4 n/a (i965_dri.so)
                                                 #2  0x00007fa15cbd7908 n/a (i965_dri.so)
                                                 #3  0x00007fa16cb5ba9d start_thread (libpthread.so.0)
                                                 #4  0x00007fa16ca8bb23 __clone (libc.so.6)

**Comment by kitao** [comment]
Thank you. I'll check it.

**Comment by acortes8** [comment]
This happens to me as well whenever I try to run any python file that uses pyxel. I'm using Manjaro which is Arch based, i3wm as well.

**Comment by liZe** [comment]
The bug is caused by a problem with sound management. A workaround is to launch an application playing some sound or dealing with sound (for example pavucontrol) before launching the pyxel application.

**Comment by JohnDowson** [comment]
I experience the same problem and I also use arch with i3wm.

**Comment by liZe** [comment]
> I experience the same problem and I also use arch with i3wm.

I use Gnome on Gentoo, so I think it's unrelated :wink:.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore. If there's something wrong, please let me know.

**Comment by liZe** [comment]
> So this issue should not occur anymore.

You're right, it's fixed. Thank you! This library is amazing…
