### ISSUE TITLE
the gamepad keys are completely off

### ISSUE THREAD

**Issue by electrolys** [kitao/pyxel#121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by electrolys** [comment]
i'm on windows 10 and i have a cheap logitech game remote from walmart and all of the buttons put in the  
constants are completely off

**Comment by kitao** [comment]
@electrolys 
I fixed the issue and released as 1.0.2.
Please check it.

**Comment by electrolys** [comment]
thank you ill check it soon

**Comment by electrolys** [comment]
I checked it and it still doesn't work

**Comment by kitao** [comment]
In the latest version of Pyxel, 1.1.2. Game controller works.
