### ISSUE TITLE
Default .pyxel extension kind of conflict with existing app

### ISSUE THREAD

**Issue by kamilko** [kitao/pyxel#123]
There is a small inconvenience if somebody use pyxeleditor from pyxel along with PyxelEdit (https://www.pyxeledit.com) because both generating default file as *.pyxel.
But those files are not compatible of course.
Using both editors on assets for project could be little "messy".

**Comment by kitao** [comment]
I renamed the extension from .pyxel to pyxres.

**Comment by emanoelbarreiros** [comment]
I have an old game I would like to get back to, but the resource file is in the old .pyxel extension. The pyxeleditor app refuses to open it. I renamed the file to have the .pyxres extension, but I keep getting this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  bad zip

I am runnin pyxel 1.3.0

**Comment by timbledum** [comment]
Update on this - @emanoelbarreiros was talking about my asteroids game (I think). I ended up having to manually recreate the new resource file in the new format and took me less time than I thought - but wish there was a way to convert the two.
