### ISSUE TITLE
Roadmap? 

### ISSUE THREAD

**Issue by ghost** [kitao/pyxel#127]
What is the main and side roads for Pyxel? What should we expect from it, any possibilities that Pyxel will work on mobile, i mean is there any roadmap?

**Comment by kitao** [comment]
I've finished the recent big milestone, SDL version of Pyxel.
Now I'm thinking about standalone binary version of Pyxel which may include MycroPython so that it runs on mobiles, but not decided.

If there's some good idea for the next milestone, please let me know.
