### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by idlesign** [kitao/pyxel#129]
Hi,

What's your take on localization for various languages?

I see two major approaches:
1. Have a huge ``FONT_DATA`` for all supported languages. No need to restart app to change language, but a memory penalty.
2. Have a number of modules with different ``FONT_DATA`` for different locales. Need to restart app and also to have some configuration options (argv) to activate the language you need. No way to use symbols from other languages.

What do you think?

Note: First step to facilitate localization is in #128

**Comment by kitao** [comment]
Sorry, I have no plan to export FONT_DATA and it is implemented in C++ in the latest SDL version of Pyxel.
