### ISSUE TITLE
[Feature Request] Always allow Pyxel to be used as a regular library.

### ISSUE THREAD

**Issue by carlsmith** [kitao/pyxel#13]
Pyxel is *awesome*! Thank you.

The ability to use a real editor and shell is really helpful. Editing code at 240x136 resolution looks cute, but it's not much fun after a while.

Just having an implementation of the TIC-80 API in Python3 is really cool in its own right, and it works well as a regular library.

Can you please commit to always allowing Pyxel to be used as we can now, even if it does add its own IDE components (shell, text editor, sprite editor etc), like other fantasy consoles?

It would be nice to have the sandboxed environment that other consoles have, with a simple shell. The deep integration of the sprite, audio and tile map editors is also very nice. It's running *everything* at 240x136 that's the problem.

I found Pyxel because I was looking for a way to build modern microcomputers - physical machines that work like a fantasy console. Is Pyxel a good choice for this?

The hardware spec is simple, and boils down to this:

```
PLATFORM:  A Raspberry Pi 3 Model B+. 
STORAGE:   Any 64GB UHS Micro SD card (or better).
DISPLAY:   Any 1280x1024 monitor, running at 60Hz.
AUDIO:     Any amplified stereo loudspeakers.
KEYBOARD:  Any ANSI mechanical keyboard.
MOUSE:     Any good quality five-button mouse.
PAD:       Any 8bitdo Pro pad (any generation).
```

The hardware specs will *never* change. Even though every console will be a clone (as the official console is a fantasy), the community is still based on the console that each member owns.

The 1280x1024 display would allow for six (pixel perfect) fullscreen resolutions:

| NAME   |  WIDTH  |  HEIGHT | SCALE |
|:--------|:-------:|:--------:|:-------:|
| maximum | 1280 | 1024 | 1 |
| high | 640 | 512 | 2 |
| medium | 320 | 256 | 4 |
| low | 160 | 128 | 8 |
| minimum | 80 | 64 | 16 | 

It [seems fairly easy][1] to replace the Pixel Desktop Environment (PixelOS is the new Raspbian) with a custom environment that just runs everything in full screen mode (a bit like ChromeOS).

[1]: https://www.linuxvoice.com/create-your-own-desktop-environment

The shell and various editors would run at the maximum resolution (1280x1024) in 24bit color. Games would run fullscreen (scaled up), obscuring everything else until they exit. Each game would use a *mode*.

Each mode would specify one of the five standard resolutions, a color palette and any other limitations (size of the sprite pool etc) that make sense for that mode (GB Mode, NES Mode, VCS Mode etc).

The software would be shipped as a custom Linux distribution that boots into the custom environment. The distro would bundle a ton of extra libraries, and a collection of open source assets.

Pyxel seems like a great library to build on, but it does not allow higher resolutions, larger palettes etc. If I added support for modes, would you accept a PR?

Sorry for such a long post. I'm very interested in this project, and wanted to introduce myself, so people know why I'm here. Thanks again for Pyxel. It's a really cool project.

**Comment by kitao** [comment]
Hi,

First, I don't have any plan to restrict Pyxel to run only standalone. I'll keep it as python module.

Second, you can run Pyxel application with arbitrary resolution. (Rather you must specify the window size because the init method needs the window size as its arguments)

Regarding your physical machine idea, I don't think it's good idea to use Pyxel for its base.
Because the concept of Pyxel is how to make it easy to start a game program. So I chose Python, popular language for beginners, and limited the number of palettes to 16 to make it easy to draw a picture. On the other hand, I don't make any speed limitation because it may make it difficult make a game. I don't think these features are suitable for physical machines.

**Comment by carlsmith** [comment]
> First, I don't have any plan to restrict Pyxel to run only standalone. I'll keep it as python module.

Sweet. That was the main concern. Thank you.

> Second, you can run Pyxel application with arbitrary resolution. (Rather you must specify the window size because the init method needs the window size as its arguments)

This does not seem to work for me. I tried a simple app at 160x128 and it worked fine. I changed the values to 320x256 (one of the resolutions I wanted to support), and it doesn't work correctly. It creates a large window with a dark grey background, with a smaller black screen inside it. The background color doesn't fill the black inner screen. It creates a square in the bottom-right corner.

> Regarding your physical machine idea, I don't think it's good idea to use Pyxel for its base...

Just to be clear, I wouldn't be using Pyxel to build the desktop environment or the editors that run on it. They'd be pretty conventional desktop applications. Pyxel would be used to provide users with an API for building games, pretty much as they'd use it now.

I understand the reason for simple limitations, and don't want to remove them. I just want to provide a range of modes, each enforcing a different set of limitations. For example, I'd like a mode that enforces something close to the Game Boy's 2bit palette and 160x144 resolution etc - just as an option.

Thank you for considering this, @kitao. I'm grateful for your time.

**Comment by carlsmith** [comment]
The PICO-8 community have developed syntax highlighters for popular text editors, as they do not like using their builtin editor either. That kinda spoils the experience though.

Deriving a Linux distro from PixelOS that runs our own tools would definitely be a viable option.

The tools would look and feel right (we would use pixel art icons, retro fonts etc), but still something people can realistically use over many projects.

Knowing the exact resolution of everybody's display also makes laying out user interfaces much less of a pain.

Also note that installing a custom distro is trivial on a RPi, as you only have to swap the SD card.

Once you go down the custom distro route, you can do a bunch of other stuff, like preventing the user from escaping the sandbox unless they really want to, bundling stuff like Python libraries and spritesheets. We can also make sure everything works out the box (like controller support).

And we have the fun of bikeshedding a fantasy microcomputer for everyone to clone.

I understand this is getting way off topic now. A lot of this stuff has nothing much to do with Pyxel, but I'd like to make the case for adding modes to Pyxel, so it can be used for projects like the one I'm describing, without needing to fork it.

Are there any technical objections to supporting modes, or would it be primarily a design choice?

Thanks again, @kitao, for considering this.

**Comment by carlsmith** [comment]
Sorrylast thing

**Comment by carlsmith** [comment]
I'm going to close the issue. The main question has an answer.

I'll look into adding modes, and we can discuss it once I have some code. I'm busy with a friend's app for now anyway, so it may take a while.

Thanks again.
