### ISSUE TITLE
Programmatic Fullscreen Mode

### ISSUE THREAD

**Issue by robinduckett** [kitao/pyxel#130]
I am unable to start my pyxel application in fullscreen mode by default, causing me to always need to hit Alt+Enter to fullscreen the game

I would like to be able to enter fullscreen mode by utilising a function call or as a parameter to pyxel.init()

I have tried to call the _toggle_fullscreen method on the App class directly but I am a novice with Python and do not know if it is even possible

**Comment by yuiio** [comment]
Maybe you can try something like that :

```
import pyxel

class App:
    def __init__(self):
        pyxel.init(160, 120)
        pyxel.app.App._toggle_fullscreen(pyxel._app) # toggle full screen here
        self.y = 0
        pyxel.run(self.update, self.draw)
    def update(self):
        fc = pyxel.frame_count % 20
        self.y = fc if fc < 10 else 20 - fc
    def draw(self):
        pyxel.cls(0)
        pyxel.text(54, 60 + self.y, 'Hello world !', 7)

App()
```

**Comment by robinduckett** [comment]
Thanks, I was not aware of the fact that the App class was available under pyxel.app - I didn't see that documented anywhere
