### ISSUE TITLE
Graphic problem 

### ISSUE THREAD

**Issue by wokwuk** [kitao/pyxel#131]
**Describe the bug**
When i launch a game or pyxeleditor or the palette, there is a graphic problem

**To Reproduce**
start the game

**Expected behavior**
no graphic problem

**Screenshots**
i join screen shot
1 for example 05_color_palette.py

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox
 - Version 66.0
![examplehello](https://user-images.githubusercontent.com/47194567/54871076-3b3d4f00-4daf-11e9-9fcc-c17e0359df77.JPG)
![exemplepalette](https://user-images.githubusercontent.com/47194567/54871077-3ed0d600-4daf-11e9-8b12-ccab84aaff2b.JPG)

**Additional context**
NVIDIA 210, with driver updated

**Comment by kitao** [comment]
Now Pyxel's rendering engine is replaced with SDL2-based version entirely .
So this problem must not happen any more.

**Comment by wokwuk** [comment]
Thx

Le dim. 16 juin 2019 à 11:46, Takashi Kitao <notifications@github.com> a
écrit :
