### ISSUE TITLE
Drawing a rectangle larger than the screen size causes it to be shifted

### ISSUE THREAD

**Issue by PureAsbestos** [kitao/pyxel#132]
**Describe the bug**
When drawing a rectangle to the screen, if the rectangle's coordinates lie outside of the screen, the rectangle is shifted, e.g. `rect(0, 0, 256, 256, 9)` on a screen of size (255, 255) will be shifted down and to the right one pixel.

**Expected behavior**
Drawing a rectangle larger than the screen should behave as if the screen were large enough to contain it. This can be achieved by clipping the rectangle's coordinates to the size of the screen.

**Screenshots**
[Example](https://imgur.com/n6td96k)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python Version: CPython 3.6
 - Pyxel Version: Latest release on pip

**Additional context**
I'm not sure if this problem affects other functions besides `rect`.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
