### ISSUE TITLE
Pythonic initialization of Pyxel (width/height)

### ISSUE THREAD

**Issue by PureAsbestos** [kitao/pyxel#133]
**Is your feature request related to a problem? Please describe.**
When initializing Pyxel, the width and height should be taken as the true resolution, not the maximum index value. This is the more intuitive and pythonic way to do it.
Example of such behavior in Python:
```python
>>> a = range(10)
>>> len(a)
10
>>> a[len(a)]
IndexError: range object index out of range
>>> a[len(a) - 1]
9
```

**Describe the solution you'd like**
If implemented, the following current version code:
```python
pyxel.init(255, 255)
```
would become:
```python
pyxel.init(256, 256)
```

Drawing calls would remain unchanged, e.g:
```python
pyxel.pix(0, 0)  # Top left
pyxel.pix(255, 255)  # Bottom right
pyxel.rect(0, 0, 255, 255)  # Rectangle the size of the screen
```

**Comment by kitao** [comment]
Because of OpenGL limitation, Pyxel limited the maximum size of the screen to 255 (users can use the position from 0 to 254)
But the new version restored its limits to 256.
So you can write pyxel.init(256, 256) and can draw from 0 to 255.
