### ISSUE TITLE
Remove color and resolution limits

### ISSUE THREAD

**Issue by PureAsbestos** [kitao/pyxel#134]
**Is your feature request related to a problem? Please describe.**
Resolution and color palette size limits seem pretty arbitrary. (I understand that the reason for the resolution limit is a limitation imposed by the way the renderer was implemented, see #26 #22)

**Describe the solution you'd like**
I'd like to be able to set whatever resolution and whatever palette I want. A maximum resolution of 1024x1024 and palette length of 256, however, would be OK. The default palette could still be the Pico-8 palette.

**Additional context**
Due to the limitations of the current implementation, fairly large changes would need to be made to accommodate larger screen sizes, but would likely be worth it. By contrast, removal of the palette length appears to be relatively easy to implement. 

It's worth noting that many 8-bit systems, such as the NES or Commodore 64, had specs exceeding the current limitations of Pyxel. (NES had more colors, C64 had a higher resolution)

**Comment by kitao** [comment]
Thank you for the comment.
Actually I'm thinking about implementing general retro game engine whose resolution and the number of colors can be specified. (It can be like Pixel Vision 8 - https://www.pixelvision8.com/ )

But regarding Pyxel itself, I'd like it to keep its spec and APIs as simple as possible for the programming beginners and retro game funs.

**Comment by PureAsbestos** [comment]
Thanks for replying; I'd appreciate it if you notified me somehow when/if you do implement a more general solution. I've seen Pixel Vision 8, but it doesn't use Python 😁

**Comment by Vlek** [comment]
Hello @kitao, sorry to necropost, but I was wondering if you would reconsider the resolution limit. I am working on creating some games specifically to use this on the [Gameboy GPi case](http://retroflag.com/GPi-CASE.html), which has a built-in screen that's 320x240. I would love to take advantage of the extra pixels instead of having the black bars.

**Comment by rafrafek** [comment]
Is the limit still there in the latest version?
