### ISSUE TITLE
GIF videos created by `_save_capture_animation()` can't be applied the change of fps

### ISSUE THREAD

**Issue by Cartman0** [kitao/pyxel#137]
**Describe the bug**
When changes 60fps `pyxel.init(128, 128, fps=60)`, it seems that 30 fps GIF video is created by function `_save_capture_animation()`.

**To Reproduce**
ex. run following code, then manually quit after 30 sec (1800 frame), result in created Gif video starts from 900 frame.

```python
import pyxel

class App:
    def __init__(self):
        pyxel.init(128, 128, caption="Hello Pyxel", scale=4, fps=60)

        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

    def draw(self):
        pyxel.cls(0)
        pyxel.text(
            0, 0, f"Hello, Pyxel! {pyxel.frame_count}", pyxel.frame_count % 16)

App()
pyxel._app._save_capture_image()
print("fps:", pyxel._app._fps)
print("capture_count:", pyxel._app._capture_count)
print("frame_count:", pyxel.frame_count)
pyxel._app._capture_start = 0
print("capture_start:", pyxel._app._capture_start)
pyxel._app._save_capture_animation()
```

**Expected behavior**
want 60 fps,Max 30 sec GIF Video

**Screenshots**
![pyxel-190415-033606](https://user-images.githubusercontent.com/10578703/56097473-a5b95900-5f2f-11e9-8520-1ad2824a5ed4.gif)

When set `pyxel._app._capture_start = 0`, do not start from 0 frame, starts from 900 frame.

**Desktop (please complete the following information):**
 - OS: Windows10
 - python 3.7.0
 - pyxel 1.0.2

**Comment by kitao** [comment]
This should be fixed in the new version of Pyxel, 1.1.1.
