### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by MushroomMaula** [kitao/pyxel#138]
**Is your feature request related to a problem? Please describe.**
In my opinion it's pretty hard to understand how, for example buttons etc. can be added /  work as there is no documentation for them. Furthermore I wish there was some explanation how event handeling with pyxel and works and how I could add my own events to a widget

**Describe the solution you'd like**
Extended Documentation ( for widgets and events) and more comments troughout the code as they are basicly nonexistent

**Comment by timbledum** [comment]
Although I agree that we could do with a bit more documentation, the reason you can't find anything about widgets or events is that pyxel doesn't provide widgets and pyxel is not event driven. 

Pyxel is function based – there's no inheritance like a standard gui.

You need to check for input and display everything to output every loop.

Have a look at the user samples here to get a better handle of how to use pyxel: https://github.com/kitao/pyxel/wiki#user-samples

**Comment by MushroomMaula** [comment]
I mean under pyxel/ui there are some widgets like a button inside of the `__init__` there are events added over `add_event_handler`. The thing I don't understand is how these events are called, as the `Widget.call_event_handler` just calls the handler which was added on the widget, but what calls this `call_event_handler` and with which possible events? It has to happen inside the main loop (I guess?), however the only event related call inside is `glfw.poll_events`, which does never call `Widget.call_event_handler`.
So how are events on widgets like the `ui.Button` "created" and how are they omitted and which events are possible?

**Comment by MushroomMaula** [comment]
Well I just realized as you said pyxel is not event driven that all the event processing for the widgets is implemented inside the update function of `pyxel/editor/app.py`.
I still think it would be good to add some more documentation or comments to help understand the code better and maybe add some examples on how to implement some widgets. Furthermore one could maybe add an README inside the ui that they are meant for the editor and if one wants to use them, oneself has to implement the event logic

**Comment by kitao** [comment]
Pyxel UI library is designed only for the Pyxel Resource Editor and it is not good idea to use it for the general purpose.

Probably I'll implement the general purpose UI library for the retro game engine because I want to make my own retro text editor. So please wait for it.
