### ISSUE TITLE
[Enhancement/Question] Integration with GUI frameworks (PySimpleGUI - tkinter, Remi, etc)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [kitao/pyxel#139]
This feature may already exist.  I'm unsure so guidance would be greatly appreciated.

I've been integrating a number of packages to PySimpleGUI which is based on tkinter, Qt, WxPython or Remi.  For example OpenCV, Matplotlib, pymunk, etc, have all been integrated on at least one of the PySimpleGUI ports.  pymunk worths with both the tkinter and the Web ports.  Here's a demo running on tkinter:
https://repl.it/@PySimpleGUI/Simple-pymunk-ball-game

**Describe the solution you'd like**
Get access to a PNG image that represents the screen image to be shown to the user.

Is it possible to integrate with a tkinter Canvas?  Or is there an image I can get that I can then draw into a Canvas or some other GUI's equivalent (SVgImage on Remi for example)

All of these integrations are "flip book" style drawing.  I simply get an image and draw it on some widget that's capable of displaying a PNG.

This Yolo Machine Learning demo is a good example
https://github.com/PySimpleGUI/PySimpleGUI/tree/master/YoloObjectDetection

It all comes down to OpenCV providing an image that I can then write to the display.

Here's a screenshot to demonstrate what I mean.  First there's a little GUI used to setup the parameters, get the filename, etc.  Then the YOLO algorithm works with OpenCV to provide an image.  I can then draw this image into a GUI window.  The posted  version added controls in that window that allow the user to modify parameters on the fly.  This screenshot only shows the window and an exit button.

![Yolo Video3](https://user-images.githubusercontent.com/13696193/56867508-ec896300-69b3-11e9-96d8-aec1af66d9d5.gif)

If I could get this capability with pyxel, then I can provide a GUI to programs that use pyxel should they wish to have a GUI that's not part of pyxel itself.

**Comment by kitao** [comment]
Though I'm not sure this feature solve this request, you can access the Pyxel's screen with the ``image`` API  in the latest Pyxel like this:

```python
screen_data_as_numpy_array = pyxel.image(4, system=True).data
```

For your information, image bank 0-2 is for user, 3 is reserved for system and mainly used for fonts and editor), 4 is mapped to the current screen.
When access to 3 or 4, you need to set the system option True.
