### ISSUE TITLE
SDL version of Pyxel will complete in a little more!

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#141]
Hi, Pyxel users.
New Pyxel with brand new native rendering engine starts working! (not complete yet)
It works at least 5-10 times faster than old version.

Old version:
<img width="478" alt="スクリーンショット 2019-05-04 17 19 39" src="https://user-images.githubusercontent.com/678802/57176652-5793d780-6e95-11e9-9d8a-b0cbb6f2e664.png">

New version (see the performance monitor on left top of the window):
<img width="473" alt="スクリーンショット 2019-05-04 17 18 09" src="https://user-images.githubusercontent.com/678802/57176655-5b275e80-6e95-11e9-82d4-700fd914df94.png">

99% of code of new Pyxel is implemented in C++ with SDL2 and Python wrapper is very thin.
So it will be very easy to transport Pyxel to other platforms and/or languages.

**Comment by rkrishnasanka** [comment]
@kitao does this mean that you removed the GLFW dependency? I've spent some time trying to get this work on the RPi and I've been having a ton of trouble.

**Comment by kitao** [comment]
@rkrishnasanka Yes. The newest Pyxel only depends on only SDL dll. It doen't need GLFW, numpy, pillow, 
 and sound module anymore.
Though audio player and GIF animation recorder are not implemented yet, I'll release it after finishing them.

**Comment by rkrishnasanka** [comment]
So I need to figure out SDL for RPi then, cool! I'll take a look at it in 3 weeks.

**Comment by yuiio** [comment]
@kitao Does it mean it will be more easy to distribute game with tools like [nuitka](http://nuitka.net/pages/overview.html) or [pyintstaller](https://www.pyinstaller.org/) ? I'm looking forward to this new version. Congratulations for your great job Kitao.

**Comment by kitao** [comment]
I've released the new version of Pyxel, 1.1.1.
It works with SDL and almost python module dependencies are removed.
Unfortunately it still depends on numpy. (probably removed in the future)
But I think it got easier to export standalone binary.
