### ISSUE TITLE
Get the color of a pixel

### ISSUE THREAD

**Issue by emanoelbarreiros** [kitao/pyxel#142]
Hi, guys. I am trying to learn more about pyxel and I'm trying to build a simple game. One thing I miss, though, is a way to get the color of a given pixel at (x,y). Is there a way to do this already? I scanned the docs and the examples but found nothing related to this feature. Thanks.

**Comment by kitao** [comment]
There's no API to get the pixel color on the screen and unfortunately there's no quick hack  to do this either. 
What are you planning to do?

(Actually, it's very easy to implement it in the next SDL-version Pyxel)

**Comment by emanoelbarreiros** [comment]
Hi, @kitao , thank you for the answer. I am learning to use the platform, and I implemented a simple shooting game. My first idea was to identify the pixel color under the mouse to detect if the shot hit the enemy. I know this is not the best idea (eventually I implemented a far better solution) but it would allow me to test my idea a bit faster.
