### ISSUE TITLE
The X, Y in the pyxel.image(0).load(X, Y, 'filename.png') must be negative to work when not zero.

### ISSUE THREAD

**Issue by Exadrid** [kitao/pyxel#143]
**Describe the bug**
The X, Y in the pyxel.image(0).load(X, Y, 'filename.png') must be negative to work properly. It works if it is 0 or negative.

This does not work properly (it loads something that is blank) - pyxel.image(0).load(255,255,'filename.png')

This works properly: pyxel.image(0).load(-255,-255,'filename.png')

**To Reproduce**
1. pixel.image(0),load(X, Y, 'filename.png' an image larger than 255 pixels and try to load the file starting at 255.
2. Try with "pyxel.image(0).load(255,255,'filename.png')" - it will fail.
3. Try with "pyxel.image(0).load(-255,-255,'filename.png')" it will work.

**Comment by kitao** [comment]
Could you check the new version of Pyxel, 1.1.1?
I rewrote the whole code with C++.
