### ISSUE TITLE
Enable copy/paste in the image editor

### ISSUE THREAD

**Issue by FilippoLeone** [kitao/pyxel#146]
A nice to have in the image editor would be a copy and paste functionality, sometimes I just need to change a few things on the original image and this could improve by far the speed at which I make some of the animation I work on.

**Comment by kitao** [comment]
Click the "select" icon, drag to specify the area, and press control + p / v, then you can use copy and paste in the image and tilemap editor.

Isn't this the feature you expect?

**Comment by FilippoLeone** [comment]
Hey @kitao thanks for your reply. 

I would like this feature to also be in the image editor, more specifically in the right column so you can do the same, use the select and then copy paste the area.
