### ISSUE TITLE
rect() treating w and h parameters as (x2, y2)

### ISSUE THREAD

**Issue by sponster-au** [kitao/pyxel#147]
**Describe the bug**
In pyxel 0.8.0, the rect() and rectb() methods are treating the parameters as (x1, y1, x2, y2, col) not as (x, y, w, h, col) as documented. 

**To Reproduce**
```
import pyxel

print(pyxel.VERSION)
pyxel.init(60, 120, scale=8)


def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()


def draw():
    pyxel.cls(0)
    pyxel.rectb(10, 20, 30, 40, 11)  # should draw a rectange of width 30 and height 40
    pyxel.line(0, 0, 30, 40, 12)    # the actual corner of the rect
    pyxel.line(0, 0, 40, 60, 13)    # expected corner of rectangle


pyxel.run(update, draw)
```

**Expected behavior**
I'd expect `rectb(10, 20, 30, 40, 11)` to draw a rectangle outline of width 30 and height 40.

**Screenshots**
<img width="592" alt="Screen Shot 2019-06-24 at 2 36 12 pm" src="https://user-images.githubusercontent.com/42725456/59992173-c4ee0880-968d-11e9-9a05-e465d3e71cd3.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5
 - pyxel 0.8.0, installed from pip
 - Python 3.7.3

**Comment by finetard** [comment]
As of version 1.1.3, issue seems to have fixed.

- Windows 8.1
- Python 3.7.3

![github issue](https://user-images.githubusercontent.com/13225616/60290959-7b284b00-9937-11e9-84d9-7021cec4be26.JPG)
