### ISSUE TITLE
Add Linux 32-bit library

### ISSUE THREAD

**Issue by GitRenhl** [kitao/pyxel#149]
I can't run pyxel on linux 32bit because "libpyxelcore.so" is for 64bit system.

```py
[...]
File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.7/dist-packages/pyxel/core/bin/linux/libpyxelcore.so: wrong ELF class: ELFCLASS64
```
Can you add library for Linux 32-bit system?

**Comment by dglaude** [comment]
I have a similar issue with trying to install on a Raspberry Pi4.
`
pi@raspberrypi4:~ $ sudo pip3 install pyxel
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyxel
  Downloading https://files.pythonhosted.org/packages/b2/14/40f3a2395a03d7d0418bccc855a8ede505483efb0772522f34bea95dc768/pyxel-1.1.4-py3-none-any.whl (4.9MB)
    100% |████████████████████████████████| 4.9MB 92kB/s 
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pyxel) (1.16.2)
Installing collected packages: pyxel
Successfully installed pyxel-1.1.4
pi@raspberrypi4:~ $ mkdir pyxel
pi@raspberrypi4:~ $ cd pyxel/
pi@raspberrypi4:~/pyxel $ python3 --version
Python 3.7.3
pi@raspberrypi4:~/pyxel $ install_pyxel_examples 
Traceback (most recent call last):
  File "/usr/local/bin/install_pyxel_examples", line 6, in <module>
    from pyxel.examples import install
  File "/usr/local/lib/python3.7/dist-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/pyxel/core/__init__.py", line 27, in <module>
    _lib = _load_library()
  File "/usr/local/lib/python3.7/dist-packages/pyxel/core/__init__.py", line 24, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.7/dist-packages/pyxel/core/bin/linux/libpyxelcore.so: wrong ELF class: ELFCLASS64
pi@raspberrypi4:~/pyxel $ ls
pi@raspberrypi4:~/pyxel $ file /usr/local/lib/python3.7/dist-packages/pyxel/core/bin/linux/libpyxelcore.so 
/usr/local/lib/python3.7/dist-packages/pyxel/core/bin/linux/libpyxelcore.so: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=485d756bb3488a90a2b92fbf4eccd6a0e6018d9d, not stripped
`
It seems bizarre pip3 would install binary... for another platform.

**Comment by GitRenhl** [comment]
I can run pyxel on my raspberry pi 3 now.
I cloned pyxel from github and I run `setup.sh` file (or `Makefile`, I don't remember). After that I coped `clone_path/pyxel/core/bin/libpyxelcore.so` to `/usr/local/lib/python3.7/dist-packages/pyxel/core/bin/linux/` and pyxel work!

**Comment by kitao** [comment]
As @GitRenhl wrote, it is possible to make pyxelcore library for other linux environment with ``make clean all`` command in pyxe/pyxel/core directory.

Problem is I don't have every build environment.
So I can only think of describing the build method for individual environment in README.

Do you have any good ideas?

BTW 32-bit linux is still popular?

**Comment by GitRenhl** [comment]
Hmm... I think the best solution is add description to README. 
I made this Issue before I noticed I can build it.

**Comment by kitao** [comment]
If I write down the instruction,

0) Install the SDL2 and SDL_image libraries for development
1) Download and unzip the zip file from github
2) Move into the unzipped directory
3) make -C pyxel/core clean all
4) pip3 install

Do you have any comments?

**Comment by GitRenhl** [comment]
Maybe like this?

## How to build
### Debian/Ubuntu
```
> sudo apt-get install libsdl2-dev libsdl2-image-dev
```
### MacOS
```
> brew install sdl2
```
### After installing SDL2
```
> git clone https://github.com/kitao/pyxel.git
> cd pyxel
> make -C pyxel/core clean all
> pip3 install <path>
```

**Comment by kitao** [comment]
Thank you, @GitRenhl 
I'll add the description to the manual in the next release.

**Comment by kitao** [comment]
I added the self-build instruction for unsupported environments to READMEs
