### ISSUE TITLE
Movement of constants module

### ISSUE THREAD

**Issue by timbledum** [kitao/pyxel#152]
Hiya!

All of my games relied on being able to access FONT_HEIGHT and FONT_WIDTH from the constants module in order to calculate font placement. This module had moved in 1.1.x, so all of my games are currently broken.

I suggest importing these constants to the main pyxel name-space so they can be used safely.

Just in general, I feel like 1.1 should have been a 2.0 release – the architecture change and breaking API changes were probably enough to warrant the major number change. At this stage, I'm considering just labelling my old games as pyxel<1.1.X which is a bit confusing for the installation process.

In addition, consider trying out the user sample games on the wiki to try out future versions to see whether any breaking changes are made?

Love the engine btw! Haven't tried the pyinstaller story yet, will do after I've got this working.

Cheers!
Marcus

**Comment by kitao** [comment]
Added the FONT_HEIGHT and FONT_WIDTH as constants in 1.1.6.

**Comment by timbledum** [comment]
Thanks!
