### ISSUE TITLE
Pyxel packager with PyInstaller

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#154]
Hi! I would like to make new utility command in Pyxel 1.2.0, which can make a standalone executable file.

It seems that it can be realized with PyInstaller, but I'm not familiar with it.

Could you give me some information about how to realize it by using Pyxel 1.1.x which uses SDL2?

**Comment by timbledum** [comment]
I'm a little bit familiar with pyinstaller, but not enough to do any real troubleshooting.

Just tried on windows and didn't seem to get far:

```
C:\python\pong\dist (master -> origin)
(pvenv) λ pong.exe
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes\__init__.py", line 356, in __init__
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pong.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\python\pong\pvenv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pyxel\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\python\pong\pvenv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pyxel\core\__init__.py", line 27, in <module>
  File "lib\site-packages\pyxel\core\__init__.py", line 24, in _load_library
  File "ctypes\__init__.py", line 434, in LoadLibrary
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\mcrouche\\AppData\\Local\\Temp\\_MEI204962\\pyxel\\core\\bin\\win64\\libpyxelcore.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[12852] Failed to execute script pong
```

**Comment by alderven** [comment]
For Windows I use [auto-py-to-exe](https://pypi.org/project/auto-py-to-exe/) to generate "One Directory" solution ("One File" solution not works for me - keyboard controls not responds).
It is important to include path `/pyxel/core/bin/win32/` with all [ZIP files](https://github.com/kitao/pyxel/tree/master/pyxel/core/bin/win32) to your output folder.

**Comment by kitao** [comment]
The reason that the PyInstaller doesn't work well is probably it lacks the Pyxel core binaries which is loaded as shared library by Pyxel's loading function.

So I'll try to exporter which copies the Pyxel binaries and make standalone exe with PyInstaller.

**Comment by kitao** [comment]
I added the Pyxel Packager (pyxelpackager) command in the Pyxel 1.2.0.
Please try it!

**Comment by alderven** [comment]
How to launch `pyxelpackager`?
I've tried running `pyxel-master\pyxel\packager.py` but nothing happens.

**Comment by kitao** [comment]
@alderven 
After installing the latest Pyxel from pip, execute the new command, 'pyxelpackager' command in the terminal.

**Comment by alderven** [comment]
Got an error:

```
C:\WINDOWS\system32>pyxelpackager d:\game.py
pyinstaller --clean --noconfirm --name=game --onefile --noconsole --add-data=c:\program files (x86)\python37-32\lib\site-packages\pyxel\core\bin\win32\libpyxelcore.dll:pyxel/core/bin\win32 game.py
usage: pyxelpackager [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                     [--add-data <SRC;DEST or SRC:DEST>]
                     [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                     [--hidden-import MODULENAME]
                     [--additional-hooks-dir HOOKSPATH]
                     [--runtime-hook RUNTIME_HOOKS]
                     [--exclude-module EXCLUDES] [--key KEY]
                     [-d {all,imports,bootloader,noarchive}] [-s] [--noupx]
                     [--upx-exclude FILE] [-c] [-w]
                     [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                     [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                     [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                     [--win-no-prefer-redirects]
                     [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                     [--runtime-tmpdir PATH] [--bootloader-ignore-signals]
                     [--distpath DIR] [--workpath WORKPATH] [-y]
                     [--upx-dir UPX_DIR] [-a] [--clean] [--log-level LEVEL]
                     scriptname [scriptname ...]
pyxelpackager: error: argument --add-data: invalid add_data_or_binary value: 'c:\\program files (x86)\\python37-32\\lib\\site-packages\\pyxel\\core\\bin\\win32\\libpyxelcore.dll:pyxel/core/bin\\win32'
```

**Comment by kitao** [comment]
Thank you.
I’ll fix it today! (in JST)

**Comment by kitao** [comment]
@alderven 
At least I fixed to use the proper separator depends on OS in 1.2.1. (';' for Windows, ':' for Mac and Linux)
But I don't have proper Windows environment to be evaluated for now.
So it would be appreciated if you check it works or not.

**Comment by alderven** [comment]
`exe` file successfully created. But it gives me an error when I run it:

![image](https://user-images.githubusercontent.com/21060932/62597215-fb09e380-b8ed-11e9-8588-129cec566672.png)

**Comment by inazmaster** [comment]
I have same problem on Windows 10.
![image](https://user-images.githubusercontent.com/20659411/62598668-1ba16000-b925-11e9-8ad1-9a5f70a3e0ce.png)

So I removed 'noconsole','onefile'  option in pyinstaller script and that result is below image. 
(OSError Korean means 'Can not find the module' )
![image](https://user-images.githubusercontent.com/20659411/62598638-03c9dc00-b925-11e9-9b48-56750ba9bbb1.png)

**Comment by alderven** [comment]
@kitao Works for me when I copied all ZIP files from `win32` folder (not only `libpyxelcore.dll`)

**Comment by inazmaster** [comment]
> uld b

Thank you!
In my case, that is win 64 folder.
But when I added '--onefile' option, There was a problem like below.
![image](https://user-images.githubusercontent.com/20659411/62603200-5eb50080-b930-11e9-8cfb-997181a7ea13.png)

I remove '--onefile' and I works successly! But I don't kwow how I can add '--onefile' option

**Comment by alderven** [comment]
@inazmaster 

It would work if you manually copy `assets` folder near the output `exe` file:

![image](https://user-images.githubusercontent.com/21060932/62605496-e6841600-b902-11e9-9cc3-55ed77da1591.png)

**Comment by inazmaster** [comment]
@alderven 
Wow I understand! Thank you!!!!!!

**Comment by kitao** [comment]
Thank you for information!

When --onefile option specified, the files are archived as one file and expanded when executed.
It seems that the loading path on Windows got wrong as a result of that. (It works on Mac)
I'll continue to investigate.

**Comment by kitao** [comment]
I probably fixed the Pyxel Packager in 1.2.2.
Could anyone confirm it on normal Windows environment?

**Comment by alderven** [comment]
Works fine for me on Windows 10.

@kitao thanks for cool feature!

**Comment by kitao** [comment]
Great!
