### ISSUE TITLE
Acceptable image size and color profile description

### ISSUE THREAD

**Issue by UnforeseenOcean** [kitao/pyxel#155]
**Is your feature request related to a problem? Please describe.** 
Yes - Photoshop PNG fails to load with `libpng` error shown below, and I can't afford Aseprite, so I want to convert the file to acceptable one but no such documentation exists for the format and the error handler just closes the entire editor.
![Image 285](https://user-images.githubusercontent.com/11834016/62002556-6eb72e00-b141-11e9-84a2-718478032f13.png)

**Describe the solution you'd like**
Add a line for the maximum acceptable size of the image in width and height, and acceptable color mode (RGB? Indexed? CMYK?) and export settings for Photoshop on the wiki alongside import guide.

**Describe alternatives you've considered**
File converter for the engine could be useful.

**Additional context**
This is the file I'm trying to import.
![Blackbeard_Logo_Pyxel](https://user-images.githubusercontent.com/11834016/62002568-b6d65080-b141-11e9-85a1-fc3f495aa33c.png)

**Comment by kitao** [comment]
@UnforeseenOcean 
Thank you! I'll check the image you uploaded.

**Comment by kitao** [comment]
I tried your png file and successed to show the image though there's a waning message.

Here's the code.

```python
import pyxel
  
pyxel.init(128, 128)
pyxel.image(0).load(0, 0, "./test.png")

def update():
        pass

def draw():
        pyxel.cls(8)
        pyxel.blt(0, 0, 0, 0, 0, 128, 128)

pyxel.run(update, draw)
```

I also successed to import the image in the Pyxel Editor.

![pyxel-190817-190121](https://user-images.githubusercontent.com/678802/63209880-79059000-c121-11e9-9b39-d8ba86e8fd7f.png)

Could you check it again in the latest version of Pyxel?

**Comment by UnforeseenOcean** [comment]
Okay, I will test it.

**Comment by UnforeseenOcean** [comment]
Okay, it does work. Thanks!
