### ISSUE TITLE
Keys does not honor local keyboard layout

### ISSUE THREAD

**Issue by dglaude** [kitao/pyxel#157]
**Describe the bug**
Does not respect the local keyboard mapping.

**To Reproduce**
Start the snake demo with a French keyboard.
Press Q it does not quit.
Press A it does quit.

**Expected behavior**
KEY_Q should map to a logical key depending on local rather than a physical key (= the position on a US keyboard).

**Desktop (please complete the following information):**
Raspberry Pi 4
 
**Additional context**
This is reopening of #56 issue.

**Comment by kitao** [comment]
@dglaude 
I changed the way to obtain key info in 1.2.1.
Now Pyxel doesn't use scancode.
Could you check it works correctly?
