### ISSUE TITLE
Cannot open file 'assets/jump_game.pyxres' in 'LoadAsset'

### ISSUE THREAD

**Issue by ibLeDy** [kitao/pyxel#159]
**Describe the bug**
After using pyxelpackager in 02_jump_game.py, running ./02_jump_game.py spits this error: "pyxel error: cannot open file '/home/bledy/projects/pyxel/pyxel_examples/dist/assets/jump_game.pyxres' in 'LoadAsset'"

**To Reproduce**
1. pyxelpackager 02_jump_game.py 
2. cd dist
3. ./02_jump_game.py 

**Expected behavior**
I expected 02_jump_game to launch as it usually should.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 5.0.0-23-generic
 - Version: 1.2.1

**./02_jump_game.py**
pyxel error: cannot open file '/home/bledy/projects/pyxel/pyxel_examples/dist/assets/jump_game.pyxres' in 'LoadAsset'

**ls assets**
cat_16x16.png
pyxel_logo_152x64.png
tileset_24x32.png
jump_game.pyxres
pyxel_logo_38x16.png

**pyxelpackager 02_jump_game.py**
pyinstaller --clean --noconfirm --name=02_jump_game --onefile --noconsole --add-data=/home/bledy/.local/lib/python3.7/site-packages/pyxel/core/bin/linux/libpyxelcore.so:pyxel/core/bin/linux --add-data=/home/bledy/projects/pyxel/pyxel_examples/assets/tileset_24x32.png:assets --add-data=/home/bledy/projects/pyxel/pyxel_examples/assets/cat_16x16.png:assets --add-data=/home/bledy/projects/pyxel/pyxel_examples/assets/pyxel_logo_38x16.png:assets --add-data=/home/bledy/projects/pyxel/pyxel_examples/assets/jump_game.pyxres:assets --add-data=/home/bledy/projects/pyxel/pyxel_examples/assets/pyxel_logo_152x64.png:assets 02_jump_game.py
190 INFO: PyInstaller: 3.5
190 INFO: Python: 3.7.3
191 INFO: Platform: Linux-5.0.0-23-generic-x86_64-with-Ubuntu-19.04-disco
191 INFO: wrote /home/bledy/projects/pyxel/pyxel_examples/02_jump_game.spec
321 INFO: An exception occured when testing for UPX:
322 INFO:   ValueError("invalid literal for int() with base 10: 'Usage'")
322 INFO: UPX is not available.
322 INFO: Removing temporary files and cleaning cache in /home/bledy/.cache/pyinstaller
323 INFO: Extending PYTHONPATH with paths
['/home/bledy/projects/pyxel/pyxel_examples',
 '/home/bledy/projects/pyxel/pyxel_examples']
323 INFO: checking Analysis
323 INFO: Building Analysis because Analysis-00.toc is non existent
323 INFO: Initializing module dependency graph...
325 INFO: Initializing module graph hooks...
325 INFO: Analyzing base_library.zip ...
2731 INFO: running Analysis Analysis-00.toc
2753 INFO: Caching module hooks...
2757 INFO: Analyzing /home/bledy/projects/pyxel/pyxel_examples/02_jump_game.py
3812 INFO: Processing pre-find module path hook   distutils
3932 INFO: Processing pre-safe import module hook   six.moves
6206 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
6579 INFO: Processing pre-find module path hook   site
6579 INFO: site: retargeting to fake-dir '/home/bledy/.local/lib/python3.7/site-packages/PyInstaller/fake-modules'
10546 INFO: Loading module hooks...
10546 INFO: Loading module hook "hook-numpy.py"...
10546 INFO: Loading module hook "hook-pydoc.py"...
10547 INFO: Loading module hook "hook-encodings.py"...
10580 INFO: Loading module hook "hook-xml.py"...
10580 INFO: Loading module hook "hook-sysconfig.py"...
10587 INFO: Loading module hook "hook-xml.dom.domreg.py"...
10587 INFO: Loading module hook "hook-pytest.py"...
11132 INFO: Loading module hook "hook-pkg_resources.py"...
11363 INFO: Processing pre-safe import module hook   win32com
11581 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
11582 INFO: Loading module hook "hook-pycparser.py"...
11582 INFO: Loading module hook "hook-setuptools.py"...
12000 INFO: Loading module hook "hook-numpy.core.py"...
12001 INFO: Loading module hook "hook-lib2to3.py"...
12002 INFO: Loading module hook "hook-distutils.py"...
12003 INFO: Loading module hook "hook-scipy.py"...
12023 INFO: Looking for ctypes DLLs
12172 INFO: Analyzing run-time hooks ...
12178 INFO: Including run-time hook 'pyi_rth_pkgres.py'
12179 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
12188 INFO: Looking for dynamic libraries
12542 INFO: Looking for eggs
12542 INFO: Python library not in binary dependencies. Doing additional searching...
12584 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0
12594 INFO: Warnings written to /home/bledy/projects/pyxel/pyxel_examples/build/02_jump_game/warn-02_jump_game.txt
12653 INFO: Graph cross-reference written to /home/bledy/projects/pyxel/pyxel_examples/build/02_jump_game/xref-02_jump_game.html
12663 INFO: Appending 'datas' from .spec
12664 INFO: checking PYZ
12664 INFO: Building PYZ because PYZ-00.toc is non existent
12664 INFO: Building PYZ (ZlibArchive) /home/bledy/projects/pyxel/pyxel_examples/build/02_jump_game/PYZ-00.pyz
13394 INFO: Building PYZ (ZlibArchive) /home/bledy/projects/pyxel/pyxel_examples/build/02_jump_game/PYZ-00.pyz completed successfully.
13402 INFO: checking PKG
13402 INFO: Building PKG because PKG-00.toc is non existent
13402 INFO: Building PKG (CArchive) PKG-00.pkg
25349 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
25350 INFO: Bootloader /home/bledy/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
25350 INFO: checking EXE
25350 INFO: Building EXE because EXE-00.toc is non existent
25350 INFO: Building EXE from EXE-00.toc
25350 INFO: Appending archive to ELF section in EXE /home/bledy/projects/pyxel/pyxel_examples/dist/02_jump_game
25481 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by kitao** [comment]
@ibLeDy Could you try 1.2.2?

**Comment by ibLeDy** [comment]
It runs as expected, this is pyxelpackager log:
pyinstaller --clean --noconfirm --log-level=WARN --onefile --noconsole --name=02_jump_game --hidden-import=numpy.random.bounded_integers --hidden-import=numpy.random.common --hidden-import=numpy.random.entropy --add-data=/home/bledy/.local/lib/python3.7/site-packages/pyxel/core/bin/linux/libpyxelcore.so:pyxel/core/bin/linux --add-data=/home/bledy/GITHUB/pyxel/pyxel_examples/assets/tileset_24x32.png:assets --add-data=/home/bledy/GITHUB/pyxel/pyxel_examples/assets/cat_16x16.png:assets --add-data=/home/bledy/GITHUB/pyxel/pyxel_examples/assets/pyxel_logo_38x16.png:assets --add-data=/home/bledy/GITHUB/pyxel/pyxel_examples/assets/jump_game.pyxres:assets --add-data=/home/bledy/GITHUB/pyxel/pyxel_examples/assets/pyxel_logo_152x64.png:assets 02_jump_game.py
8029 ERROR: Hidden import 'numpy.random.bounded_integers' not found
8029 ERROR: Hidden import 'numpy.random.common' not found
8029 ERROR: Hidden import 'numpy.random.entropy' not found

Thank you!

**Comment by kitao** [comment]
Good.
The errors in the log occur when the NumPy is not the latest version.
But it doesn't matter.
