### ISSUE TITLE
Add "How To Contribute" Section in the README.md

### ISSUE THREAD

**Issue by adamfaliq42** [kitao/pyxel#16]
I like the documentation so far. Clear and concise. I'd suggest to add a "How to Contribute" section next.

**Comment by RobRoseKnows** [comment]
A CONTRIBUTING.md would also be nice. I think GitHub has some bonus features when you add one.

**Comment by kitao** [comment]
Thank you. I'll check what other projects in GitHub explains for contribution.

**Comment by kitao** [comment]
I'm thinking about writing how to contribute in the Pyxel wiki.
But I'm not sure what I should write. Is there any good example to refer?

**Comment by christine-hu** [comment]
@kitao I'd suggest checking out CONTRIBUTING.md files in other repos, such as [this one](https://github.com/TEAMMATES/teammates/blob/c2be7e10141984c8b94e6140ef2885c3a17bffeb/docs/CONTRIBUTING.md)! The one I linked was quite extensive, but maybe you could start out by defining an official style guide for the code base. Love this project, btw! :)

**Comment by kitao** [comment]
Pyxel 0.9.0 manual  has the contribution section!
