### ISSUE TITLE
PyxelEditor crashes when using Sound Editor and pressing 'A' key

### ISSUE THREAD

**Issue by JoshuaKey** [kitao/pyxel#161]
**Describe the bug**
When using the Sound Editor and pressing various Keys. The application crashes with the message: "pyxel error: invalid sound index in 'PlaySound'". 
I specifically tried 'A' first but most other letter keys also fail.
This error also arises when I try to click on the keyboard with the mouse.
Looks like it stems from:
piano_keyboard.py Line 130: pyxel.play(1, pyxel.SOUND_BANK_FOR_SYSTEM)

**To Reproduce**
1. Run "pyxeleditor 'filename' " (I used highPitch)
2. Click on Sound Editor (3rd button)
3. Press 'A'
4. Application crashes
5. Command Line shows "pyxel error: invalid sound index in 'PlaySound'"

**Expected behavior**
Application does not crash.
<Optional> Application plays note

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python: 3.7.4

**Additional context**
I would like to help contribute to this problem.

**Comment by JoshuaKey** [comment]
Looks like the problem revolves around the use of SOUND_BANK_FOR_SYSTEM and EXTENDED_SOUND_BANK_FOR_SYSTEM. These values are 64 and 65 respectively.

The C++ backend instantiates an array of Sound Banks with a size of EXTENDED_SOUND_BANK_FOR_SYSTEM or 65. The last index, 64, is an exclusive Sound bank.

You can get access to this Sound bank by calling pyxel.sound(64, system=true). However PlaySound doesn't account for the EXTENDED_SOUND_BANK_FOR_SYSTEM and will only play up to index 63. Index 64 throws the error above.

A simple fix would be to change PlaySound() to use EXTENDED_SOUND_BANK_FOR_SYSTEM when checking for out of bounds, or adding a system variable similar to creating the sound.

What is the recommended solution?

**Comment by kitao** [comment]
Thank you for report. It's just my mistake.
Every sound index should use EXTENDED_SOUND_BANK_COUNT instead of SOUND_BANK_COUNT.
I'll fix it soon.

**Comment by kitao** [comment]
I fixed it in 1.2.3.
