### ISSUE TITLE
Pyxel Packager or Pyxel Exporter. Which name is more suitable?

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#162]
Hi,

I've implemented the stand-alone file exporter for Pyxel from the version 1.2.
But the name of the command cannot be decided completely because I'm not English native.

Which one is more suitable for the name of the commnad, Pyxel Packager or Pyxel Exporter?
Especially when considering the possibility of supporting other file formats such as html in the future

Thank you.

**Comment by timbledum** [comment]
I think Pyxel Packager is my preference - a bit more accurate and I think more friendly too. Both would work though.

**Comment by jamesguessis** [comment]
Pyxel Packager makes a lot more sense to me.

**Comment by kitao** [comment]
Thank you for the advice!
I'll keep the name of Pyxel Packager
