### ISSUE TITLE
pyxel.bltm cannot use mapchip of IMAGE No.1 and No.2 (IMAGE number is fixed by 0)

### ISSUE THREAD

**Issue by tinycore-hisanori** [kitao/pyxel#164]
When I use pyxeleditor and MapEditor.
I drew map-chip image on IMAGE No.2. And I made TILEMAP No. 0 with IMAGE No.2 map-chip.
But, map-chip image of All TILEMAP is fixed IMAGE No.0. 

I used pyxel.bltm command following,
pyxel.bltm(0,0,0,0,0,120,120)

I created TILEMAP No.0 with IMAGE No.2 mapchip. But, It showed TILEMAP No.0 with IMAGE No.0.

**Desktop (please complete the following information):**
 - OS: WINDOWS10
 - Version pyxel1.2.2

**Comment by kitao** [comment]
Right. Image index reference of Tilemap is not saved and loaded correctly. I'll fix it.
For now, please specify the image_index property of the Tilemap manually before using bltm.

**Comment by kitao** [comment]
I fixed it in 1.2.3.
