### ISSUE TITLE
A best way to create scenes, and switch between them.

### ISSUE THREAD

**Issue by jaronwanderley** [kitao/pyxel#165]
First I am a big fan of pixel games, and **pyxel** is very simple and easy, with his very simple API. But I miss being able to modularize my code, to have multiple screens (scenes) and to switch between them, a level calling another one. So my suggestion would be to create a **Scene Object**.

But if it is not the goal, due to the simplicity of the API, what is his real charm! What would be the best way for me to manage several screens (levels), would you have any suggestions?

If I'm wrong, about anything, please any suggestions are most welcome.

**Comment by jaxxgu** [comment]
Hey @jaronwanderley 
You could check [this repo](https://github.com/5h00T/mini_shooting)

**Comment by jaronwanderley** [comment]
> Hey @jaronwanderley
> You could check [this repo](https://github.com/5h00T/mini_shooting)

@jaxxgu  Thanks man! I loved it!!!!
