### ISSUE TITLE
Issue with `rect()` API

### ISSUE THREAD

**Issue by rkrishnasanka** [kitao/pyxel#171]
**Describe the bug**
Seems like the API for `rect()` is incorrect. The API is not working according to spec

**Comment by kitao** [comment]
Could you describe it more specifically?

**Comment by rkrishnasanka** [comment]
It seems like the older API `x, y, w, h, col` is not working as expected. I'm not exactly sure what is up with it but here's an example:

<img width="174" alt="Screen Shot 2019-09-02 at 12 09 13 AM" src="https://user-images.githubusercontent.com/855696/64089835-064a0680-cd16-11e9-9640-ddf6381b6ae3.png">
<img width="246" alt="Screen Shot 2019-09-02 at 12 09 07 AM" src="https://user-images.githubusercontent.com/855696/64089838-0a762400-cd16-11e9-9b21-e48853fe5850.png">

This should generate a square according to the API but that's not happening here

**Comment by kitao** [comment]
Which is the version of Pyxel?

Before 1.1.x, ``rect``'s format is ``(x1, y1, x2, y2, col)``
After 1.2.x, it's ``(x, y, w, h, col)``

**Comment by rkrishnasanka** [comment]
Ah! I need to check what's on my machine and the raspi. I guess I'm gonna close the issue then. I'm not really building any games at the moment, I'll modify the thing. Thanks !
