### ISSUE TITLE
Modify standard pyxel icon

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#174]
Is it possible to replace standard pyxel icon with custom one?

![image](https://user-images.githubusercontent.com/21060932/65421412-55aebe80-de0c-11e9-8188-73b952c42a1e.png)

Thanks!

**Comment by NeonMercury** [comment]
Seems that here is icon data: 

https://github.com/kitao/pyxel/blob/09b2a6d95594f3b804d365f06a9325509baefb00/pyxel/core/include/pyxelcore/constants.h#L70-L77
And here is ison set up: https://github.com/kitao/pyxel/blob/09b2a6d95594f3b804d365f06a9325509baefb00/pyxel/core/src/pyxelcore/window.cc#L55-L87

Thus, if you've asked about API to change the icon, then answer is no, replacement is not possible yet.

**Comment by kitao** [comment]
I think it's a good idea to be able to change the icon.
I don't have much time now, but I'll add an API when I can afford it.

**Comment by kitao** [comment]
In Pyxel 1.2.8, ``-i``option added to the pyxelpackager.
You can specify the icon file with the option.
