### ISSUE TITLE
Pyxel displays elements as if they are zoomed in.

### ISSUE THREAD

**Issue by jlpjr1999** [kitao/pyxel#175]
**Describe the bug**
When running a game the window seems to blow up the elements of the screen. 

**To Reproduce**
1. Run the program.

**Expected behavior**
The window should show a full pong menu, with two paddles on the side and a dotted line down the middle.

**Screenshots**
*My Window*
![image](https://user-images.githubusercontent.com/38260408/65653084-ef7b9480-dfe1-11e9-8384-c54f6c7495d6.png)
*Correct Window, Different Computer*
![pyxel_correct_screen](https://user-images.githubusercontent.com/38260408/65653068-e7bbf000-dfe1-11e9-9a09-2646903df06d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Version 1809

**Additional context**
The program was run using Atom with the Script package as well as IDLE and produced the same results. The same code does not produce the same error with the other person I am working with. Pyxel has been uninstalled and reinstalled using `pip install -U pyxel`. Python is on version 3.7.4.

**Comment by GitRenhl** [comment]
Check your pyxel version on both computers using this code:
```py
import pyxel
print(pyxel.VERSION)
```
I found your game source code [link](https://github.com/Vlek/Pyxel_Games) and it is working correctly on pyxel version 1.0.2.

Here is the pyxel version diffrent:
>1.0.2: `pyxel.rect(x1, y1, x2, x2, col)`
>greater then 1.0.2: `pyxel.rect(x, y, w, h, col)`

If you have installed Python3.6 the maximum pyxel version you can install is 1.0.2.

-------
So, I guess on `Correct Window, Different Computer`  you are trying to run your game on Python3.6 and on `My Window` Python3.7.

**Comment by jlpjr1999** [comment]
Thanks. It was a difference in pyxel versions as you had implied. I've updated the code using the suggestions on our page and the code works on my end.

Thanks for all of the help!
