### ISSUE TITLE
Drawing triangles

### ISSUE THREAD

**Issue by GitRenhl** [kitao/pyxel#178]
Can you add functions `tri` and `trib` with arguments `(x1,y1, x2, y2, x3, y3, col)` like in this repo [https://github.com/marespiaut/triangle.py](https://github.com/marespiaut/triangle.py).
Similar to #52 issue.

**Comment by kitao** [comment]
Good idea.
I'll add the APIs in the future release.

**Comment by YifangSun** [comment]
Any polygon and that border could be composed of `tri` and `line`. So I think triangle is useful.

**Comment by kitao** [comment]
Supported in 1.2.10
