### ISSUE TITLE
Flip image horizontally

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#183]
Sometimes I need to have image directed both left and right. So I have to draw 2 images:

![image](https://user-images.githubusercontent.com/21060932/67076735-6f86bb80-f196-11e9-8d5a-93805f93e196.png)

It would save lots of time to use additional argument like `flip_horizontally=True` to flip image:
`pyxel.blt(x, y, img, u, v, w, h, colkey, flip_horizontally)`

P.S. Also `flip_vertically` and `rotate` would be great, but `flip_horizontally` is most wanted feature.

**Comment by FilipLundby** [comment]
Regarding the flipping of the image - from the documentation: `If negative value is set for w and/or h, it will reverse horizontally and/or vertically.` 

https://github.com/kitao/pyxel#graphics

**Comment by alderven** [comment]
Thanks @FilipLundby!
