### ISSUE TITLE
Remove hard coded quit when Escape is pressed

### ISSUE THREAD

**Issue by FilipLundby** [kitao/pyxel#184]
**Is your feature request related to a problem? Please describe.**
I hope you will consider this small change - to remove hard coded quit when Escape is pressed - for the following reasons:

* Usually users expects Escape to toggle a menu. I'm currently working on some UI, but unfortunately using Escape is not an option right now.
* Game state (player stats, current level etc.) might get lost, because it's not possible to save before quitting.

**Describe the solution you'd like**
Remove hard coded quit completely and let developers use `pyxel.quit()`. 
 
**Describe alternatives you've considered**
* Allow overriding the default behavior.
* An option to disable the default behavior.

Thank you! :)

**Comment by kitao** [comment]
I understood the situation.
How about making the new system variable like "quit_key" and enabling to change the quit key through it?

**Comment by FilipLundby** [comment]
Do you mean something like: 
`pyxel.init(256, 256, quit_key = pyxel.KEY_Q)`

I guess that would work, if I can set the key to `None` as well.

**Comment by kitao** [comment]
Originally I thought I'll add the global module variable, but your idea seems more better.
So I'll add new option for the ``init`` function as you described.

**Comment by bnidevs** [comment]
@FilipLundby said he wanted to also have the ability to set the quit key to `None`, but it expects an integer or something convertible to an integer.

Is there an integer that's equivalent to having no quit key?

**Comment by bnidevs** [comment]
Looking at [this](https://wiki.libsdl.org/SDLKeycodeLookup), I assume it's 0?
