### ISSUE TITLE
二つのソースファイルを統合するAPIが欲しいです。（I want an API that integrates two source files.）

### ISSUE THREAD

**Issue by NanakiChi** [kitao/pyxel#186]
提案したいことは、題名の通りです。
たとえば、Aさんが音声を作り、Bさんが画像を作った場合、２つのソースファイルが存在します。
それを一つのゲームのソースとして使うのは、バラバラだと大変なので、一つのソースファイルに統合できる方法があったらいいと思います。

現状、友人と開発をしているのですが、二つのファイルを統合することがうまくできなくて困っています。

**Comment by NanakiChi** [comment]
友人が音楽のソースファイルを別のソースファイルにコピーして移すプログラムを作ったので代理投稿で提供します。
GITHUBのコメント欄のソースコード記述の仕様があまりわかっていないので不備があったら聞いていただければと思います。

`#CODING UTF-8`

`import os, sys, codecs, struct
import pyxel as pi`

`def exchange():`

    m = []
    n = ""
    o = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]
    [m.append(str(y)+str(x)) for x in range(4) for y in o ]
    print(m)

`def sound_copy():`
  `  l=["C0", "C#0", "D0", "D#0", "E0", "F0", "F#0", "G0", "G#0", "A0", "A#0", "B0", "C1", "C#1", "D1", "D#1", "E1", "F1", "F#1", "G1", "G#1", "A1", "A#1", "B1", "C2", "C#2", "D2", "D#2", "E2", "F2", "F#2", "G2", "G#2", "A2", "A#2", "B2", "C3", "C#3", "D3", "D#3", "E3", "F3", "F#3", "G3", "G#3", "A3", "A#3", "B3", "r"]`

    tspn = "TSPN"
    nsvf= "NSVF"
    pi.init(1, 1, caption="Sauce Copy Prompt", fps=10)
    for co in range(64):
        img2 = pi.load("./music.filename")  #コピー元音楽ファイル
        a = pi.sound(co).note
        b = pi.sound(co).tone
        c = pi.sound(co).volume
        d = pi.sound(co).effect
        e = pi.sound(co).speed
        no = ""
        to = ""
        vo = ""
        ef = ""
        sp = ""
        for x in a:
            if x == -1:
                no+=str(l[x])
            else:
                x-=12
                no+=str(l[x])
        for x in b:
            to+=tspn[x]
        for x in c:
            vo+=str(x)
        for x in d:
            ef+=nsvf[x]

        img = pi.load("./sourse.pyxres") #コピー先ファイル
        pi.sound(co).set(no,to,vo,ef,e)
        pi.save("./sourse.pyxres")

`sound_copy()`

**Comment by kitao** [comment]
I understand there is this type of need.
必要性はよくわかります。

How about adding the resource type option for the load API like ``load(filename, image=True, tilemap=True, sound=True, music=True)``, with this command, you can specify which resource type should be ignored?

loadコマンドにリソースタイプごとにロードの有無を指定するオプションをつけるというのはどう思いますか？

**Comment by NanakiChi** [comment]
なるほど、ありがとうございます！
Thank you!  :)
