### ISSUE TITLE
Specify version of glfw needed.

### ISSUE THREAD

**Issue by Neugierdsnase** [kitao/pyxel#19]
I ran into this error `AttributeError: module 'glfw' has no attribute 'set_window_size_limits'`
after installing what I think is the latest glfw version by running `apt-get install libglfw3` on Ubuntu since the glfw package from the README wasn't located. I wanted to check if the versions match but they aren't specified in the README. Could you please specify them/it?

**Comment by MiguelAlcaino** [comment]
I know that everyone hates the "it happens to me as well", but. It happens the same to me! I installed the same glfw version as you and also the dev package. But no luck.

I have Ubuntu 16.04. 

This is the complete error:

Traceback (most recent call last):
  File "game.py", line 3, in <module>
    pyxel.init(240, 240)
  File "/mypath/lib/python3.5/site-packages/pyxel/__init__.py", line 27, in init
    border_width, border_color)
  File "/mypath/lib/python3.5/site-packages/pyxel/app.py", line 65, in __init__
    glfw.set_window_size_limits(self._window, width, height,
AttributeError: module 'glfw' has no attribute 'set_window_size_limits'

**Comment by Mec-iS** [comment]
have you checked in #1 ?

**Comment by kitao** [comment]
I specified the version of GLFW in the READMEs.
Thank you for the report.
