### ISSUE TITLE
update examples

### ISSUE THREAD

**Issue by ddddtttt6666** [kitao/pyxel#195]
**Is your feature request related to a problem? Please describe.**
some examples don't even open!

**Comment by YifangSun** [comment]
Please describe it more detailed, then can we know what's going wrong. (∩_∩)

**Comment by ddddtttt6666** [comment]
they have minor bugs, for example
the snake game, when run says: 'module pyxel has no attribute FONT_HEIGHT and in the demo it should be changed to pyxel.constants.FONT_HEIGHT'
i will try to fix them all and i'll commit on a new branch.
(Amazing project BTW)

**Comment by ddddtttt6666** [comment]
and 'pyxel.tri' doesn't work

**Comment by YifangSun** [comment]
the binaries updated 20 hours ago, re-install the latest pyxel then problem might got solved
