### ISSUE TITLE
"pyxel.tilemap().get()" is not functioning properly (tilemap.getが機能していません)

### ISSUE THREAD

**Issue by NanakiChi** [kitao/pyxel#197]
Hello.
I was developing a game with pyxel today.
And  I found a bug when using tilemap().get().

I thought it might have happened because of the complex code in the game, 
and I experimented with simple test code, but I got the same error.

test code
```
#CODING UTF-8
import os, sys, re, random
import pyxel
class Window():
    def __init__(self):
        self.x = 160
        self.y = 96
        pyxel.init(self.x,self.y,caption = 'test',fps = 10)
        pyxel.load("./001_sause.pyxres") #The same bug happened with any source file
        pyxel.run(self.main,self.draw)
    def main(self):
        a = pyxel.tilemap(0).get(0,0)
    def draw(self):
        pyxel.cls(0)
        pyxel.bltm(0,0,1,0,0,20,16)
if __name__ == "__main__":
    w = Window()
    w.main()
```

error code
```
Traceback (most recent call last):
  File "D:\pyxel_data\001_Moneytest.py", line 24, in <module>
    w.main()
  File "D:\pyxel_data\001_Moneytest.py", line 16, in main
    a = pyxel.tilemap(0).get(0,0)
  File "C:\Users\Myname\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyxel\__init__.py", line 657, in tilemap
    _tilemap_bank[tm] = Tilemap(core.tilemap(int(tm)))
OSError: exception: access violation reading 0x00000004
```

If this is a bug in pyxel, I want you to fix it.

**Comment by kitao** [comment]
Thank you for report.
Could you try to modify the example 03 like this? I just added the first line of the update method.
```python
    def update(self):
        print(pyxel.tilemap(0).get(0, 0))
        self.pal_test_is_enabled = (pyxel.frame_count // 30) % 10 >= 5
        self.clip_test_is_enabled = pyxel.btn(pyxel.KEY_SPACE)

        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()
```
In my environment, this code works.
How about in your environment?

**Comment by NanakiChi** [comment]
example03 worked on my environment.
The OS error occurred because it was called after instantiation.
However, the correct number cannot be read from the tilemap using pyxel.tilemap (). Get ().
I created a game screen using pixeleditor.
And when reading the numerical value with pixel.tilemap (). Get () on the upper left and the right side of the screen, 128 is output. The other squares are 0. Those numbers were different from the expected numbers.
Please let me know if there is a way to solve these problems.

**Comment by kitao** [comment]
Could you write your platform (OS) and the version number of Pyxel?

**Comment by NanakiChi** [comment]
Sorry I forgot to write it.
My platform Windows10 Home.
Pyxel  ver.1.2.8

**Comment by NanakiChi** [comment]
Maybe a tilemap is set but not output.
https://pyxeledit.com/forum/discussion/1064/pyxel-edit-to-tiled
When I looked at the above site, there was no description in fixlog.md that the bug that the tile map could not be acquired was fixed.
I don't know if this information is useful, but I wanted to add it.

**Comment by kitao** [comment]
Could you try in 1.2.10?
最新版の1.2.10で再発するか確認してみていただけますか。

**Comment by zooid** [comment]
Issue still exists in 1.8.15

```
if pyxel.tilemap(0).get(self.snake[0].x /8, self.snake[0].y /8) == 5:
AttributeError: 'builtins.Tilemap' object has no attribute 'get'
```
