### ISSUE TITLE
Binaries need updating

### ISSUE THREAD

**Issue by YifangSun** [kitao/pyxel#198]
I meet some problems like other issues, and I guess the reason is:

- ##  API have updated
According to [CHANGELOG](https://github.com/kitao/pyxel/blob/master/CHANGELOG.md), APIs already updated 4 days ago. It did.
<div align="center">
Picture 1
</div>

![image](https://user-images.githubusercontent.com/39836849/68600275-31529280-04dd-11ea-9518-e05b42901357.png)

- ## Binaries have not updated
I found that "libpyxelcore.dll" didn't change since 10s days.
Maybe some new features have no update in it.
<div align="center">
Picture 2
</div>

![image](https://user-images.githubusercontent.com/39836849/68601359-23057600-04df-11ea-9948-f979bd59bf72.png)

**Comment by YifangSun** [comment]
**My problem:**

When I install pyxel-1.3.0, it alert an error:
![image](https://user-images.githubusercontent.com/39836849/68603398-26026580-04e3-11ea-825b-eb4f29e7eb59.png)

I think it's because GetConstantNumber function in libpyxelcore.dll  is old version, it can not check DEFAULT_QUIT_KEY, then is throw an error.
![image](https://user-images.githubusercontent.com/39836849/68603641-aaed7f00-04e3-11ea-993d-00494d320554.png)

**Comment by kitao** [comment]
I commit the new binaries.
