### ISSUE TITLE
Update the translations of the README

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#199]
This is a post for communicating with the translators of the documents.

**Comment by kitao** [comment]
@YifangSun @ccmorataya @dora-0 

I updated the following changes in the README.md for 1.2.10.

https://github.com/kitao/pyxel/commit/01fa5c473108a7c8045597722b741aafe7361adb#diff-04c6e90faac2675aa89e2176d2eec7d8

https://github.com/kitao/pyxel/commit/42ef0f4fc9affce7ebdca098067b8021280d0902#diff-04c6e90faac2675aa89e2176d2eec7d8

Could you update the translations of the develop branch?

**Comment by YifangSun** [comment]
BTW, I add tri describe in API Reference #202

**Comment by kitao** [comment]
Thank you, @YifangSun !
@ccmorataya and @dora-0 , could you translate the reference for tri and trib?

**Comment by ccmorataya** [comment]
Done, in #204 👍

**Comment by kitao** [comment]
@ccmorataya Could you also translate the API reference for ``tri`` and ``trib``?

**Comment by ccmorataya** [comment]
Sorry I've didn't notice, is done in #205

**Comment by kitao** [comment]
@YifangSun @ccmorataya @dora-0

Could you update the README in each language for the following change?

https://github.com/kitao/pyxel/commit/663f93fa8e701b518fde39825073f6dea0b9675e#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by ccmorataya** [comment]
@kitao Spanish README updated in #215

**Comment by kitao** [comment]
Hello,  @YifangSun  @ccmorataya @dora-0 

Could you translate the new API reference in the develop branch?

https://github.com/kitao/pyxel/commit/25b0d080bca900a644fe9d171fe4447a11c6a0af#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by humrochagf** [comment]
Hi, I looked through the old translations and saw that there was a former Portuguese translation. So I made a pull request to update it according to the current English version at the PR #226

**Comment by kitao** [comment]
Hi, @YifangSun @ccmorataya @dora-0 @humrochagf 
I hope everyone is doing well.

I updated the installation instruction of the README. 
Could you translate the following changes in the develop branch?

https://github.com/kitao/pyxel/commit/db5793fd86b6d5d8d5d4b7494fd03b9068abef47#diff-04c6e90faac2675aa89e2176d2eec7d8
https://github.com/kitao/pyxel/commit/feca0fe32376976ed226883c407516ebb96a34fc#diff-04c6e90faac2675aa89e2176d2eec7d8

Thank you in advance!

**Comment by humrochagf** [comment]
Done
