### ISSUE TITLE
Radnom segmentation faults in "02_jump_game.py"

### ISSUE THREAD

**Issue by programical** [kitao/pyxel#208]
When running the example "02_jump_game.py" with Python 3.7.3 on Debian 10, segmentation faults happen seemingly at random. 

I tried tracing the segfaults using [this method](https://stackoverflow.com/a/2663863/11617800):
```
line, 02_jump_game.py:96
line, 02_jump_game.py:97
call, /usr/local/lib/python3.7/dist-packages/pyxel/__init__.py:769
line, /usr/local/lib/python3.7/dist-packages/pyxel/__init__.py:770
line, /usr/local/lib/python3.7/dist-packages/pyxel/__init__.py:774
return, /usr/local/lib/python3.7/dist-packages/pyxel/__init__.py:774
Segmentation fault
```

**Comment by kitao** [comment]
Could you also inform the version of Pyxel?

**Comment by programical** [comment]
> Could you also inform the version of Pyxel?

1.2.10 according to pip.

**Comment by kitao** [comment]
Great information. I'll try to fix this issue on vacation.

**Comment by kitao** [comment]
This seems to have stopped happening with a few fixes, so I'll close it. Please let me know if something similar happens again.
