### ISSUE TITLE
pyxel.COLOR_PURPLE is misspelled as pyxel.COLOR_PERPLE 

### ISSUE THREAD

**Issue by fabiommendes** [kitao/pyxel#210]
A simple API typo: pyxel.COLOR_PURPLE is misspelled as pyxel.COLOR_PERPLE. We should probably keep COLOR_PERPLE as an alias to COLOR_PURPLE and remove it in 1.3.

**Comment by kitao** [comment]
Thank you. I fixed it in the develop branch.
