### ISSUE TITLE
Pymunk (physics) integration

### ISSUE THREAD

**Issue by fabiommendes** [kitao/pyxel#211]
I am implementing a simple integration with with the Pymunk physics engine and I am wondering if you have any interest to integrate it with pyxel as an optional module (e.g., pyxel.phys) or if should I keep it as a separate project installable using pip.

What currently works:
* Functions to draw pymunk.Shape's using pyxel rendering engine. 
* API to create pymunk objects using functions similar to the ones in pyxel (e.g.. phys.rect, phys.line, phys.tri, phys.circ)
* An automatic mainloop for users that simply want to run the simulation without any game interaction akin to pyxel.show()

What I may implement in the future
* Creation of joints, motors, etc
* Integrating texts and images
* Simple event system to register collisions and physics events
* Simple scheduler to manage animations and events
* Particle effects

![demo](https://user-images.githubusercontent.com/1248626/71483906-a9a0b900-27e8-11ea-928d-7d8a124f9007.gif)

**Comment by fabiommendes** [comment]
The animation above was created with this simple code:

```python
import pyxel
from pyxel import phys

pyxel.init(120, 80, fps=60, caption='Physics demo', scale=4)
space = phys.space(bg=0, col=1, gravity=(0, 10))
phys.margin()

ball = phys.circ(10, 10, 5, vel=(50, 50), mass=1, moment=50, col=pyxel.COLOR_RED)
line = phys.line(50, 50, 75, 25, vel=(0, 0), mass=2, moment=200, col=pyxel.COLOR_GREEN)
tri = phys.tri(100, 50, 100, 25, 80, 50, vel=(0, 0), mass=4, moment=300, col=pyxel.COLOR_ORANGE)
rect = phys.rect(0, 60, 10, 15, vel=(10, -10), mass=2, moment=100, col=pyxel.COLOR_CYAN)

space.run()
```

The real animation is slightly more fluid than the gif above

**Comment by kitao** [comment]
Sorry for late reply.
Thank you for the information!
I'd like to keep the spec of Pyxel as simple as possible.  So please release it as the separated module.
