### ISSUE TITLE
Pyxel's new palette

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#217]
Now I'm considering a new palette for Pyxel.
Please give me feedback on it.

![pyxel-palette](https://user-images.githubusercontent.com/678802/72732939-36694780-3bda-11ea-9a8e-a14920b1307e.png)
![nog20200119b_sample拡大](https://user-images.githubusercontent.com/678802/72732943-39643800-3bda-11ea-9f3f-7e095884cecb.png)
![nog20200120a_8x8ACT拡大](https://user-images.githubusercontent.com/678802/72732951-3a956500-3bda-11ea-85c8-1436bb8ca95b.png)
![nog20200120c_8x8拡大](https://user-images.githubusercontent.com/678802/72732957-3bc69200-3bda-11ea-9dbd-79dc7b94df16.png)

**Comment by jaronwanderley** [comment]
What if we could have a method for setting the color palette?
So we could create a game with a color palette chosen by the developer, or even be able to create different levels by changing the colors of the color palette. 

Or even, create animations in sprites by changing the color palette. Like this “Color Cycling in Pixel Art” por Stephen Schroeder https://link.medium.com/RS44tKZp33

**Comment by kitao** [comment]
Hi, @jaronwanderley 
It is possible to specify the custom palette when initializing Pyxel with the arguments.
Also possible to change the drawing color with ``pal`` command dynamically.

**Comment by kitao** [comment]
New Pyxel's palette is fixed. Thank you.

**Comment by merwok** [comment]
Hope it’s ok to ask here: is there a way to specify custom palette in the editor too?

**Comment by nbghjh** [comment]
what would specifying a color palette using augments in the initialization look like

**Comment by nbghjh** [comment]
what would specifying a color palette using augments in the initialization look like

**Comment by merwok** [comment]
It’s not in the init function (if that’s what you meant), see the docs here: https://github.com/kitao/pyxel/#graphics

**Comment by nbghjh** [comment]
thank you
