### ISSUE TITLE
Games do not render correctly beyond 256x256 resolution.

### ISSUE THREAD

**Issue by carlsmith** [kitao/pyxel#22]
If you pass a width or height to `pyxel.init` that is above 256, the rendering is broken. The background color does not fill the screen properly (there is a black margin around the top and sides).

Above 256x256, the `pyxel.cls` command does not work correctly either. Things just blit over each other, so you can still see artifacts from previous frames.

At Line 40 in `constants.py`, two constants are defined:

``` python
RENDERER_IMAGE_WIDTH = 256
RENDERER_IMAGE_HEIGHT = 256
```

That code is presumably why everything works up to 256 pixels, and immediately breaks beyond that.

I'm still figuring out how the code works, so don't know how to fix this yet.

**Comment by kitao** [comment]
Oh. It's my fault.
I used the max function instead of the min function in the largest_power_of_two method in renderer.py.
I'll fix and test it.

**Comment by kitao** [comment]
@carlsmith 
Sorry, let me confirm the situation again.

Pyxel's application window is resizable and when the window size is changed, its rendering area is also changed to the largest pixel perfect scaled size.
For example, if the application initialized as 100x100 and the window size is 300x250, pyxel changed the scale to 2 automatically, and as a result, rendering area size will be 200x200.
(Actually, I also forgot about this specification, sorry!)

Normally, when the application is initialized, first, Pyxel try to make the window expanded 4 times and if its size is larger than OS's window size limitation, change the window size to the allowed maximum size. After that, the rendering area will be changed automatically as I wrote.

On the other hand, regarding `cls` behavior, I don't know what happens for now.

So could you try set the scale option and check what happen again?
like this:
`pyxel.init(100, 256, scale=3)`

Thank you!

**Comment by kitao** [comment]
This bug is caused by the same reason as #26 
As explained in #26 ,unfortunately it it difficult fix this bug in the current implementation.
So please treat this as a specification of Pyxel for now.
I'll add the limitation of window size to the READMEs.

**Comment by carlsmith** [comment]
I'll try that later today. Thanks for taking the time to look into it, and explaining the situation.
