### ISSUE TITLE
Doesn't install on Ubuntu 

### ISSUE THREAD

**Issue by bakirillov** [kitao/pyxel#228]
**Describe the bug**
`pip install -U pyxel` 
fails with an error:
 `class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'

ERROR: Command errored out with exit status 1: /home/bakirillov/anaconda3/envs/lapki/bin/python /home/bakirillov/anaconda3/envs/lapki/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jo98jnqi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output
`
libsdl-dev is up-to-date (2.0.10+dfsg1-1ubuntu1).
libsdl-image-dev is also up-to-date (2.0.5+dfsg1-1).
Python - 3.7.5.

**To Reproduce**
1. Run `pip install -U pyxel`

**Expected behavior**
It should have installed pyxel.

**Screenshots**
![image](https://user-images.githubusercontent.com/30053869/77154108-19eb6d80-6aac-11ea-9546-d8d2be6e9c57.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10

**Comment by accidentalrebel** [comment]
There are [other](https://github.com/iterative/dvc/issues/1582#issuecomment-461257304) [packages](https://github.com/iterative/dvc/issues/1995#issuecomment-491889669) that has the same error as below:
` AttributeError: module 'enum' has no attribute 'IntFlag'`

The solution that they found was uninstalling the `enum34` package. Have you tried this?

**Comment by bakirillov** [comment]
> There are [other](https://github.com/iterative/dvc/issues/1582#issuecomment-461257304) [packages](https://github.com/iterative/dvc/issues/1995#issuecomment-491889669) that has the same error as below:
> ` AttributeError: module 'enum' has no attribute 'IntFlag'`
> 
> The solution that they found was uninstalling the `enum34` package. Have you tried this?

Tried that now, it works! Thank you very much. Will mark the issue as closed.
