### ISSUE TITLE
Call pyxel.quit() without python app quit or with exit callback

### ISSUE THREAD

**Issue by int-0** [kitao/pyxel#231]
Hi,
I'm making a network based game using pyxel. When pyxel quits, the python app it's destroyed but I'm need to shoutdown networking before that. Can I stop the game loop without exit the entire python application?, or, alternatively, can I define exit callback to be called by pyxel.quit() before it exists? I'm trying with **atexit** module but callbacks are ignored.

Thank you!

**Comment by ddekany** [comment]
Yeah, it just exits with an OS level `exit(0)` call in the core C code, which is brutal. Python `finally`-s won't run, etc. Thonny (a Python IDE used in education) hates that for example too, so I also vote for Pyxel becoming a good Python citizen in this regard.

**Comment by kitao** [comment]
I've already fixed this issue in the latest development version of Pyxel.
After the end of the translations of the READMEs, I'll release it. (Now I'm searching for translators of Spanish and Korean)

**Comment by kitao** [comment]
I've released 1.3.2 supports mannered exit way.
