### ISSUE TITLE
It is difficult to understand the correspondence of the arguments of the blt function

### ISSUE THREAD

**Issue by Tree-frog-code** [kitao/pyxel#232]
Hello. I am a pyxel newbie.
When using pyxel's blt function, it was difficult to determine which argument played what role.
I thought it would be nice to use pyxel.blt's arguments as keyword arguments.
Alternatively, prepare a function that wraps the pyxel.blt function and make it compatible with the previous function.

**Comment by kitao** [comment]
All of the current arguments of `blt` is mandatory information that cannot be omitted.
And I would like to avoid to lengthy function call code. So let me keep the current specification.
