### ISSUE TITLE
Is it possible to change the cursor icon?

### ISSUE THREAD

**Issue by gachis** [kitao/pyxel#233]
Is it possible to change the cursor icon?

**Comment by Tree-frog-code** [comment]
Hello! The question is whether you can change the cursor image, but I think that you can change the cursor image by replacing the cursor image with another image. I looked at `test_resource.pyxres` in `/ pyxel/editor/assets`, thinking there was a cursor image, but there was no cursor image.
Therefore, **I think that the image of the cursor is generated in the source code.** Write something on lssues if you know something again.

**Comment by kitao** [comment]
Hi.
There's no function to change the icon image.
But you can get the position of the mouse cursor when the cursor is not visible.
So by setting the cursor invisible and drawing some image at the position of the cursor instead, you can realize to change the cursor image.

**Comment by Tree-frog-code** [comment]
Hi I have found my guess is incorrect.  I think it makes sense to invalidate the original image and activate the new one.  BTW, **I want to hear one, but the editor wants to know where to read the information of the image of the cursor.**

**Comment by gachis** [comment]
> Hi.
> There's no function to change the icon image.
> But you can get the position of the mouse cursor when the cursor is not visible.
> So by setting the cursor invisible and drawing some image at the position of the cursor instead, you can realize to change the cursor image.

Thank you, it was simple to make it work

I tried this @Tree-frog-code 

```
def update(self):
 pyxel.rect(pyxel.mouse_x, pyxel.mouse_y, 10, 10, 11)
def draw(self):
 pyxel.rect(pyxel.mouse_x, pyxel.mouse_y, 10, 10, 11)

```

**Comment by kitao** [comment]
@gachis You only need to write the rect command in the draw function.
The update's one is not necessary.

**Comment by Tree-frog-code** [comment]
Hi! I thought the first question meant changing the mouse cursor in the **editor that came with Pyxel.** If you want to make a mouse cursor from the beginning, I think the method of @gachis  is good.
