### ISSUE TITLE
Snippets for Pyxel  and a makeshift IDE for pyxel in Atom

### ISSUE THREAD

**Issue by OscarDSanchezJ** [kitao/pyxel#235]
I made a snippet for ATOM and with collaboration in VSCODE, for the framework and I would like your help, to improve and convert them into packages from both editors if they find it useful.

https://github.com/OscarDSanchezJ/Pyxel-Snippets-Package

For Atom there is a way to convert your editor into an IDE for Pyxel, installing "Python-run" and "python-Virtualenv" packages in community extension packages of Atom.

I hope this information was helpful to you.

it's my first Issue direct help and collaboration in
 this engine :)

**Comment by gachis** [comment]
Works like a charm in Atom

**Comment by kitao** [comment]
Thank you for sharing the information. I'll share it at some point in time.
