### ISSUE TITLE
Please update the translation of the READMEs

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#237]
Hello, @YifangSun @ccmorataya @dora-0 @humrochagf

Thank you for translating the READMEs.
For the next release, I have updated the README in English.
Could you update the translation in each language in Develop branch?

I changed four parts:

- modified Installation instruction
https://github.com/kitao/pyxel/commit/db5793fd86b6d5d8d5d4b7494fd03b9068abef47#diff-04c6e90faac2675aa89e2176d2eec7d8

- new API for mouse wheel
https://github.com/kitao/pyxel/commit/1143b436152d2dd043fb05fe06195e921851df78#diff-04c6e90faac2675aa89e2176d2eec7d8

- new option for the init API
https://github.com/kitao/pyxel/commit/8369951c6903e75ce9dc57ef19e83ec15c932f42#diff-04c6e90faac2675aa89e2176d2eec7d8

@humrochagf 
Sorry, I should have done all the updates at once. Can you translate the other two parts as well?

**Comment by humrochagf** [comment]
No problem at all 😊

**Comment by kitao** [comment]
Translates of Portuguese and Chinese are complete.

Can anyone translate the changes of the English README, which are almost 4 lines of text, into Korean and Spanish?

Once the translation is complete, I'll release the new version of Pyxel.

**Comment by kitao** [comment]
Now all of the READMEs are translated.
Since I've used Google Translate in several places, if there is anything wrong with the translation, please let me know or send PR!

**Comment by kitao** [comment]
@YifangSun @ccmorataya @dora-0 @humrochagf 
Thank you for the translation every time!

I updated the installation instruction in the READMEs in the develop branch.
Could you translate it into each language? It's a change of a few lines.
Thank you in advance.

https://github.com/kitao/pyxel/commit/86a96ff7ed14decbaaa521304282cf7e4df343ee#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by kitao** [comment]
Finished
