### ISSUE TITLE
New quit() function on windows

### ISSUE THREAD

**Issue by nemillo** [kitao/pyxel#241]
When using the new quit function on Windows 10 + Python 3.8.2 the following error message appears

  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pyxel\__init__.py", line 554, in update_wrapper
    quit()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pyxel\__init__.py", line 567, in quit
    core.quit()
OSError: [WinError 541541187] Windows Error 0x20474343

**Comment by kitao** [comment]
@nemillo Could you give me more information?

When you press ESC while running the Pyxel appliation, what happens?
You called pyxel.quit in the update or draw function?

**Comment by nemillo** [comment]
Hi,

ESC key works normally and quits application succesfully

In my app i am calling pyxel.quit from update function (you can check same error reproduces itself on example application/07_snake.py  )

I have tried to move pyxel.quit to draw function. Error stays the same.

BR

**Comment by kitao** [comment]
Thank you. I slightly modified the exit way and released it as 1.3.3. Could you upgrade Pyxel and try if again?

**Comment by nemillo** [comment]
Function quit() is OK now on 1.3.3

Thank you
