### ISSUE TITLE
Pyxel Discord server starts!

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#245]
Thanks to your support, Pyxel's Discord server is now up and running!
Please feel free to join.

- [Discord server (English)](https://discord.gg/FC7kUZJ)
- [Discord server (Japanese - 日本語版)](https://discord.gg/qHA5BCS)

**Comment by kitao** [comment]
The Pyxel Gam was also held on these server.

**Comment by joemanu23** [comment]
u should put the discord link in the readme ... ^^
