### ISSUE TITLE
Import failed on Anaconda 3 on Mac OS Catalina 10.15.4

### ISSUE THREAD

**Issue by projetmbc** [kitao/pyxel#246]
Here is the error I have when I just try to import pyxel.

```
> python /Users/login/test.py
Traceback (most recent call last):
  File "/Users/login/test.py", line 3, in <module>
    import pyxel
  File "//Users/login/anaconda3/lib/python3.7/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "//Users/login/anaconda3/lib/python3.7/site-packages/pyxel/core/__init__.py", line 43, in <module>
    _lib = _load_library()
  File "//Users/login/anaconda3/lib/python3.7/site-packages/pyxel/core/__init__.py", line 40, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "//Users/login/anaconda3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "//Users/login/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(//Users/login/anaconda3/lib/python3.7/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Library not loaded: /usr/local/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib
  Referenced from: //Users/login/anaconda3/lib/python3.7/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
  Reason: image not found
```

**Comment by kitao** [comment]
@projetmbc Could you tell how you installed Pyxel for Anaconda?

**Comment by projetmbc** [comment]
I have installed it using pip shipped by Anaconda.

**Comment by kitao** [comment]
How about SDL2 and SDL2-image?

**Comment by projetmbc** [comment]
Which name is used in the Python evironment for this ?

**Comment by projetmbc** [comment]
Ok the problem comes from this. I will folow the instruction and then close this comment if the bug was me. ;-)

**Comment by kitao** [comment]
You only need to install `sdl2`, `sdl2-image`, and `gifsicle` with `brew` command. You don't need to install `python3` because it has already been installed with Anaconda.

**Comment by projetmbc** [comment]
So easy. Sorry for this is not a bug comment.

I have a little suggestion. In the doc you should write something like this for "stupid" guy like me. :-)

***First, in the environment where Homebrew package manager is installed, install the required packages with the following command:***

`brew install sdl2 sdl2_image gifsicle`

***If you don't already have Python3 (version 3.6.8 or higher), you can install it using the following command:***

`brew install python3`

Thanks a lot for your funny project !

**Comment by kitao** [comment]
I added the cautionary statement.
