### ISSUE TITLE
Can't modify cursor and app icons

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#248]
**Describe the bug**
When I change colors using `palette` variable, cursor and app icon colors also changes:

![изображение](https://user-images.githubusercontent.com/21060932/82781213-dde4d800-9e61-11ea-96be-cdd996565679.png) ![изображение](https://user-images.githubusercontent.com/21060932/82781355-3e741500-9e62-11ea-9511-66d0ce2cb711.png)

**Expected behavior**
I'd like to see cursor and app icon colors unchangeable or be able to change them manually.

**To Reproduce**
1. Initialize app with custom `palette`
2. Enable cursor visibility `pyxel.mouse(visible=True)`
3. See, that cursor colors have changes as well as app icon colors

**Desktop:**
 - OS: Windows 10
 - pyxel 1.4.0

**Comment by kitao** [comment]
Thank you for reporting. Certainly this happens. I'll think how to handle this.

**Comment by kitao** [comment]
In 1.4.1, I fixed the icon not to get affected by the changed libraries.

**Comment by alderven** [comment]
Thank you! What about cursor colors?

**Comment by kitao** [comment]
In Pyxel 1.5.0. You can change the cursor freely with `pyxel.cursor` variable like `pyxel.cursor.cls(2)`, `pyxel.cursor.set(0, 0, ["11", 22])'
Pyxel's cursor is the part of the graphics, so if you change the palette color, please take care of the cursor as well.
