### ISSUE TITLE
unknown constant name 'COLOR_DARKGRAY' in 'GetConstantNumber'

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#251]
**Describe the bug**
Getting following error when trying to run exe file compiled from python script:
`pyxel error: unknown constant name 'COLOR_DARKGRAY' in 'GetConstantNumber'`

**To Reproduce**
1. Compile python to exe with [auto-py-to-exe](https://pypi.org/project/auto-py-to-exe/)
2. Run compiled exe

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Python 3.8
 - Pyxel 1.4.1

**Comment by kitao** [comment]
I haven't checked the auto-py-to-exe.
Why don't you use Pyxel Packager to make exe files?

**Comment by alderven** [comment]
Pyxel Packager doesn't have `Console Based` option so I can't see exact error message. Instead it  gives me common error:

![изображение](https://user-images.githubusercontent.com/21060932/83892206-fbb21700-a756-11ea-8ea3-8658aea304d6.png)
