### ISSUE TITLE
Change window icon

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#252]
Pyxel window has fixed icon:

![изображение](https://user-images.githubusercontent.com/21060932/83999885-57a1b900-a96c-11ea-9d5b-a1a615850948.png)

Is it possible to change it somehow?

**Comment by kitao** [comment]
There's only one way to change the icon for now. Make stand-alone file with pyxelpackager and specify your icon as an argument.

**Comment by alderven** [comment]
But this only changes file icon; not icon displayed in pyxel window.

**Comment by kitao** [comment]
Pyxel 1.5.0 has `pyxel.icon` function as an Advanced API.
