### ISSUE TITLE
Pyxel crashes when closing

### ISSUE THREAD

**Issue by Jim-Hawkins** [kitao/pyxel#255]
**Describe the bug**
The app crashes when clicking on the close button or pressing a specified key to close (via pyxel.quit()). The window remanins open and you have to close it from the task manager. Note: the Python Shell does restart despite this issue.
I have experienced this issue in a MSI modern and a HP laptop both bought this year and with similar characteristics.

**To Reproduce**
It happens when you close the app while it is running. 

**Desktop:**
 - OS: Windows Home 10 64-bit
 - Python 3.7
 - Pyxel 1.4.1

I hope you can help me :)

**Comment by kitao** [comment]
I can't reproduce this error with Pyxel 1.4.2 and Python 3.8.5 on Windows 10 64-bit.

**Comment by JoseCr8** [comment]
I have the same problem with Python 3.8.3 and Pyxel 1.4.2 on Windows 10 64-bit. Probably has something to do with the editor I'm using(Anaconda Spyder), older versions worked perfectly. It's not a big issue, the rest works perfectly.

**Comment by kitao** [comment]
Please try Pyxel 1.5.0. You can choose the standalone version.
