### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by Shaylin-TRK** [kitao/pyxel#256]
Pip fails to install on Windows 10 after I have downloaded the file.

I have run the command `pip3 install -U pyxel` from the command prompt, but it always tells me their is no version that satisfies the requirements. I have also tried running the setup file, but it does not work either.

I have Python 3.8 and pip3 installed on my computer.

Is there something I am missing.

**Comment by UngeheurenUngeziefer** [comment]
Try just `pip install pyxel` or give us a screenshot of the error.

**Comment by Shaylin-TRK** [comment]
Here is the file folder on my desktop:

![Untitled 4](https://user-images.githubusercontent.com/66368978/86933809-960fcc80-c100-11ea-9250-49e5f6a80d05.jpg)

Here is my using the code you provided, I don't believe it works because `pip` on my computer refers to Python 2.7 pip:

![Untitled 5](https://user-images.githubusercontent.com/66368978/86933942-bdff3000-c100-11ea-9466-8a505404b7b3.jpg)

And here is the error received when specifing with pip3:

![Untitled 6](https://user-images.githubusercontent.com/66368978/86934041-d96a3b00-c100-11ea-9a17-761984e0c087.jpg)

My only guess is that it is because of internet errors I have had with the computer in the picture, but I shouldn't need internet to install a file I already have, should I?

**Comment by UngeheurenUngeziefer** [comment]
@Shaylin-TRK Maybe there is a problem with 32/64 bit versions? 
Look at this [topic](https://github.com/mavlink/MAVSDK-Python/issues/88)

So internet errors is not cool while you are trying to install something anyway

**Comment by kitao** [comment]
Please try Pyxel 1.5.0.
