### ISSUE TITLE
pyxel.cls(0) is not clearing the screen properly for some resolutions

### ISSUE THREAD

**Issue by KevinVanKiwi** [kitao/pyxel#26]
Some pixels do not get overwriten(/overdrawn) on some resolutions.
```
import pyxel

class MyGame:
    def __init__(self):
        pyxel.init(100,100)
        self.x = 0
        pyxel.run(self.update, self.draw)

    def update(self):
        self.x = (self.x + 1) % pyxel.width

    def draw(self):
        pyxel.cls(0)
        pyxel.rect(self.x,0,self.x+7,7,9)

MyGame()
```
this code leads to this result:
![100x100](https://user-images.githubusercontent.com/41760497/43658073-0e5e68a6-9758-11e8-90cc-0d61b3aca0e2.gif)

but if I change the pyxel.init() to
```
pyxel.init(100,101)
```
the result is fine:
![100x101](https://user-images.githubusercontent.com/41760497/43658121-37cfa880-9758-11e8-81ad-46b1b7288007.gif)

This code shows how the bottom and right border aren't drawn properly
```
import pyxel

class MyGame:
    def __init__(self):
        pyxel.init(100,100)
        self.x = 0
        pyxel.run(self.update, self.draw)

    def update(self):
        self.x = (self.x + 1) % pyxel.width

    def draw(self):
        pyxel.cls(13)
        pyxel.rect(self.x,0,self.x+7,7,9)

MyGame()
```
![pyxel-180803-203905](https://user-images.githubusercontent.com/41760497/43659780-4bf34312-975d-11e8-89f3-95c1345b749f.png)

- Win10,
- Python 3.6.2
- pyxel 0.7.4

**Comment by kitao** [comment]
This bug may be related to #6 because the implementation of `cls` is the same as `rect` command.
@KevinVanKiwi  In your environment, does the example #3 work correctly?

**Comment by kitao** [comment]
@KevinVanKiwi Regarding `cls`, It was reproduced. You don't need to try. I'll fix it!

**Comment by kitao** [comment]
Now I understood the cause. It's the limitation of the point sprite size of OpenGL.
It's limited to 256 and Pyxel uses OpenGL point sprite to draw elements. So any element its size if over 256 is limited to 256. And `cls` is the same implementation as `rect`. So this problem happens.

It isn't easy to remove this limitation on the current implementation.
So please let this limitation as a specification of Pyxel for a while.

**Comment by Vlek** [comment]
Hey @kitao, now that Pyxel has moved to SDL2, does that mean that this could potentially get reopened? The reason I ask is because I'm trying to write some stuff specifically for the GPi case and that thing is 320x240. I can live with 256x240, but it doesn't hurt to ask!

**Comment by kitao** [comment]
Hi,
On SDL2 version of Pyxel, clipping is processed with pure software (not
using OpenGL feature).
So I don't think this issue happen again on the latest version.

2019年7月2日(火) 12:06 Derek McCammond <notifications@github.com>:
