### ISSUE TITLE
Sound audition is played even when editor minimized

### ISSUE THREAD

**Issue by doc1oo** [kitao/pyxel#260]
The Pyxel music editor played a preview on mouse over
the sound number list even when the window is minimized.
(When place the mouse cursor in the same position in the window.)

**Screen capture**
[https://twitter.com/doc1oo/status/1297400538212925440](https://twitter.com/doc1oo/status/1297400538212925440)

**Environment**
Windows 10 1909 / Pyxel 1.4.1 / Python 3.8.5

**Comment by kitao** [comment]
I'm searching for the smart way to pause a SDL2 application includes sounds now.

**Comment by kitao** [comment]
In 1.5.4, everything is paused when the window is inactive.
