### ISSUE TITLE
A question about Python perfomance

### ISSUE THREAD

**Issue by winterwolf** [kitao/pyxel#262]
Hello. At the moment I'm using love2d to write my game which is based on luajit. Luajit is a million times faster than python, so for a long time I could not decide to use your library. But recently I discovered [pypy](https://www.pypy.org), which turns out to be almost as good as luajit in performance. And now I am seriously thinking about switching from love to pyxel! In this connection, I have a question - why do you suggest using python? Don't you think that performance and memory consumption should come first for a game library/engine? I understand that for small pixel games, the performance gain is insignificant, especially since the sdl is responsible for the graphics, but what if the game grows and becomes large? For me personally, the choice of language is very important, because I make an online game and I want the client and server to be in the same language, and for the server, performance is always very important. Thanks :)

**Comment by kitao** [comment]
Hello. I understand the performance difference between Lua and Python.

The reason I have chosen Python is, I'd like to make the game development environment with witch users can start game programming very easily. Python is easy to understand for beginner and also has many users and documents.
And I also expect users extend the Pyxel's functionality with many external modules written in Python.

If you want the higher performance, I recommend to use SDL2 directly and C++. In that case, there is no color and screen size limitation.

**Comment by winterwolf** [comment]
@kitao Sorry, I may have phrased my question poorly.

I've tried running Pyxel games samples both through regular Python (CPython) and PyPy. In both cases, everything works perfect and there is no difference, except PyPy is potentially much faster (usually it is 4-5 times faster, but in some tests it can be 100 times faster).

So my question is, don't you want to change the readme and require pypy3 installation instead of python3 by default?

**Comment by humrochagf** [comment]
I would say for the same propose the language of choice for pyxel was Python. 

To be approachable to beginners, and installing PyPy adds a new layer of complexity to someone that's starting.

And you shouldn't care about performance at the beginning of the project, once you hit performance bottlenecks on your project you can start to tune your code based on your use case, it will be more effective than generic pre-optimization strategies.

Also, Python offers lots of different strategies to improve performance that you can choose as you need:

- Using pypy as you recommended
- Using [numba](https://numba.pydata.org/) jit if your arithmetic computation is the main problem
- Using [cython](https://smirnov-am.github.io/cython/) to speed the parts of the code where you need performance boost
- Using c++ directly as @kitao said to create modules with your most-used routines
- Any other performance optimization of your choice :smile:

**Comment by winterwolf** [comment]
@humrochagf yes, you're right, I shouldn't care about performance at the beginning, but I think, in any case there is no disadvantages in using pypy instead of cpython. Even if pypy will case some additional problems (which is almost impossible because its compatibility is very high), such problems should not be ignored by @kitao. Of course, this is only my vision.
