### ISSUE TITLE
Pyxel should save parameters passed to init() as module parameters.

### ISSUE THREAD

**Issue by fabiommendes** [kitao/pyxel#266]
It is sometimes useful to know which parameters were used to initialize pyxel during the game runtime.  Pyxel already saves width and height as module parameters and maybe could extend this behavior to the other parameters of the init() function such as caption, fps, fullscreen, etc. I would even add an extra attribute dt/time_step/time_delta = 1 / fps to make it easier to integrate with any physics or animation loop.

This is a very simple modification. If you think it is a nice direction to take pyxel, I can send a PR.

**Comment by kitao** [comment]
One of Pyxel's API design policy is keeping APIs simple for beginners.
So Pyxel doesn't support system variables users can easily keep by theirselves.
