### ISSUE TITLE
Basic Pyxel application uses ~250MB of memory

### ISSUE THREAD

**Issue by kfurtak1024** [kitao/pyxel#267]
### Is your feature request related to a problem? Please describe.
The following, basic Pyxel application takes around 250MB of memory (!)

```python
import pyxel

pyxel.init(256, 256, caption="TEST APP")

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)

pyxel.run(update, draw)
```

![memory_usage](https://user-images.githubusercontent.com/51701596/95501478-aa39c300-09a8-11eb-904c-536e9341142e.png)

That's pretty unexpected for such a minimalistic and tiny framework (which by the way is a great idea!) The equivalent in pygame uses less then 20MB.

It looks like the problem is caused by Recorder class. The following code instantiates 900 images with the size of screen (256x256 in my example):

```cpp
  for (int32_t i = 0; i < SCREEN_CAPTURE_COUNT; i++) {
    captured_images_[i] = new Image(width, height);
  }
```

And each image takes around 256KB (256 * 256 * 4 bytes):

```cpp
  data_[0] = new int32_t[width * height]();
```

So, in total it gives us **225MB (!)** (900 * 256KB)

### Describe the solution you'd like

It's pretty neat that Pyxel offers screen capture to GIF out-of-the-box. But to me it's more like a feature for developers, not players.
I'd love to have the possibility to turn off entire screen capture feature programatically during Pyxel initialization.
So, maybe we can have a new flag ```developer_mode``` in ```pyxel.init``` which will turn off recording subsystem:
```python
def init(
    width: int,
    height: int,
    *,
    caption: str = DEFAULT_CAPTION,
    scale: int = DEFAULT_SCALE,
    palette: List[int] = DEFAULT_PALETTE,
    fps: int = DEFAULT_FPS,
    quit_key: int = DEFAULT_QUIT_KEY,
    fullscreen: bool = False,
    developer_mode: bool = False
) -> None:
```

### Describe alternatives you've considered

Tbh I don't see any other **cheap** alternative solutions.

### Additional context
N/A

**Comment by kitao** [comment]
I know Pyxel allocates the buffer for screenshots.
This is the result of considering the balance between user convenience and required performance.

I don't think that using 250MB as buffer is not be problem for modern environments. And rarely used option causes confusion for users and high maintenance cost for developers. 

What kind of environment are you concerning?

**Comment by kfurtak1024** [comment]
I'm targeting my game at low-spec environments (like 1GB of RAM).
In such a scenario 250MB is a lot.

Again, it's a pretty neat feature for developers (that's why I suggested ```developer_mode``` flag) but for end-users it's not a must have. So, why not allow developer to decide whether this feature should be enabled or not in their game?

To avoid confusion, the flag could be defaulted to ```True``` (so GIF capture would be enabled by default, as it is right now)

And last thing, probably it is just a psychology effect, but I'm not feeling great about releasing a retro-styled game created with minimalist framework that requires 250MB of RAM to run. But maybe it's just me 😃

**Comment by cubez** [comment]
> And last thing, probably it is just a psychology effect, but I'm not feeling great about releasing a retro-styled game created with minimalist framework that requires 250MB of RAM to run. But maybe it's just me 😃

It's most certainly not just you. :) I would also very much appreciate being able to turn off extra features that require a large amount of RAM.

**Comment by merwok** [comment]
Maybe the data structure could be revised, if each pixel only needs 4 bits.

**Comment by kitao** [comment]
Now you can specify the length of video by the option of `init`. If you set it to 0, Pyxel doesn't alloc much memory.
