### ISSUE TITLE
Borderless full screen

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#269]
Is it possible to remove borders in full screen mode?

![изображение](https://user-images.githubusercontent.com/21060932/96678454-62d50e80-137a-11eb-8c10-d0e65bc7f38b.png)

**Comment by kitao** [comment]
Pyxel is just using SDL2's fullscreen method.
So if there's some way to do that in SDL2, I can realize that feature.
It would be appreciated if someone let me know about that kind of information.

**Comment by bloodywing** [comment]
@kitao 
https://wiki.libsdl.org/SDL_CreateWindow
Looks like you only have to add SDL_WINDOW_BORDERLESS as additional flag to your fullscreen method.

**Comment by kitao** [comment]
Is it possible to switch to fullscreen without border dynamically?
For your reference, Pyxel's SDL2-handling code is [here](https://github.com/kitao/pyxel/blob/main/lib/engine/src/sdl2.rs).

**Comment by SyedAhkam** [comment]
> Is it possible to switch to fullscreen without border dynamically? For your reference, Pyxel's SDL2-handling code is [here](https://github.com/kitao/pyxel/blob/main/lib/engine/src/sdl2.rs).

I came across this function on the window object: [Window::set_bordered()](https://rust-sdl2.github.io/rust-sdl2/sdl2/video/struct.Window.html#method.set_bordered).

I gave it a try using the below code:

```rs
fn toggle_fullscreen(&mut self) {
        let window = self.sdl_canvas.window_mut();
        if window.fullscreen_state() == SdlFullscreenType::Off {
            window.set_bordered(false);
            let _ = window.set_fullscreen(SdlFullscreenType::Desktop);
        } else {
            window.set_bordered(true);
            let _ = window.set_fullscreen(SdlFullscreenType::Off);
        }
    }
```
However, it made no difference.

**Comment by kitao** [comment]
Sorry, I misunderstood the fullscreen rule of Pyxel.
Pyxel's screen size is always an integral multiple of the screen size. (Same rule as PICO-8)
So the area looks border is margin for that rule.
If this rule doesn't exist, pixel arts are distorted and mouse cursor can't indicate correct pixels.
