### ISSUE TITLE
A function that returns the pressed key

### ISSUE THREAD

**Issue by ashwga** [kitao/pyxel#271]
A function that returns the pressed key(s).
It would be easier to implement "input boxes" and not using multiple if elif statements to determine what key was pressed.

**Comment by bloodywing** [comment]
I'm looking for a way to archive that as well. Checking all KEY_ that pyxel has was an idea that I had as well. But it looks incredible ugly.
My plan is to make it possible for the user to reassign their inputs for my game.

Put this in a .update function:
```python
for k in pyxel.__dict__.keys():
    if k.startswith('KEY_'):
        if pyxel.btnp(getattr(pyxel, k)):
            print(k)
```

**Comment by nwilliams770** [comment]
@ashwga @bloodywing To clarify, it sounds like you are unhappy with `btn(key)` because you have to query for all _n_ keys you care about, right?

Instead, you're looking for something more like:

```
btns()
Returns a list of all buttons pressed during this frame

btnsp([hold], [period])
Returns a list of all buttons pressed for this frame. When hold and period are specified, only returned the keys at the period frame interval when the key is held down for more than hold frames
```

Does this sound right? If so, I'll give it a shot!

**Comment by bloodywing** [comment]
@nwilliams770 yes, pretty much. Use case is an options menu where I let the users set their own keys for the controls.

**Comment by kitao** [comment]
In 1.5.0, there are `pyxel.input_keys` and `pyxel.input_text` variables.

**Comment by danjane** [comment]
Neither pyxel.input_keys nor pyxel.input_text appear to work in version 2.1.10. pyxel.input_keys has been removed, and pyxel.input_text is always an empy string. Is there another simple way to get a list of the keys pressed in the last frame?
