### ISSUE TITLE
PyDoc ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by winterwolf** [kitao/pyxel#277]
Create file "test.py" with this content:

```python
import pyxel
pyxel.init(160, 120)
```

Then run `pydoc -b` from the same directory.

Now navigate to your **test** module and get the error:

> ErrorDuringImport: problem in test - ValueError: signal only works in main thread or with __pypy__.thread.enable_signals()

I'm new in python so sorry if my issue is noobish, but I have no idea how to provide documentation to my app due to this error.

**Comment by bloodywing** [comment]
put `pyxel.init` in a function or behind a `if __name__ == '__main__'` so it won't call pyxel.init during importing a module

```python
import pyxel


def main():
    pyxel.init(160, 120)
    # ... more pyxel calls here, pyxel.run(...) etc.


if __name__ == '__main__':
    main()
```

**Comment by winterwolf** [comment]
@bloodywing thank you!

**Comment by winterwolf** [comment]
@bloodywing your solution works well in procedure-style code but I still don't understand how to fix files written in object oriented style (classes), for example [this hello world](https://github.com/kitao/pyxel/blob/master/pyxel/examples/01_hello_pyxel.py).

**Comment by bloodywing** [comment]
This would work:
```python
import pyxel


class App:
    def __init__(self):
        pyxel.init(160, 120, caption="Hello Pyxel")
        pyxel.image(0).load(0, 0, "assets/pyxel_logo_38x16.png")
        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

    def draw(self):
        pyxel.cls(0)
        pyxel.text(55, 41, "Hello, Pyxel!", pyxel.frame_count % 16)
        pyxel.blt(61, 66, 0, 0, 0, 38, 16)

if __name__ == '__main__':
    App()
```
this prevents creating the object during import too. Usually people don't import  example scripts and simply run them. An exception is things like pydoc, which will scan every directory in a module. It also looks like this behavior changed over time in python:https://bugs.python.org/issue38904

**Comment by winterwolf** [comment]
@bloodywing thank you so much! ❤️
