### ISSUE TITLE
`SEGFAULT` when running `04_sound_api.py` or `05_color_palette.py`

### ISSUE THREAD

**Issue by marespiaut** [kitao/pyxel#28]
Hello,

My setup is:
* Arch Linux
* Python 3.6.6
* Pyxel 0.7.6

When launching the `04_sound_api.py` or `05_color_palette.py` examples, I get a segmentation fault a few seconds after.

Is there a way to properly backtrack segfaulting code in Python?

**Comment by kitao** [comment]
@marespiaut Are example #1-3 OK?

**Comment by marespiaut** [comment]
@kitao Yes, the.other exemples are working fine.

**Comment by kitao** [comment]
@marespiaut 
Can you trace the code with this method?
https://stackoverflow.com/questions/2663841/python-tracing-a-segmentation-fault

**Comment by marespiaut** [comment]
Python got updated on my system and I cannot manage to reproduce this bug with Python 3.7.0 and Pyxel 0.7.8.
