### ISSUE TITLE
Gamepad not working in Linux

### ISSUE THREAD

**Issue by CaffeinatedTech** [kitao/pyxel#281]
**Describe the bug**
Checking for Gamepad inputs using `pyxel.btn(pyxel.GAMEPAD_1_LEFT)` for example does not return true on Linux.  Have tried both a Xbox One and a PS4 controller connected via USB.  Confirmed working in OS.

**To Reproduce**
1. Be running Linux
2. Check inputs on GAMEPAD_1 or GAMEPAD_2
3. Do something to indicate buttons were pressed

**Expected behavior**
`btn` expected to return true when `[key]` is `GAMEPAD_1_LEFT` for example.

**Desktop (please complete the following information):**
 - OS: Linux - Manjaro, Kernel 5.9.3-1, Cinnamon 4.6.7
- Python 3.8.6
- Pyxel 1.4.3

**Additional context**
Tried both `GAMEPAD_1` and `GAMEPAD_2`.  Building and running both from PyCharm and from stand-alone executable

**Comment by bloodywing** [comment]
Have you tested jstest-sdl? https://github.com/meleu/jstest-sdl most likely sdl2 isn't detecting your gamepad.
Some gamepads were broken with the recent sdl2 on arch: https://bugs.archlinux.org/task/67174

**Comment by CaffeinatedTech** [comment]
Yeah it seems to be working in jstest-sdl

![controller-jstest](https://user-images.githubusercontent.com/27036556/100849997-e54f0300-34ce-11eb-943a-b59a8d431878.png)

**Comment by kitao** [comment]
Please try it on 1.5.0. The core engine and way of using SDL2 is re-implemented.
