### ISSUE TITLE
Cursor lag on OSX

### ISSUE THREAD

**Issue by desmondw** [kitao/pyxel#282]
**Describe the bug**
I'm experiencing cursor lag when clicking, but only on OSX. When clicking, the cursor will not render updates for 200-700ms. I'm not sure if this is just draws or if it affects input as well. It noticeably delays the cursor from updating even outside of the pyxel window.

![click_issue](https://user-images.githubusercontent.com/1052705/101211821-9dde8900-362c-11eb-8116-94e504ee1df8.gif)

**To Reproduce**
1. Using a mac, open the example file `06_click_game.py`
2. Move mouse around and note no lag
3. Click while moving the mouse around an notice a delay in draw updates

**Expected behavior**
There should be no delays in rendering or input of cursor on OSX.

**Desktop:**
 - OS: OSX Catalina 10.15.7
-  Computer: MacBook Pro (15", 2017)
 - Version 1.4.3

**Comment by desmondw** [comment]
I was able to track this down to `SDL_GetMouseState` not providing updated coordinates immediately following a click. It's still unclear why.

The actual SDL cursor being rendered has always been unaffected though, so one solution would be to replace the image bank rendered cursor with the SDL cursor styled in the same way (set on [SDL_CreateCursor](https://wiki.libsdl.org/SDL_CreateCursor)). This would also make the cursor more responsive with general movement for all OSes by unlocking it from the scaled grid (currently at default scale 4, the cursor jumps between the scaled pixels).

**Comment by kitao** [comment]
Could try Pyxel 1.5.0?
