### ISSUE TITLE
Black cursor dot visible on alternate palettes

### ISSUE THREAD

**Issue by desmondw** [kitao/pyxel#284]
**Describe the bug**
Whenever `pyxel.mouse(True)` is enabled, a small black pixel is drawn exactly at the cursor location. This remains an actual single pixel even with window scale. This is usually not noticed, because with the default color palette the black outline of the cursor covers it up. However, if using an alternate palette without black then this issue will be visible.

![cursor_dot](https://user-images.githubusercontent.com/1052705/101229540-91225b00-3655-11eb-8924-0d8c606fec8d.gif)

**To Reproduce**
1. Change the entire palette color to white on init: `palette = [0xffffff] * 16`
2. Set `pyxel.mouse(True)`
3. Run and note a single black pixel being displayed at cursor location 
4. Set `pyxel.mouse(False)`
5. Notice no black pixel at cursor location

**Desktop (please complete the following information):**
This was noticed on both a mac and PC

**Comment by WarpedWartWars** [comment]
(very late here)

I see this in [a replit repl](https://replit.com/@WarpedWartWars/Pyxel-test?v=1) I made.

I'm on Windows 10.

I also see it when the mouse hasn't been set to visible.

**Comment by kitao** [comment]
Please try Pyxel 1.5.0. Mouse cursor drawing code is re-implemented.
