### ISSUE TITLE
Pyxel install fails on Raspberry Pi 4

### ISSUE THREAD

**Issue by bifft2** [kitao/pyxel#286]
I am trying to install pyxel on my Raspberry Pi. I first installed all the packages pyxel is dependent on. Then I executed the following commands, as the README specifies:

```
git clone https://github.com/kitao/pyxel.git
cd pyxel
make -C pyxel/core clean all
pip3 install .
```

Everything runs without issue until the` pip3 install .` command. I have also tried `pip3 install --no-cache-dir . `

With either, I get the following traceback:

pi@raspberrypi:~/pyxel $ pip3 install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/pyxel
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-togbwxhy/setup.py", line 2, in <module>
        from pyxel import VERSION
      File "/tmp/pip-req-build-togbwxhy/pyxel/__init__.py", line 10, in <module>
        from . import core  # type: ignore
      File "/tmp/pip-req-build-togbwxhy/pyxel/core/__init__.py", line 42, in <module>
        _lib = _load_library()
      File "/tmp/pip-req-build-togbwxhy/pyxel/core/__init__.py", line 39, in _load_library
        return cdll.LoadLibrary(lib_path)
      File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /tmp/pip-req-build-togbwxhy/pyxel/core/bin/linux/libpyxelcore.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv
   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-togbwxhy/

Any help in understanding what's going wrong would be much appreciated!

**Comment by bloodywing** [comment]
From what I've found out. The gcc version on raspberry pi os is too old. It's gcc 8 but you need at least gcc 9 to compile the extension.

**Comment by bifft2** [comment]
Thank you for this! I have downloaded gcc 9. Do you know how to specify for it to compile with the new version?

**Comment by bifft2** [comment]
I figured it out! I just changed the second line in the below to specify version 9.1:

```
ifeq ($(PF),linux)
CC = g++-9.1
```

Thanks again for your help!!
