### ISSUE TITLE
pyinstaller executable unable to load .pyxres file

### ISSUE THREAD

**Issue by desmondw** [kitao/pyxel#287]
**Describe the bug**
After getting the pyinstaller building my package I found out that it wouldn't include my `.pyxres` file, even if it was in the same directory. The file only had a few sounds in it.

Output from the terminal:
```
Last login: Thu Dec 10 17:38:29 on ttys006
/Users/desmondweindorf/www/operator/src/dist/app ; exit;
➜  ~ /Users/desmondweindorf/www/operator/src/dist/app ; exit;
pyxel error: cannot open file '/var/folders/dg/_z71_dwd32d46yybz1262cv40000gn/T/_MEIEwYGB8/sounds.pyxres' in 'LoadAsset'

[Process completed]
```

Commenting out the line where I load in the resource file makes everything work fine in the executable. Building on OSX.

**Comment by kitao** [comment]
Have you put your data in assets folder?
pyxelpackager command recognizes only files in the "assets" folder as mentioned in the README.

**Comment by desmondw** [comment]
I initially had them in an assets folder outside of the src folder, so I may have had that one folder too high. Let me double check

**Comment by desmondw** [comment]
That did it. The assets folder must be in the same directory as the main file. I was running it in the directory above like so: `pyxelpackager src/app.py`
