### ISSUE TITLE
pyxeleditor command not working.

### ISSUE THREAD

**Issue by EvokerKing** [kitao/pyxel#290]
**Describe the bug**
I can use pyxeleditor by going into `C:\Python39\Lib\site-packages\pyxel\editor` and running `py __init__.py` but I can't actually use my own files for this. The way that you are supposed to is by running `pyxeleditor [file]`. But this just says 
![image](https://user-images.githubusercontent.com/69367929/102215039-2370fd00-3ea7-11eb-9e77-0ce391bee61d.png)

**To Reproduce**
1. Run pyxeleditor on your files using `pyxeleditor`.
2. Observe

**Expected behavior**
It should run pyxeleditor.

**Screenshots**
Returns an error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: I have no clue what to put here
 - Version: Latest

**Additional context**
Did the PATH variables get set right?

**Comment by EvokerKing** [comment]
Hello. I have been waiting for 3 days. Can someone please help me out.

**Comment by doc1oo** [comment]
It just looks like the system environment variable "`Path`" is not set.
I think it will be fixed if you set it manually.
`C:\Program Files\Python39\Scripts\`

Although it is a Japanese version, it is a screenshot.
![image](https://user-images.githubusercontent.com/99213/102686944-9921f380-422e-11eb-8d26-6c258dee188f.png)

**Comment by EvokerKing** [comment]
That was already a PATH variable. However I found out that it didn't create `install_pyxel_examples.exe` or `pyxeleditor.exe`. Apparently I didn't have CMD opened as administrator when running `pip install -U pyxel`.
