### ISSUE TITLE
sound.set_note(note) API causes error

### ISSUE THREAD

**Issue by doc1oo** [kitao/pyxel#292]
**Describe the bug**
I got an error when I try to use the Sound.set_note(note) API.
(Also set_tone(), set_volume(), set_effect() are same result.)

The error message is 
```
Traceback (most recent call last):
  File "test_core2.py", line 6, in <module>
    s.set_note("c2")
  File "C:\Program Files\Python38\lib\site-packages\pyxel\__init__.py", line 391, in set_note
    core.sound_set_note(note.encode("utf-8"))
TypeError: this function takes at least 2 arguments (1 given)

```

**To Reproduce**
1. run below script 
```
import pyxel

pyxel.init(100,100)
pyxel.sound(0).set_note("c2")
```

2. See error in console

**Expected behavior**
I found Sound class is defined class in` __init__.py`.
And I thought that there function were not enough arguments, so I added them and it seemed to work. 
(I don't know if it's correct.)

source code
```
    def set_note(self, note: str) -> None:
        core.sound_set_note(note.encode("utf-8"))
```
fixed code
```
    def set_note(self, note: str) -> None:
        core.sound_set_note(self._c_obj, note.encode("utf-8"))
```

**Desktop:**
 - OS: Windows10 20H2
 - Pyxel 1.4.3
 - Python 3.8.5

**Comment by kitao** [comment]
Core engine and Python wrapper are re-implemented in 1.5.0. Please try it on 1.5.0 again.
