### ISSUE TITLE
I want to set the playback position of the music

### ISSUE THREAD

**Issue by doc1oo** [kitao/pyxel#293]
**Is your feature request related to a problem? Please describe.**
I'm currently making a composition tool with Pyxel. So I noticed that the playback position of the music can be obtained by API, but the playback position cannot be set.
It's inefficient because the user playing the song from the beginning every time when preview of music. I think this problem is the same when writing songs with the official pyxel editor.

Even now, it's possible for Pyxel users to generate and play their own dedicated music each time to specify the playback start position, but the loop of the song complicates the problem.
Even if you start playing from the middle of the song, you may want to return to the beginning of the song when the song is over.
In that case, you have to make music that is packed with sounds endlessly without using loops. But it's not elegant.

**Describe the solution you'd like**
I'd be happy if I could specify playing position of the music :) (In units of sound and notes(tick))
Ex.)
- set_play_pos(ch, pos)
- playm(msc, loop=False, play_pos=0)

**Comment by kitao** [comment]
I added `tick` option to the `play` and `playm` functions in Pyxel 1.6.6.
Now you can specify playback position.
If the speed of the sound is 30, `tick=30` means one note.

**Comment by kitao** [comment]
You can also playback partially in the sound and music editors with `SHIFT`+`SPACE`.

**Comment by doc1oo** [comment]
Thank you very much for the music enhancement!
