### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by serpent7776** [kitao/pyxel#296]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add support for FreeBSD? Pyxel comes with prebuilt libraries and is missing library for FreeBSD. Therefore I cannot run pyxel games on FreeBSD.

**Describe the solution you'd like**
Include prebuilt library for FreeBSD.

**Describe alternatives you've considered**
I don't believe there is, except for running the game on linux instead.

**Additional context**
N/A

**Comment by kitao** [comment]
Please try self-building according to README in Pyxel 1.5.0.

**Comment by serpent7776** [comment]
I did self-build on FreeBSD with changes in my fork https://github.com/serpent7776/pyxel/tree/freebsd-support.
All examples seem to work, but no sound in generated. I can submit PR if you like, but I didn't test whether this doesn't break something for other platforms.
