### ISSUE TITLE
"The specified module could not be found"

### ISSUE THREAD

**Issue by Sir-Quack-III** [kitao/pyxel#297]
I recently decided to start using pyxel, and I did all of the steps in the read me file. I entered in cmd `pip install pyxel`, and loaded up one of the examples programs.

But it gave me this error:
`OSError: [WinError 126] The specified module could not be found`

It gave me code in the module that it was referencing, and I tried installing anything that looked odd, but nothing there existed. I tried looking this problem up everywhere, but I couldn't find anything close to my problem.

Can someone please help?
Thanks in advance!

**Comment by merwok** [comment]
You maybe have multiple installations of python on your machine.
The command `pip debug` will show you which python is associated with it, and you can check if that’s the same you’re running.

**Comment by kitao** [comment]
Please try 1.5.0. It provides stand-alone version.
