### ISSUE TITLE
Fix docs on PyPI

### ISSUE THREAD

**Issue by MichaelCurrin** [kitao/pyxel#298]
**Describe the bug**
The PyPI package page has broken links and images.

**To Reproduce**

Go to https://pypi.org/project/pyxel/ - see images are missing.
Click on English and see README.md gives a not found error.

I don't know if this ever worked or how much work it would be fix, but it would give a more polished image and first impression of the package especially for newcomers who find it on PyPI before GitHub.

**Screenshots**
![Screen Shot 2021-03-05 at 1 33 17 pm](https://user-images.githubusercontent.com/18750745/110110455-8479e400-7db7-11eb-98bc-81f372be7e82.png)

**Comment by kitao** [comment]
Thank you for reporting.
It seems that it happened because the links in the READMEs changed to relative.
As the result of that, the description for PyPI can't refer to links.
I'll fix the links of the READMEs or add some auto link completion script for PyPI.

**Comment by kitao** [comment]
In 1.5.0, README.md's relative link is replaced to absolute link automatically for PyPI.
