### ISSUE TITLE
MacBook M1 pyxel not working

### ISSUE THREAD

**Issue by qelpasa** [kitao/pyxel#299]
I'm trying to turn on my project I've beed doing on my windows pc on my new MacBook Pro with m1 chip. I've installed anaconda, pip and python. I imported project with git. Using Pycharm I'm trying to run my project, but all I get is bunch of errors: Thank in advance!

/Users/mario/PycharmProjects/beast/venv/bin/python /Users/mario/PycharmProjects/beast/main.py Traceback (most recent call last): File "/Users/mario/PycharmProjects/beast/main.py", line 1, in import pyxel File "/Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/init.py", line 10, in from . import core # type: ignore File "/Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/core/init.py", line 42, in _lib = _load_library() File "/Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/core/init.py", line 39, in _load_library return cdll.LoadLibrary(lib_path) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/init.py", line 452, in LoadLibrary return self._dlltype(name) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/init.py", line 374, in init self._handle = _dlopen(self._name, mode) OSError: dlopen(/Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): no suitable image found. Did find: /Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib: mach-o, but wrong architecture /Users/mario/PycharmProjects/beast/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib: mach-o, but wrong architecture

Process finished with exit code 1

**Comment by kitao** [comment]
Please try Pyxel 1.5.0. It works on M1 Mac.
