### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stsewd** [kitao/pyxel#30]
Good work! Love this project already :)

I notice that you have the docs on the readme only, I think you can use sphinx, that way you can put docstrings in your python files and then put all together with sphinx. Then host the docs on read the docs, you can host translations too! Let me know if you want this, I can help with sphinx and read the docs.

**Comment by kitao** [comment]
Thank you for the information! It looks very useful.
Since Pyxel has not so much documentation yet, I first tried creating a wiki (https://github.com/kitao/pyxel/wiki). I will think about introducing Sphinx when the number of documents increases in the future.
