### ISSUE TITLE
I can't install on windows 7 SP1

### ISSUE THREAD

**Issue by Lufims** [kitao/pyxel#305]
When i click on the install file, appear that:
![Screenshot_1](https://user-images.githubusercontent.com/73536178/115976886-cec24a80-a548-11eb-95fe-de7d2bb1f680.png)

And i don't know if this have something to do, but, When try to run the code "pip install -U pyxel", appear this:
![Screenshot_2](https://user-images.githubusercontent.com/73536178/115976940-442e1b00-a549-11eb-8cc3-1aeebc5b965b.png)

Can someone help?

**Comment by Lufims** [comment]
I tried to make something, and i make the long_description a string:
![Screenshot_1](https://user-images.githubusercontent.com/73536178/116000007-d3c4df80-a5c4-11eb-97af-3aed148b4151.png)

And now appear this:
![Screenshot_2](https://user-images.githubusercontent.com/73536178/116000022-e808dc80-a5c4-11eb-9674-ea67fe3067e9.png)

**Comment by kitao** [comment]
Please try it on 1.5.0 again. The core engined is re-implemented in Rust.
