### ISSUE TITLE
Pyxel2 (in Rust)

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#306]
Hello, Pyxel users!

It's taking longer than expected, but Pyxel 2 is starting to work. The core engine is eventually implemented in Rust.

There will be no screen size restrictions and it will work without Python installed.

<img width="636" alt="スクリーンショット 2021-05-23 17 33 38" src="https://user-images.githubusercontent.com/678802/119253942-7d13eb00-bbee-11eb-9e62-c6795aaf7565.png">

**Comment by merwok** [comment]
Will you keep python for game code, or switch to say lua?  or require people to use rust?

**Comment by YifangSun** [comment]
I notice that you rewrite pyxel in Rust. Will the pyxel1 and pyxel2 be supported parallelly in the future? Or pyxel1 is deprecated? @kitao

**Comment by kitao** [comment]
Pyxel1 will be deprecated. But all of the futures includes Python support
will be kept.
And there are many big features now I’m planning for 2, but implementing
all features at the same time is very tough. So I’ll release the first rust
version of Pyxel supports current features + alpha as Pyxel 1.5. After that
add new big features step by step.

2021年10月5日(火) 11:56 孙逸方 ***@***.***>:
