### ISSUE TITLE
Support custom palette in editor and resource files

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#315]
**Is your feature request related to a problem? Please describe.**
We can run a pyxel game with a custom palette, but we can’t use it in the editor.

**Describe the solution you'd like**
Idea 1: add a command-line parameter to the editor like `--palette 1a1c2c,5d275d,b13e53,ef7d57`
This could be a little unconvenient to use though.

Idea 2: add a param like `--palette path/to/file` that reads the palette from a file.  Could use a text file format (lospec for example has multiple text formats for each palette) for easy parsing, or a PNG file with 1px per colour but that would require PIL or pypng to analyse.  I have a clone of the repo and added this option for my own usage, so I can send a PR.

Idea 3: update resource file format to store palette in the resource file.  Load automatically when opening a resource file with a custom palette.  To save a custom palette, either keep it a secret feature (people have to add palette file to the zip) or add a palette tool in editor.  I probably can’t make a PR for this, and you’re doing the rust rewrite so probably better to wait for that.

**Describe alternatives you've considered**
See above

**Additional context**

**Comment by kitao** [comment]
My current plan is to add the dedicated custom palette file (.pyxpal?) which is loaded automatically when the .pyxres file ins the same directory is loaded.

**Comment by merwok** [comment]
That sounds good; a pyxapp file would include code assets and palette I suppose?

**Comment by merwok** [comment]
pyxapp should be fine because the packaging code does a recursive glob in the game directory, so pyxpal will be included just like pyxres.

**Comment by notbored** [comment]
I think it would be better to bundle it in the `.pyxres` file rather than have an additional file just for a palette.

Maybe include a palette editor in the sprite editor like [TIC-80](tic80.com). Allowing you to edit each colour individually as well as copy/paste palette into the editor.

**Comment by kitao** [comment]
The matter to be decided first is how to handle colors in the editor.
Pyxel and its editor are designed for fixed 16 colors because it focuses on the retro game spec and programming learners. And palette modification is for users who can handle advanced coding and 3rd party design tool. (Kinds of bonus function for advanced users)
If the editor allow the palette change, UI colors are also changed and users can't use it correctly.
How to handle palette data depends on how to handle that.

**Comment by merwok** [comment]
Changing the editor colours is a real issue.
For my usage, I have been carefully choosing 16 colours in an order that matches the original colours, so that the editors stay usable.  A person on discord sent me a script to automate that sorting, which gives good results.

**Comment by notbored** [comment]
Okay so here is my proposal:

1) Editor UI colours stay fixed regardless of game palette.
- if you want user to have the ability to change the colour of the editor then that can be an extra feature(not bothered personally)

2) Changing the game palette can be done:
  - dragging a png/gif containing the desired 16 colours onto the palette widget in the editor
  - with the CLI option `-p / --palette` which either takes a string of comma separated hex values or a path to a text file containing the same.
  - editing the `palette` file in `.pyxres` container directly (Palette state is kept in `.pyxres` files along with the other resources associated with the project.)

**Comment by matteoturini** [comment]
@kitao I believe this is an essential feature for colorblind people like me, and 8% of people around the world, to be able to distinguish colors. I am currently spending 15% of the time drawing art to find out which color is which, something that could easily be resolved with more vibrant colors.

**Comment by kitao** [comment]
I understand your situation and I think accessibility is important in game development as well.
But the current point is not the reason, it is how to keep Pyxel resource editor's visibility.
The editor is made as an ordinal Pyxel application. So the number of colors for both user image and tool is limited to 16.
If user changes the palette, it brakes tool's visibility and deteriorates the usability of the tool.

One of solutions I'm thinking now is to allow Pyxel use 32 colors include the original system palette and also user defined palette. But it requires many design changes such as how to keep screen image format, how to handle drawing functions, and so on. There may be more sophisticated ways to change the design for this feature.
That's the reason why I'm taking the time to consider.

By the way, if you would like to change the palette in the editor only for you. It is very easy. Just insert some palette change code in the Python code of the tool. The difficulty of implementation depends on whether the specifications are unified for everyone or the response of a specific situation.

**Comment by merwok** [comment]
On discord, someone gave me a script to reorder a palette so that the colours match the order of the original palette.  This keeps the editor itself usable!

Your idea to support 32 colours is probably the best one, but as you said it would require many changes.

**Comment by kitao** [comment]
I don’t think so. It depends on user’s color selection. The important thing
is to make a clear distinction between temporary approach and permanent
approach.

If it can be temporary one. Change palette color in the editor code is the
easiest one, I think.

2022年5月8日(日) 19:30 Éric ***@***.***>:

**Comment by matteoturini** [comment]
> palette change code

Wait, can you change the palette?

**Comment by merwok** [comment]
Yes, the pyxel editor is a normal pyxel app, so you can use all functions including `pyxel.colors.from_list`: https://github.com/kitao/pyxel/pull/368/files#diff-a90bc88882f91fe7650d31a51a7b807af522f5f94316d4f0979988c573596ad5R45
