### ISSUE TITLE
Window is blank when running pyxel on WSL 2

### ISSUE THREAD

**Issue by trbedwards** [kitao/pyxel#316]
**Describe the bug**
The window produced by pyxel is blank (doesn't show anything). To be more precise, it does show something for a split second, but then immediately goes white (see screenshot).

**To Reproduce**
- Run an X-server on windows (in this case [VcXsrv](https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3))
- Open WSL terminal
- Install pyxel examples, if you haven't already
- `python 01_hello_pyxel.py`

**Screenshots**
![hello_pyxel](https://user-images.githubusercontent.com/1222553/131229761-6b79a0d6-619e-444f-83db-7726710c4160.PNG)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04 on WSL 2 (Windows 10 host)
- Python 3.9.6
- pyxel 1.4.3

**Comment by kitao** [comment]
Please try on 1.5.0 again. Because the core engine is re-implemented in Rust.
