### ISSUE TITLE
Add camera function

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#323]
A `camera` function is convenient to draw things relative to some origin coordinates.

It should take `x, y` params and make the graphics function calls that follow (blt, pset, line, etc.) add these offets to they coordinates.  A call without parameters resets the camera.

Example in pico-8: https://www.lexaloffle.com/dl/docs/pico-8_manual.html#CAMERA (not much info there but it’s used very often in games).

Thanks!

**Comment by kitao** [comment]
Hi,
I agree with that. I’ll add camera function in the next version. Thank you.

2021年10月12日(火) 8:37 Éric Araujo ***@***.***>:

**Comment by kitao** [comment]
I implemented the camera function as a test.
Then I found its specification is more difficult for users than I expected.
`load` and `set` function should be affected or not.
`clip` should be affected or not. What should happen when self-copying with `blt`. 

It seems difficult to officially implement it until I clarify its spec and confirm that users will not be confused.

**Comment by merwok** [comment]
Added for 1.5.2 \o/

**Comment by kitao** [comment]
Yes, supported in 1.5.2.
