### ISSUE TITLE
Can't import pyxel. Traceback (most recent call last)

### ISSUE THREAD

**Issue by Capelnyk** [kitao/pyxel#324]
**Describe the bug**
I cannot run any program written in Pyxel. 
I'm using Windows 10, Python 3.10.0rc2
The console returns me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\edu\AppData\Roaming\Python\Python310-32\site-packages\pyxel\__init__.py", line 6, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (C:\Program Files\lib\collections\__init__.py)
```
**To Reproduce**
import pyxel

**Expected behavior**
Run my program.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.10.0rc2

**Comment by kitao** [comment]
Please try Pyxel 1.5.0.
