### ISSUE TITLE
Add `mget(img, x, y)` function to get map sprite at coordinates

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#325]
**Is your feature request related to a problem? Please describe.**
Easy way to know what sprite is at certain map coordinates, for collisions and other needs.

**Describe the solution you'd like**
Basically expose the `get_tilemap` function from 10_platformer example in the pyxel namespace.

The name `mget` comes from pico8 (meaning _map (tile) get_), it could be `tget` if you prefer _tile get_ or `tmget` or something else.  I only care that function names are internally consistent 🙂 (which makes me suggest that the `pget` method in tilemap is misnamed!)

The doc will have to make clear that `img, x, y` are tilemap parameter, not screen coordinates — this tripped me up for some time when I started pico8.  But everyone learns that, or it’s not a problem if you blit the map at 0,0 and use `camera` for scrolling.

**Describe alternatives you've considered**
Copying the `get_tilemap` function forever in all my projects 🙂 

**Additional context**
Would also be great to have `mset(img, x, y, tile)` for changing the tilemap in memory during the game.

(Then the next step is to add sprite flags!  These are a neat way to give more power to artists doing sprites and maps, without having the developer hard-code lists of tiles in collision etc. code.)

**Comment by kitao** [comment]
In Pyxel 1.5.0. Pyxel's tile became a tuple of (x in tile, y in tile).
And though they are part of "Hidden Advanced API", tilemap's methods became the same as Graphics and Image class like `tilemap.cls(3)` and `tilemap.rect(0, 0, 4, 4, 8)` because users can remember methods easily.
Please understand the purpose of Pyxel is not the PICO-8 clone.

**Comment by merwok** [comment]
Alright!  (I was naming pico-8 to give a reference, and because pyxel’s readme mentions it — wasn’t suggesting that pyxel should copy all of it)
