### ISSUE TITLE
Resize sprites to desired size.

### ISSUE THREAD

**Issue by 20AbhishekRoka02** [kitao/pyxel#326]
**Is your feature request related to a problem? Please describe.**
I don't like pyxel for one reason and that is we can't resize our sprite i.e. if I draw something in 8x8 it remains that small, and I can't increase its size from any pyxel function.

**Describe the solution you'd like**
Please create a function to allow sprite resizability.

**Comment by kitao** [comment]
This is because Pyxel respects 8-bit game consoles which don't support scaling and rotation.
But I know some users made their own function which can scale and rotate.

https://twitter.com/Ontake441/status/1457168245148897284?s=20
