### ISSUE TITLE
transparent sprite background

### ISSUE THREAD

**Issue by 20AbhishekRoka02** [kitao/pyxel#327]
**Is your feature request related to a problem? Please describe.**
when I used my background color other than black, I found my sprite in a box where its background is black and that is really annoying, I want a transparent background feature,

**Describe the solution you'd like**
In img() function, add a new keyword to the transparent background where 1 describe True for a transparent background and 0 describe False, and describe background as black

Thank You!

**Comment by merwok** [comment]
Could you share the code you’re using (the line where you call `pyxel.blt`) and a screenshot of the result?

I have no problem with light grey as background colour for example, as long as I pass `11` as the last argument to `blt`.

**Comment by 20AbhishekRoka02** [comment]
[image: sprite + code.PNG]
See this is my code + sprite on the screen.

**Comment by 20AbhishekRoka02** [comment]
![sprite + code](https://user-images.githubusercontent.com/75659036/142765503-73327dd0-e58a-407f-b6db-d68974f7632c.PNG)

**Comment by merwok** [comment]
You define colour 12 to be transparent, but black is 0.

**Comment by 20AbhishekRoka02** [comment]
Cool, thanks!
