### ISSUE TITLE
Create tutorials

### ISSUE THREAD

**Issue by 20AbhishekRoka02** [kitao/pyxel#328]
**Is your feature request related to a problem? Please describe.**
I want kitao/pyxel tutorials so, we can use its features more easily.

**Describe the solution you'd like**
create step-by-step game creation video or web articles in English and only in English (as it is a universal language).

Games like: contra classic level 1 only, super Mario bros level 1, or any level.

But, don't create games like snake and apple, ping pong etc. they are quit basic and the background never changes.

I like your jump man game as its background is changing but, still, I want more.

Thank You!

**Comment by kitao** [comment]
I can't do that because I'm full of Pyxel upgrades, but it seems that there are people who are making video content and tutorials, so please search.
