### ISSUE TITLE
Ability to change cursor image

### ISSUE THREAD

**Issue by WarpedWartWars** [kitao/pyxel#329]
Pretty much the title.

It used to be possible by editing `pyxel.constants.MOUSE_CURSOR_DATA`, but that's no longer possible:
https://github.com/kitao/pyxel/commit/633a8185d16122a37dca371cff93c7eef874b8e7#diff-c63ca80a88391b3bd30b8f153bdca69907aa28eb7c8df8ffef54b5e639d6ed42L56-L65

**Comment by WarpedWartWars** [comment]
I realized it was moved here:
https://github.com/kitao/pyxel/commit/633a8185d16122a37dca371cff93c7eef874b8e7#diff-562bbd903199b2c1f377985d3601ca7093dc651cb27b858188755b1f392d1fe4R24-R28

I wonder how to get that from within Python.

**Comment by kitao** [comment]
In 1.5.0, you can modify the mouse cursor image with `pyxel.cursor` image.

**Comment by merwok** [comment]
It’s not documented in the README

**Comment by WarpedWartWars** [comment]
> In 1.5.0, you can modify the mouse cursor image with `pyxel.cursor` image.

Do I just set that to the tuple of strings of numbers like I did with `pyxel.constants.MOUSE_CURSOR_DATA`?

**Comment by WarpedWartWars** [comment]
Unfortunately, I can't seem to use pyxel:
```
Traceback (most recent call last):
  ...
  File "/[python3path]/lib/python3.8/site-packages/pyxel/__init__.py", line 10, in <module>
    from .lib.linux.pyxel_wrapper import *  # type: ignore  # noqa F403
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /[python3path]/lib/python3.8/site-packages/pyxel/lib/linux/pyxel_wrapper.so)
```

**Comment by kitao** [comment]
Actually Pyxel 1.5.0 can handle many Image Banks.
And now pyxel.cursor is also an image bank.

So, you can call the following functions to edit image:

pyxel.cursor.pset(10, 10, 3)
pyxel.cursor.cls(0)
pyxel.cursor.set(0, 0, [“fff”, “fff”, “fff”])

**Comment by kitao** [comment]
Have you tried the self-building written in README?

**Comment by WarpedWartWars** [comment]
1. I found out.
2. I'm using it on replit.com.
2.1. README seems to just say to install it with pip.
