### ISSUE TITLE
Problem with usage of pyxel.blt(..., colkey) in 1.5.0

### ISSUE THREAD

**Issue by ksetrae** [kitao/pyxel#331]
**Bug:**
In the new 1.5.0 version, using _colkey_ argument as keyword argument (e.g. `pyxel.blt(self.x - scroll_x, self.y, 0, 40, 0, 8, 8, colkey=0)`)  throws TypeError: `TypeError: blt() got an unexpected keyword argument 'colkey'`. 

However, using it as positional argument (`pyxel.blt(self.x - scroll_x, self.y, 0, 40, 0, 8, 8, 0)`) works fine.

**How to reproduce:** 
For example, in[ examples/10_platformer.py](https://github.com/kitao/pyxel/blob/00c3f163f238af35e562c1813097764c609e6989/pyxel/examples/10_platformer.py) at line 224 change 
`pyxel.blt(self.x - scroll_x, self.y, 0, 40, 0, 8, 8, 0)`
to 
`pyxel.blt(self.x - scroll_x, self.y, 0, 40, 0, 8, 8, colkey=0)`
and run the script.

**Comment by kitao** [comment]
Thank you for your report. I fixed it locally. It will be released soon as 1.5.1.
