### ISSUE TITLE
Please help with translating READMEs for Pyxel 1.5.0

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#332]
Hi all,

I released Pyxel 1.5.0 but its READMEs are not translated perfectly and some parts are written in English.
It would be appreciated if some volunteers help with translation.

Especially volunteer members who translated READMEs before, please consider it. Thank you.
@YifangSun @humrochagf @gamwe6 @grewn0uille @Nadpher @dora-0 @KoschenkoVlad @Koshchanka

**Comment by kitao** [comment]
Thank you for your cooperation.
Chinese, English, German, Korean, and Japanese are finished!
French, Italian, Portuguese, Russian, and Spanish remain.

**Comment by YifangSun** [comment]
The new Pyxel rewritten in Rust is released. Great job! Can't wait to use it.

Clean code need clean folder.
There were so many README in root folder.  What about move **descriptive** files such as README.aa.md into one folder which maybe called "doc/" or something else.

**Comment by kitao** [comment]
Thank you for translation.
Good idea! I’ll move READMEs.

2021年12月12日(日) 21:40 Nameless ***@***.***>:

**Comment by kitao** [comment]
Now French version is added. Thank you for your cooperation.
And I changed the file structure of the READMEs. Please take care of if when you translates the READMEs.
Many links in the READMEs are changed.

**Comment by edusombra** [comment]
Hi, I wanted to leave here the README.es.md

I have been receiving some advice from the Pyxel community via the discord and I wanted to give back all the help I was given. This won't compensate for how many questions I asked, but it is the most I can do right now.

[RRADME.es.md](https://github.com/kitao/pyxel/files/7723296/RRADME.es.md)

**Comment by kitao** [comment]
@edusombra Thank you. But it seems that your README.es is not based on [the current Spanish translated version](https://github.com/kitao/pyxel/blob/main/doc/README.es.md).
So every description is changed and all links are old.
Could modify it to be based on the current one?

**Comment by edusombra** [comment]
Yes, here it is, with the links from the current Spanish version
[RRADME.es.md](https://github.com/kitao/pyxel/files/7726487/RRADME.es.md)

**Comment by kitao** [comment]
Thank you! I merged it.

**Comment by kitao** [comment]
The remaining are Italian, Portuguese, and Russian.
Anyone who speaks those languages, please help!

**Comment by PaulcPaul** [comment]
Hi! I would like to help with the Portuguese translation.

I'll be sending a PR as soon as I can.

**Comment by humrochagf** [comment]
Oops, sorry @PaulcPaul I started translating it when @kitao  mentioned me at the Issue, just hadn't enough time to finish it.
I just pushed the WIP, so you don't have to make any rework.

I was planning to finish it this weekend, but if you want to take it from there, feel free to either merge it into your changes or start from scratch as well :slightly_smiling_face:

**Comment by PaulcPaul** [comment]
Lol I am so sorry about that @humrochagf . I'll continue from where you left if that's okay with you.

**Comment by humrochagf** [comment]
Great job with the merging of translations @PaulcPaul :tada:

**Comment by PaulcPaul** [comment]
No problem @humrochagf ! I made sure to fork from you to keep your changes in the branch history.

Love this library like you wouldn't believe. Great job from @kitao !

**Comment by kitao** [comment]
Thank you everyone.

The rest are Italian and Russian.

**Comment by kitao** [comment]
Hello, translation volunteers. Thank you for your cooperation.
Some small parts of the READMEs are changed in response to the changes after 1.5.1 release.
It would be appreciated to check it and reflect the changes. Thank you!

**Comment by kitao** [comment]
Unfortunately, it seems that there is no translation volunteers for Italian and Russian.
My policy is that nothing is better than incomplete information.
So after a while, I'll remove Italian and Russian from the official READMEs.

**Comment by kitao** [comment]
Thank you, @SSNikolaevich.
Now the remaining language is Italian!

To the other language's translation volunteers, I'm sorry to bother you many times.
Actually the `init` function has added a new option.  (Its description consists of only several words)
I'd be appreciated if you translated it and check your language's README again.

**Comment by humrochagf** [comment]
Hi @kitao I just sent the update for Portuguese translation for the init function. One thing that I noticed is that at the Example call of the function the parameter is missing. It would be nice to have it there for reference on how to use it.

**Comment by kitao** [comment]
@humrochagf Thank you! I added an extra option to the example of `init`. It should be included in the next release.

**Comment by kitao** [comment]
Hi, @Nadpher. A happy new year!
Is it possible to get your help with an Italian translation?

**Comment by kitao** [comment]
Thank you for your cooperation, volunteers.
Regarding the `capture_scale` instruction for `init` function, the following languages are not translated:
- Chinese
- Germany
- Italian
- Korean
The instruction sentence consists of only a few words, so please consider it. Thank you!

**Comment by kitao** [comment]
REAME will be updated as needed in the future, so I would like to close this ISSUE for 1.5 except for the Italian version.
Thank you for your continued cooperation!
