### ISSUE TITLE
Coordinates error in the Pyxel Editor

### ISSUE THREAD

**Issue by edusombra** [kitao/pyxel#337]
When using the Pyxel editor, installed on an M1 device, the standalone version has a couple of errors. Copying and pasting is not working, as it tries to copy from one coordinate, near the start of the image bank. This problem is related to the second problem, which is that the coordinates shown on the image bank are not multiplied by 8 when moved to another position that is not the start. For example, when moving down with the arrows, the coordinates are 0, 1 instead of 0, 8 (the upper left corner) 

Attached are 3 images of the problem
![Screenshot 2021-12-16 at 00 13 34](https://user-images.githubusercontent.com/83667153/146279519-0352e65d-5d21-46b0-9709-9d437a156228.png)
![Screenshot 2021-12-16 at 00 13 21](https://user-images.githubusercontent.com/83667153/146279522-75cdee4c-eeca-4ab3-89df-abdd7eb22d7a.png)
![Screenshot 2021-12-16 at 00 13 40](https://user-images.githubusercontent.com/83667153/146279523-4caa322f-d15c-4548-94dc-bc65cc18aad1.png)

**Comment by kitao** [comment]
I don't have M1 Mac, but I fixed some position-related issues of the editor.
Could you check how about the issue is in the latest 1.5.1?

**Comment by edusombra** [comment]
Yes, in the latest version, 1.5.1 it all now works, copying and pasting
