### ISSUE TITLE
What educational institutions are using Pyxel?

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#339]
Hi, Pyxel users.
Thank you for enjoying Pyxel. Let me ask you one question.

From time to time, I get reports that Pyxel is used in school and cram school classes, so I would like to know exactly what kind of place and grade it is actually used in.
If you don't mind, could you please tell me the school name and country, (and if possible, the content of the lesson) by replying to this issue?

[Japanese]
時折Pyxelを学校や塾の授業で活用していると教えていただくのですが、実際にどんな場所や学年で使われているか知りたく思っております。差し支えなければ、教育機関名・国（さらに可能であれば簡単な授業内容）について、本Issueに返信する形で教えていただけないでしょうか。日本語でも結構です。よろしくお願いします！

**Comment by edusombra** [comment]
We have been using Pyxel in the UC3M in Spain, that is why during November and December, you have had an increased activity and some chats were in Spanish

**Comment by kitao** [comment]
Thank you for your information. @edusombra
Interesting! I hope the students found the joy of programming.

**Comment by kitao** [comment]
I heard that Keio University and Osaka University in Japan utilizes Pyxel for their classes.

慶應技術大学と大阪大学でPyxelを使った授業を行なっているそうです。

**Comment by laurentabbal** [comment]
French International School of Tokyo. "Première" and "Terminale" (Lower Sixth and Upper Sixth). The students love it. An example by one of my students : https://twitter.com/j3am6s/status/1469682600654835713.

**Comment by danbst** [comment]
I've started using Pyxel in introduction Python course for 8-9-10 grades in a private school in Kyiv, Ukraine. Pyxel is planned to be used for a yearly project.

Previously I used Turtle, but 8bit aesthetics is much more welcomed. IMO the basic API is more powerful than Turtle's (putpixel, getpixel, image maps, blits), and low-dimension screen greatly compensates Python's slowness.

**Comment by kitao** [comment]
Thank you, @laurentabbal and @danbst.
I'm surprised and glad that Pyxel is used by young students.

**Comment by takashihattori** [comment]
We have been using Pyxel for 2 years in an introductory programming course for 1st grade students in SFC (Shonan Fujisawa Campus), Keio University.  I greatly appreciate that Pyxel helps to keep motivation of students.

**Comment by kitao** [comment]
@takashihattori Thank you for sharing the situation.
I'm very glad to hear that Japanese university utilize Pyxel!

**Comment by kitao** [comment]
@krp Thank you for sharing the information.
The snippets for students is very good idea and look useful!

**Comment by matteoturini** [comment]
There is a game jam happening called "Nuit du C0de", night of code, organized by the Tokyo French High-School (correct me if I'm wrong) with all the French schools that are outside of France.

**Comment by laurentabbal** [comment]
> There is a game jam happening called "Nuit du C0de", night of code, organized by the Tokyo French High-School (correct me if I'm wrong) with all the French schools that are outside of France.

That's correct. 155 schools, 4429 students, 138 cities, 38 countries

**Comment by fRbOl23** [comment]
> There is a game jam happening called "Nuit du C0de", night of code, organized by the Tokyo French High-School (correct me if I'm wrong) with all the French schools that are outside of France.

Actually, some that are inside too, it used to be more Asian-centered, but now every _lycée français_, including ones in France, can subscribe, making it very international.
