### ISSUE TITLE
Snake game – example?

### ISSUE THREAD

**Issue by timbledum** [kitao/pyxel#34]
Hello!

Thanks for the great library! I've created a simple snake implementation using it – happy for you to use as another example if you like (but all good if not).

https://github.com/timbledum/snake
![pyxel-180805-215153](https://user-images.githubusercontent.com/20265151/43684822-41dd51e8-98fb-11e8-910a-a3ffc1b25acb.png)

**Comment by eliheuer** [comment]
@timbledum This was helpful for me, thanks!

**Comment by kitao** [comment]
@timbledum 
It's cool! Especially, I'm very surprised that you are using sound function well.
Let me think which place is suitable for your example. (I may make new place for examples from users apart from the current simple examples for beginners)

**Comment by timbledum** [comment]
Cheers! Yes – good idea.

Yeah the sound and music did take me a chunk of time (and 1/3 of the code by lines!), but it adds so much to the game. The example was super helpful, and I did steal your drums. It's really cool that it's all being generated by the lib too!

**Comment by kitao** [comment]
Hi! I created the wiki(https://github.com/kitao/pyxel/wiki) and introduced you sample.
Thank you for an excellent sample!
