### ISSUE TITLE
Adding multiplayer to pyxel?

### ISSUE THREAD

**Issue by ValorZard** [kitao/pyxel#343]
Hello,
I just found out about this engine, and I'm wondering if it would be possible to add multiplayer to this engine. Specifically, rollback netcode with the GGRS library (https://github.com/gschup/ggrs) might be very interesting. It would allow for very low latency multiplayer online.

**Comment by kitao** [comment]
Thank you for your suggestion.
One of the features of Pyxel is its flexibility.
I heard some people already tried to implement multiplayer feature with other module.
