### ISSUE TITLE
Keys does not honor local keyboard layout (reopening of #157)

### ISSUE THREAD

**Issue by yblake** [kitao/pyxel#349]
In 1.5.3, running 01_hello_pyxel.py using French keyboard does'nt exit when pressing "Q" with code : 

`if pyxel.btnp(pyxel.KEY_Q):` 
then Window is closed when pressing key "A"

If I change the code to :
`if pyxel.btnp(pyxel.KEY_A):` 
then Window is closed when pressing key "Q"

I worked around changing all samples code to:
```
        if pyxel.btnp(pyxel.KEY_ESCAPE):
            pyxel.quit()
```

**Comment by yblake** [comment]
May be linked to this Rust-sdl2 issue #1065 : [Implement serde::{Serialize, Deserialize} ?](https://github.com/Rust-SDL2/rust-sdl2/issues/1065)

They advice to use `Keycode::from_scancode` to retrieve key label.

**Comment by kitao** [comment]
Thank you for the information.
I changed the key definitions of Pyxel to SDL2 Keycode base.
Now you should get the non US keyboard keys correctly.
Please try Pyxel 1.5.5.
