### ISSUE TITLE
API for dynamically changing game speed

### ISSUE THREAD

**Issue by timbledum** [kitao/pyxel#35]
Use case – a game that gradually gets faster as the difficulty ramps up.

I achieved this by modifying pyxel._app _one_frame_time and pyxel._app._fps, but it would be great if there was a more official way to do this.

**Comment by kitao** [comment]
There's no official way to change the speed of updating dynamically and changing `_app_one_frame_time` affects system processing such as button, so you should not change it.

I think most simple and safe way to change update speed is make another your own update function and call it from normal update function while changing updating frequency.

**Comment by timbledum** [comment]
OK – you're saying to essentially set the game speed as quite high, then control the speed of execution yourself within this framework?
