### ISSUE TITLE
Please help me update the Italian version of the README

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#366]
The Italian version of the README has not yet been translated for the version 1.5 update, so if you understand Italian, please help with the translation.

The English part of the link below is the part that needs translation:
https://github.com/kitao/pyxel/blob/main/doc/README.it.md

I look forward to your cooperation! Thank you.

**Comment by MauroCoppola** [comment]
Hi! I'd like to help with the Italian translation (I'm already working on it actually 😄).
I can create the pull request in the coming days.

**Comment by kitao** [comment]
Great! Thank you very much!

2022年1月11日(火) 8:03 Mauro Coppola ***@***.***>:

**Comment by kitao** [comment]
Thank you for your translation!
