### ISSUE TITLE
Mouse cursor speed is accelerated on Linux

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#367]
The speed of the Pyxel mouse cursor looks doubled on Linux.
It seems that it is caused by the mouse settings of SDL2 for Linux while the actual system mouse cursor is invisible.

Any information for solving this issue is welcome!

**Comment by merwok** [comment]
I don’t notice this problem on debian testing with libsdl2-2.0-0

**Comment by kitao** [comment]
Thank you. It may happen only on Linux VM on Mac due to the irregular screen resolution.

**Comment by kitao** [comment]
It seems that there's no other same report, I close this issue.
