### ISSUE TITLE
During the pyxel.init argument border_color is not working.

### ISSUE THREAD

**Issue by kamilko** [kitao/pyxel#37]
While trying to add some border to screen, there is no change with adding `border_color` argument.
Border is always black.
No matter if there is custom palette added or default.

**Comment by kamilko** [comment]
Yes, 24bit works. Thank you.
But I don't know why this is so different from other functions.
I've already did pull request https://github.com/kitao/pyxel/pull/41 with fix for that.

**Comment by kitao** [comment]
Actually I implemented the palette color version first.
But I realized that users sometimes need to set the color that is not included in the palette to distinguish between border and drawing area. As a result of that, Pyxel's default border color is different from the default palette and user can identify border whatever color user uses in the drawing area.

**Comment by kamilko** [comment]
Ok, I get it.
So now only README.md should be updated to just inform about it.

**Comment by kitao** [comment]
I updated the READMEs in v0.7.8.
