### ISSUE TITLE
Please help translate the README update

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#370]
Some parts of the README have not been translated, so I would appreciate your help.

- Three lines of the example introduction
- The reference of the `camera` function
- The reference of the `bltm` function

**Comment by erickisos** [comment]
Hey!

Which langs are involved?

**Comment by kitao** [comment]
Specifically the following READMEs need translation updates.

- Chinese
- German
- French
- Portugese
- Russian

**Comment by kitao** [comment]
I updated the READMEs with Google translation's help!

**Comment by kitao** [comment]
Yes, please.
Any correction is welcome.

2022年1月25日(火) 23:29 Diego Ramirez ***@***.***>:
