### ISSUE TITLE
Can it be used with rust instead of python?

### ISSUE THREAD

**Issue by jcornaz** [kitao/pyxel#372]
Hey, the project looks really great :-)

I see a significant part this project sources is using rust:

![image](https://user-images.githubusercontent.com/2535178/151170555-82d1f06e-7924-49a7-b081-c08763862794.png)

And as I personally prefer rust to python, I am wondering:

Is it possible to use rust instead of python?

If yes, is there a doc for usage from rust?

If it is possible but there is no documentation, could you give me an entry point were I can try to figure out stuff by myself (by reading rust code if necessary)?

**Comment by kitao** [comment]
The document and examples don't exist, but you can.
Please check this repository. It can be a kind of entry point.
https://github.com/kitao/gobliso

**Comment by kitao** [comment]
And this is the test code for Rust:
https://github.com/kitao/pyxel/blob/main/lib/engine/tests/test_pyxel.rs
This code is simpler than the previous repository.

**Comment by jcornaz** [comment]
Awsome thanks! I know what I'll be doing this weekend :-)
