### ISSUE TITLE
Issue with `rndi()` in examples

### ISSUE THREAD

**Issue by notbored** [kitao/pyxel#375]
In some of the examples a function called `rndi()` is used but is no longer in the `pyxel` lib/module. 

It's used in the following:
- 02_jump_game.py
- 06_click_game.py
- 07_snake.py
- 09_shooter.py

**Comment by kitao** [comment]
`pyxel.rndi` is added from 1.6.9. And the examples of 1.6.9 also use it.
Could you check the version of Pyxel you used to run the examples?
And I also would like to know your OS and installation way of Pyxel (pip or standalone binary).

**Comment by notbored** [comment]
Sorry, I didn't even think to check(or look at the shell output properly) as I did a fresh install with Homebrew.

The issue was that I had an old version installed(`1.6.8`) using `pip` and that was being used instead of version `1.6.9` installed via Homebrew.

Now using `1.6.9` everything is fine so apologies for that!

**Comment by notbored** [comment]
My default way is using Homebrew to install on MacOS or to use PIP if it's not available.
