### ISSUE TITLE
`text()` throws `TypeError` when giving a non-string value to it's `s` parameter

### ISSUE THREAD

**Issue by notbored** [kitao/pyxel#376]
```python
pyxel.text(50, 50, pyxel.frame_count, 1)
```
Causes:
```shell
TypeError: argument 's': 'int' object cannot be converted to 'PyString'
```

Works fine if you explicitly convert integer/non-string values to a string using `str()`:
```python
pyxel.text(50, 50, str(pyxel.frame_count), 1)
```

Would it be possible for `text()` to behave similarly to `print()` and convert all arguments to strings where necessary.

**Comment by kitao** [comment]
It's a good idea, but due to the Rust module for making Python interface, it's difficult to implement without dirty hack on Python side. When I found the way of automatic casting on pyo3 (it's the name of the rust module), I'll implement this feature.

**Comment by merwok** [comment]
Can rust code call the Python function `str`?
