### ISSUE TITLE
Replace `pyxel.KEY_NONE` with `None`

### ISSUE THREAD

**Issue by notbored** [kitao/pyxel#379]
Only a nitpick and I'm also a beginner so maybe I'm not correct but could `quit_key` accept `None` instead of `pyxel.KEY_NONE`.

I think the value `None` makes more sense(I tried to do that before rereading how to do it in the README). `None` seems typically/conventionally used when representing "nothingness/absence" in Python.

**Comment by kitao** [comment]
I'd like to distinguish between "key is not specified as option" and "It was specified not to perform key detect" in both Rust and Python module in common way. So I don't change the API.
