### ISSUE TITLE
Discussion? Argument border_with is not scaled.

### ISSUE THREAD

**Issue by kamilko** [kitao/pyxel#38]
If I want scale Pyxel window, and add an border to it, border has always value in pixels while rest of the screen is pixels*scale.

app.py lines 61 and 62:
```
window_width = width * scale + border_width
window_height = height * scale + border_width
```

Shouldn't be border scaled together with "work area"? I mean for me it's a little not natural if part of screen is scaled and part of it's not.
Shouldn't be fixed with:
```
window_width = (width + border_width) * scale
window_height = (height + border_width) * scale
```
?

**Comment by kitao** [comment]
First, Pyxel's window is resizable (actually).
And Pyxel's rendering area keeps its resolution specified in the `init` command though it is scaled depends on the window size.
On the other hand Pyxel's border area works as a margin, so border area changes regardless of the scale value.
So I decided the border ares should not be affected by the scale value.
