### ISSUE TITLE
Pyxel is not initialized

### ISSUE THREAD

**Issue by marcsshawty** [kitao/pyxel#381]
When i try to load my .pyxres archive, my program don't run and show this message in terminal: 

PS C:\Users\mwrcs\Documents\codes> & C:/Users/mwrcs/AppData/Local/Programs/Python/Python310/python.exe c:/Users/mwrcs/Documents/codes/PONG_AGR_VAI.py 
thread '<unnamed>' panicked at 'Pyxel is not initialized', wrapper\src\lib.rs:69:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "c:\Users\mwrcs\Documents\codes\PONG_AGR_VAI.py", line 147, in <module>
    pyxel.load("art.pyxres")
pyo3_runtime.PanicException: Pyxel is not initialized

[https://prntscr.com/26pre4a](url)

**Comment by DiddiLeija** [comment]
Did you run `pyxel.init` before loading the resource?

If not, Pyxel is expected to fail, because you should run `init` before anything else.
