### ISSUE TITLE
Tips for UX Enhancements

### ISSUE THREAD

**Issue by rafaelvasco** [kitao/pyxel#385]
Hey, first of, amazing little engine. Well done. I just wanted to post some things that could improve user experience on the editor:

- Change scroll button from right mouse button to middle mouse button or space key + left mouse button.
- Add the ability to copy a frame region just by selecting it on the right panel, ctrl+c, selecting the target frame rect, ctrl+v.
- Add the ability to invert a frame pixels horizontally and vertically. 
- Add the ability to rotate a frame pixels clockwise 90 degrees (less important).
- Add the ability to clear the current frame region with the current selected color on palette. This could be a new button and a shortcut, for example : delete key.

Thank you!

**Comment by kitao** [comment]
Thank you for your suggestion.
I'll implement the flip feature (horizontally and vertically) in the next version at least.

**Comment by kitao** [comment]
Flip feature is implemented in 1.7.2.
