### ISSUE TITLE
API for moving window

### ISSUE THREAD

**Issue by matteoturini** [kitao/pyxel#387]
This API would also be useful for more dynamic movement in games.

An example where this is used is in Rythm Doctor, theres [this](https://youtu.be/jkXtILc1XUc) scene where the screen moves with the player to create immersion.

**Comment by merwok** [comment]
Do you mean the `camera` function?  https://github.com/kitao/pyxel/#graphics

**Comment by matteoturini** [comment]
> Do you mean the `camera` function? https://github.com/kitao/pyxel/#graphics

no, I mean the actual game window in the OS

**Comment by merwok** [comment]
Ah, that seems hard to do in a cross-platform way, and probably undesireable for UI / accessibility reasons.

Fun idea though!

**Comment by matteoturini** [comment]
> probably undesireable for UI / accessibility reasons

Isn't that up to the game devs?

**Comment by matteoturini** [comment]
SDL has an API for moving windows. That's as cross platform as it gets.

http://wiki.libsdl.org/SDL_SetWindowPosition

**Comment by kitao** [comment]
I know SDL2 has such kind of API. But whether it works or not depends user's environment and I'd like to avoid such kind of tricky application on Pyxel. So I will not add this API.

**Comment by matteoturini** [comment]
> user's environment

The three supported environments, windows mac and linux, have support for the API.

**Comment by kitao** [comment]
Yes, but display’s resolutions are different. And some users use multiple
displays.
I would like to avoid an title user created doesn’t work correctly on other
user’s environment.

2022年5月1日(日) 7:57 Mattéo Turini ***@***.***>:

**Comment by matteoturini** [comment]
Treat the displays as one big display. 

> display’s resolutions are different.

That is why there should be a display resolution API too

**Comment by kitao** [comment]
I understand the necessity of the resolution API.
But Pyxel's design policy is that users don't need to care about
environments they don't have and the same code should work almost the same
on various environments for simplicity.
Display-related APIs are against the policy and too complicated to
guarantee user's apps work correctly.
That's the reason I don't implement them. (And of course you have the right
to fork and modify Pyxel!)


2022年5月2日(月) 0:15 Mattéo Turini ***@***.***>:
