### ISSUE TITLE
How to use Tilemap.set ?

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#390]
The doc shows a list of 4 strings made of 6 hex digits, without explaining the meaning.

**Comment by kitao** [comment]
Actually descriptions in the READMEs were old. I updated them.
Text should be 4 characters per one tile like "0102" for (1, 2). Spaces are ignored.
There is a working example code  in example2.

**Comment by merwok** [comment]
Thanks for the update!

Could the readme explain that `"0102"` means `(1, 2)` ?
What is example2 ?  (didn’t find `set` in 02_jump_game)

**Comment by kitao** [comment]
Sorry! It’s example3!

2022年4月30日(土) 19:37 Éric ***@***.***>:
