### ISSUE TITLE
API suggestion: avoid similar function and class (tilemap and Tilemap)

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#391]
The most pythonic way would be to use `Tilemap(param)` to get an instance.  For multiple signatures (`width, height, img` or `tm`), the typical solution is classmethods (see dict.fromkeys, int.from_bytes, etc. → could be `Tilemap.load`)

**Comment by kitao** [comment]
tilemap function is for getting singleton instance.
If you use Tilemap class name as method, you can create new instance of Tilemap class.
Though I'm not sure what pythonic way is, but it's a normal design from the perspective of game engine.

**Comment by merwok** [comment]
Ah ok!  Could this info be added to the readme then?
