### ISSUE TITLE
Typing error in the documentation

### ISSUE THREAD

**Issue by LeonPupier** [kitao/pyxel#395]
Hello,
I found some functions explained in the documentation where they are missing an "_**s**_" in the name of the function in the examples provided.
I have noticed that this problem is common to all languages in the documentation.

> ![doc](https://user-images.githubusercontent.com/100092382/172043430-1380f083-d59d-4559-a926-1ea050321f16.png)

_Despite this, you are doing a great job, thanks for everything!_

**Comment by kitao** [comment]
Thank you for checking.
These kind of information is very helpful.
I corrected the descriptions.
