### ISSUE TITLE
Option to store pyxres files as text (XML)

### ISSUE THREAD

**Issue by SuperZooper3** [kitao/pyxel#396]
The idea behind storing things as text is useful because it lets Git play with merges and changes of parts of pyxres files instead of only having 1 change at a time linearly. This would be fantastic for collaboration

**Comment by merwok** [comment]
Personally, I would enjoy a way to save pyxres as a directory of files (the exact same format as is currently used, but unzipped – I fact I already unzip and save).  I do not think adding XML to the file formats would be a good move.

**Comment by kitao** [comment]
I don't feel the need for that feature so much, and you have a way to use unzipped text, so let me close this issue.
