### ISSUE TITLE
Keyboard processing idea

### ISSUE THREAD

**Issue by kra53n** [kitao/pyxel#399]
You may encounter a problem when you want to perform the same action with several buttons pressed. And it's a challenge to do it beautifully.

It would be great if it could be done like this:

```python
if pyxel.btnp(pyxel.KEY_W | pyxel.KEY_UP):
    do_something()
```

Instead of this:

```python
if pyxel.btnp(pyxel.KEY_W) or pyxel.btnp(pyxel.KEY_UP):
    do_something()
```

I think the first way is more flexible because you could give keys to some variable and use it in conditions:
```python
go_up = pyxel.KEY_W | pyxel.KEY_UP
if pyxel.btnp(go_up):
    do_something()
```

But perhaps this idea leads to an overloaded design.

**Comment by kitao** [comment]
Whether this idea is good or bad, I think there aren't enough bits to cover all keys.
