### ISSUE TITLE
Got b'X11: RandR gamma ramp support seems broken' 

### ISSUE THREAD

**Issue by cuu** [kitao/pyxel#40]
Hi
I am trying to run pyxel on a arm-based GameConsole called [GameShell](https://www.clockworkpi.com/), GPU is Mali 450

got these errors when try to run    **01_hello_pyxel.py** 

```
Traceback (most recent call last):
  File "01_hello_pyxel.py", line 20, in <module>
    App()
  File "01_hello_pyxel.py", line 6, in __init__
    pyxel.init(160, 120, caption='Hello Pyxel')
  File "/home/cpi/.local/lib/python3.5/site-packages/pyxel/__init__.py", line 33, in init
    border_width, border_color)
  File "/home/cpi/.local/lib/python3.5/site-packages/pyxel/app.py", line 57, in __init__
    if not glfw.init():
  File "/home/cpi/.local/lib/python3.5/site-packages/glfw/__init__.py", line 606, in init
    res = _glfw.glfwInit()
  File "/home/cpi/.local/lib/python3.5/site-packages/glfw/__init__.py", line 515, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/cpi/.local/lib/python3.5/site-packages/glfw/__init__.py", line 45, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/cpi/.local/lib/python3.5/site-packages/glfw/__init__.py", line 494, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/cpi/.local/lib/python3.5/site-packages/glfw/__init__.py", line 668, in _raise_glfw_errors_as_exceptions
    raise GLFWError(message)
glfw.GLFWError: (65544) b'X11: RandR gamma ramp support seems broken'
```

OS env:
python3.5
Linux clockworkpi 4.14.2-clockworkpi-cpi3 #1 SMP Sat Jul 14 09:34:56 CST 2018 armv7l GNU/Linux
libglfw3   (3.2.1-1).

here is the 

> glxinfo | grep Open

```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

```
the full version of glxinfo is [here](https://paste.ubuntu.com/p/kXsyX4nqNY/)

Do you know why I can not run pyxel successfully ,
why I get the error X11: RandR gamma ramp support seems broken'  ?

Thanks

**Comment by kitao** [comment]
GameShell looks interesting!

It just failed to initialize glfw by calling `glfw.init`.
So we need to find the way to run glfw on this environment.

I'm not sure the below link is related to this problem, but there's some information which mentions `X11: RandR gamma ramp support seems broken' message at least. 
https://github.com/glfw/glfw/issues/1004

**Comment by kitao** [comment]
Because I don't have GameShell environment, the current version of Pyxel doesn't support it officially.
I'll take care of this environment when I get it and feel sure many users want its support.

**Comment by rkrishnasanka** [comment]
@kitao Looks like its broken even on the Raspberry Pi's default Debian. I just compiled glfw on it and I get the same error.

**Comment by wookayin** [comment]
This is a bug of glfw3.2. Try installing glfw 3.3+.
