### ISSUE TITLE
Mouse coordinates hasn't changed after calling camera()

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#400]
1. Call `pyxel.mouse_x` or `pyxel.mouse_y`
2. Call `pyxel.camera(x, y)`
3. Call `pyxel.mouse_x` or `pyxel.mouse_y`

Mouse coordinates same for (1) and (3). Expected to be different since camera was moved.

**Comment by kitao** [comment]
The `camera` function only affects the drawing positions of the drawing APIs.
It doesn't affects input-related positions and reference positions for image drawing.
