### ISSUE TITLE
Import Error on Mac

### ISSUE THREAD

**Issue by kantel** [kitao/pyxel#401]
When I try to run Pyxel I got the following Import Error:

>Traceback (most recent call last):
  File "/Users/admin/git/pyxel/gettingstarted/hellopyxel.py", line 1, in <module>
    import pyxel
  File "/Users/admin/Library/Python/3.10/lib/python/site-packages/pyxel/__init__.py", line 6, in <module>
    from .lib.macos.pyxel_wrapper import *  # type: ignore  # noqa F403
ImportError: dlopen(/Users/admin/Library/Python/3.10/lib/python/site-packages/pyxel/lib/macos/pyxel_wrapper.so, 2): Symbol not found: _CHHapticDynamicParameterIDHapticIntensityControl
  Referenced from: /Users/admin/Library/Python/3.10/lib/python/site-packages/pyxel/lib/macos/pyxel_wrapper.so
  Expected in: flat namespace

as well as with Python 3.10 (Thonny) as with Python 3.8 (Anaconda).

I run this on a MacBook Pro (from 2012) with MacOS Catalina with Pyxel 1.7.1.

**Comment by kitao** [comment]
Probably this issue happens due to a version difference of macOS. I also got the same issue report from a user uses Catalina.
I'll search for a way not to refer  _CHHapticDynamicParameterIDHapticIntensityControl from SDL2. Any information for it is welcome.

**Comment by kitao** [comment]
For reference: https://githubhot.com/repo/ruby2d/ruby2d/issues/230

**Comment by nosoroog** [comment]
Same issue. 
Works with Pyxel 1.6.9.
I use MacBook Pro (Mid 2012) with MacOS Catalina 10.15.7.

**Comment by Evgeny-TechnoNinja** [comment]
```
rom .pyxel_extension import *  # type: ignore  # noqa F403
ImportError: /mnt/school/PYTHON/gamesdev/pyxeldemo/tstfirst/venv/lib/python3.8/site-packages/pyxel/pyxel_extension.abi3.so: undefined symbol: SDL_Metal_DestroyView
```
Ubuntu 20. Pyxel didn't take off, pyxel 1.9.12

**Comment by Evgeny-TechnoNinja** [comment]
pip install pyxel==1.9.0 
works well with basic examples
