### ISSUE TITLE
Example links are broken

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#405]
Example links in Readme are broken, e.g.:
https://github.com/kitao/pyxel/blob/main/pyxel/examples/01_hello_pyxel.py

**Comment by km19809** [comment]
Will this commit (https://github.com/kitao/pyxel/commit/aa436fe13ec9570a21a09004e05d6f9f0c989cac)  solve the issue?

**Comment by kitao** [comment]
Thank you for report. I fixed it.
