### ISSUE TITLE
Is there any plan to make an in-app python editor?

### ISSUE THREAD

**Issue by km19809** [kitao/pyxel#406]
I am curious if you have any plan to make an in-app python editor.
As a library, it does not need to have a script editor. 
It is often inferior to dev tools like VSCode.
However, fantasy consoles like PICO-8 or TIC-80 have an editor.
So if you want to make pyxel a (standalone) fantasy console, I think there should be an in-app editor.

p.s.
I tried to use the pyxel editor in the browser, then I came up with this idea. (The attempts are not successful yet.)
Some platforms, such as browser, Android, and RaspberryPi, would benefit from a standalone app.
It is irritating to import codes from the external editor on these platforms.

**Comment by kitao** [comment]
For native platforms, I don't have any plan to support an in-app editor. Because implementing editor and supporting it for many platforms are very hard.
But regarding a web platform version, it may be good idea. Because it works regardless of platform and also there is useful text editor library like ACE.
I hope somebody try it because I don't have time now.

**Comment by laurentabbal** [comment]
I started working on it (with Ace precisely). I've implemented Ace in many differents projects. For the "Nuit du c0de", my goal is to have the same kind of development environnement as Scratch. That's why I was eagerly awaiting for the web version of Pyxel.

**Comment by kitao** [comment]
@laurentabbal Please go ahead with it.
I'll focus on developing the stable web version of Pyxel for a while.

**Comment by laurentabbal** [comment]
Hi. A first version of the online editor (playable game on the left and code editor on the right) should be published this week. So far, it works fine with simple scripts. More tests ahead.

**Comment by laurentabbal** [comment]
Example :
![image](https://user-images.githubusercontent.com/592821/186606676-06fec019-6f89-42e6-930a-89092b3497ec.png)
The user can change the code in the editor (on the right) and reload the game and play (on the left).

**Comment by laurentabbal** [comment]
Demo : www.pyxelstudio.net

**Comment by km19809** [comment]
@laurentabbal 
Can pyxelstudio be integrated with pyxel editor?
I hope it can edit and download the `.pyxres` file in the browser.

**Comment by laurentabbal** [comment]
> @laurentabbal 
> Can pyxelstudio be integrated with pyxel editor?

I'm working on it right now. The editor works fine in the browser : I can open, modify and save the .pyxres file.
It should be ready next week.

**Comment by laurentabbal** [comment]
It's almost ready. You can already check : www.pyxelstudio.net
I still need to do a last thing : make the .pyxress available for the code.

**Comment by km19809** [comment]
@laurentabbal 
When I use `pyxel.load('res.pyxres')`, the example(moving square with arrow keys) does not work. Perhaps FS issue?

The Code:
```py
import pyxel

class Jeu:
    def __init__(self):
        pyxel.init(128, 128)
        self.vaisseau_x = 60
        self.vaisseau_y = 60
        pyxel.load('res.pyxres') # The only change
        pyxel.run(self.update, self.draw)

    def vaisseau_deplacement(self):
        if pyxel.btn(pyxel.KEY_RIGHT) and self.vaisseau_x<120:
            self.vaisseau_x += 1
        if pyxel.btn(pyxel.KEY_LEFT) and self.vaisseau_x>0:
            self.vaisseau_x += -1
        if pyxel.btn(pyxel.KEY_DOWN) and self.vaisseau_y<120:
            self.vaisseau_y += 1
        if pyxel.btn(pyxel.KEY_UP) and self.vaisseau_y>0:
            self.vaisseau_y += -1

    def update(self):
        self.vaisseau_deplacement()

    def draw(self):
        pyxel.cls(0)
        pyxel.rect(self.vaisseau_x, self.vaisseau_y, 8, 8, 1)
        
Jeu()
```

**Comment by km19809** [comment]
This issue seems to be resolved.
The web-based solution, pixel studio, is good enough for my purpose.
Thank you all.
