### ISSUE TITLE
Draw time is 83800

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#413]
### Description:
Sometimes Pyxel displays draw time 83800

![image](https://user-images.githubusercontent.com/21060932/188491802-0b093838-94cc-4e19-a62b-e955768ae68a.png)

### Steps to reproduce:
1. Run this code:
```
import pyxel
pyxel.init(160, 120)
pyxel.show()
```
2. Enter Alt+0
3. Press few times Alt+Enter

### Configuration:
OS: Win 11
Python: 3.10
Pyxel: 1.8.2

**Comment by kitao** [comment]
Does this issue occur in the latest Pyxel (1.8.12)?

**Comment by alderven** [comment]
> Does this issue occur in the latest Pyxel (1.8.12)?

Seems it has been fixed. Thank you!
