### ISSUE TITLE
Ideas for automatically fetching files on the web

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#416]
Thanks to Pyxel's new utility script, an html file for Pyxel is very simplified like [this](https://github.com/kitao/pyxel/blob/main/wasm/pages/01_hello_pyxel.html).

Another thing I would like to achieve is automatic fetching of files.
It seems that Emscripten can't mount real file system directly, but it may be realized virtually if I can insert some hook script for each load function in Pyxel.

With the feature, I would like shorten this script from

```html
<body>
    <div id="loading">Loading...</div>
    <pyxel-asset name="assets/pyxel_logo_38x16.png"></pyxel-asset>
    <pyxel-run root="../../python/pyxel/examples" name="01_hello_pyxel.py"
        onstart="document.getElementById('loading').remove()"></pyxel-run>
</body>
```

to
```html
<body>
    <div id="loading">Loading...</div>
    <pyxel-run root="../../python/pyxel/examples" name="01_hello_pyxel.py"
        onstart="document.getElementById('loading').remove()"></pyxel-run>
</body>
```

If anyone has the knowledge to implement this feature, I would appreciate any advice.

**Comment by messense** [comment]
> It seems that Emscripten can't mount real file system directly,

Related https://github.com/pyodide/pyodide/pull/2987

**Comment by kitao** [comment]
@messense Thank you for the information.
So the Pyodide main branch has native-fs feature now?

**Comment by kitao** [comment]
Ah it doesn't support Safari for now...

https://github.com/pyodide/pyodide/blob/main/docs/usage/file-system.md

**Comment by kitao** [comment]
In 1.8.12. I added a hook function for Emscripten file system so that Pyxel can get necessary files automatically.

**Comment by km19809** [comment]
It is astonishing!
When I tried synchronous XMLRequest for hooks, the browser blocked it since it is deprecated.
But your approach works!
I know this is a closed issue AND this is not much relevant to the pyxel, but can you tell me how did you make it work?

**Comment by kitao** [comment]
Thank you for your comment.

I just searched for synchronous XMLHTTPRequest sample code which works, and
copied it.
https://github.com/kitao/pyxel/blob/main/wasm/pyxel.js#L292-L299

Regarding file system side, when I tried whether I can replace functions
under pyodide.FS, it worked.
So I wrapped open and stat functions to invoke XMLHTTPRequest when called.
https://github.com/kitao/pyxel/blob/main/wasm/pyxel.js#L319-L330

Best,
Takashi Kitao.

2022年10月6日(木) 17:34 Minsoo ***@***.***>:
