### ISSUE TITLE
Rendering issues in the pyxel window

### ISSUE THREAD

**Issue by AndrewNelis** [kitao/pyxel#42]
Any shape seems to fail to render correctly. Even the basic program:

```python
import pyxel

pyxel.init(50, 50)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)

pyxel.run(update, draw)
```
I would expect just a black screen but instead I see:

![pyxel-180807-143551](https://user-images.githubusercontent.com/1493693/43779264-db2a9aa4-9a4f-11e8-8a7a-41e22f381679.png)

This seems to happen for any shape. For example if I add a circle to the mix:

![pyxel-180807-144648](https://user-images.githubusercontent.com/1493693/43779686-df99d324-9a50-11e8-8802-71986532e855.png)

Example 3 renders as follows:

![pyxel-180807-144811](https://user-images.githubusercontent.com/1493693/43779721-f181eea0-9a50-11e8-87ac-bd487e066b51.png)

OS: Linux Fedora 27
Hardware: NVIDIA Corporation GT218 [GeForce 210] (rev a2)
Pyxel Version: 0.7.7 (but running master version from git at time of writing)
Python: 3.6.6.

**Comment by kitao** [comment]
When you use only `cls` command, Pyxel only draws some rectangle. But your screenshot of it show some noise dots. So I think there is something fundamental problem in the environment, especially around OpenGL.

Is it possible to make sure OpenGL and glfw(3.2.1 or higher) itself work well?

**Comment by kitao** [comment]
Since there is no information update, close it. If you have any problems please create a new issue!
