### ISSUE TITLE
Drawing freezes when click and hold window border

### ISSUE THREAD

**Issue by alderven** [kitao/pyxel#420]
### Description:
Drawing freezes when I click and hold window border. See video capture:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/21060932/192479224-47f1d4ad-aa25-414a-988e-13e022b3b125.gif)

## Steps to reproduce:
1. Run following code:

```
import pyxel


class App:
    def __init__(self):
        pyxel.init(80, 60, display_scale=6)
        self.i = 0
        pyxel.run(self.update, self.draw)

    def update(self):
        self.i += 1

    def draw(self):
        pyxel.cls(pyxel.COLOR_BLACK)
        pyxel.text(s=str(self.i), x=35, y=25, col=pyxel.COLOR_RED)


App()
```

2. Click and hold on window border

## Configuration:
OS: Win 10
Python: 3.10
Pyxel: 1.8.8

**Comment by kra53n** [comment]
I think this is done on purpose so that when the window moves, the game cycle does not iterate. This is done for the convenience of the user, because when he moves the window, he does not play and the game should, in theory, stop.

**Comment by alderven** [comment]
> I think this is done on purpose so that when the window moves, the game cycle does not iterate. This is done for the convenience of the user, because when he moves the window, he does not play and the game should, in theory, stop.

The problem is that `update` function keep working while drawing is freezing.
Ideally both `draw` and `update` should behave identically (both freezing or both updating).

**Comment by kitao** [comment]
I changed a frame skip process in 1.8.11.
Now Pyxel stop fast forward if the elapsed time is more than 0.2 second. Please check it.

**Comment by alderven** [comment]
> I changed a frame skip process in 1.8.11.
> Now Pyxel stop fast forward if the elapsed time is more than 0.2 second. Please check it.

It has been fixed. Thank you!
