### ISSUE TITLE
README.md - Wrong tile coordinate in tilemap image example

### ISSUE THREAD

**Issue by sleepingpandagames** [kitao/pyxel#422]
I was browsing through the README.md file and I think I found a mistake in an image about how to use tilemap in the Graphics section.

See in following screenshot:
![Screenshot_2022-10-09-11-32-53-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/71437756/194749301-9101109b-9363-4397-9ad1-7488200ec668.jpg)

Shouldn't be the value I highlighted (1, 0) and not (0, 1) as it is currently? 

Maybe I'm wrong. If so, please ignore this issue, and sorry about that. 😅

**Comment by kitao** [comment]
Thank you for your report.
It's my mistake. I'll fix it in the next release.

**Comment by sleepingpandagames** [comment]
Cool!
Thanks 👍
