### ISSUE TITLE
Couldn't work screenshot (Alt+1, Alt+3) in web app

### ISSUE THREAD

**Issue by hadamak** [kitao/pyxel#423]
as is: 
  Alt + 1 or Alt + 3 cause freeze in web app.

to be:
  I want to download screenshot pictures.

environment:
  [https://kitao.github.io/pyxel/wasm/examples/script_test.html](https://kitao.github.io/pyxel/wasm/examples/script_test.html) and others.
  -Microsoft Edge or Firefox
  -Windows11

**Comment by kitao** [comment]
In the latest Pyxel, I suppressed crashing error when capture functions are used.

To enabled capture functions on the web like other platforms, the chrono crate of Rust should work on the web and I also need to come up with a way to download save file in Emscripten file system.

**Comment by km19809** [comment]
@kitao 
`chrono` version [above 0.4.20](https://github.com/chronotope/chrono/releases/tag/v0.4.20) should work on emscripten target. https://github.com/chronotope/chrono/pull/568

Doesn't it works?

**Comment by kitao** [comment]
@km19809 It can be compiled. But when I called chrono::Local::now() with Emscripten, it crushed.

**Comment by kitao** [comment]
I tried chrono::Local::Now() at the beginning of Pyxel code for test.
The error message was 
`pyo3_runtime.PanicException: cannot call wasm-bindgen imported functions on non-wasm targets`

**Comment by kitao** [comment]
In the latest version of Pyxel on the web, you can save the output file.

**Comment by hadamak** [comment]
I became able to do that. Thank you for your nice work.
