### ISSUE TITLE
Can I get output for Android? 

### ISSUE THREAD

**Issue by mehrdad-mixtape** [kitao/pyxel#425]
Hi, Can I get output for Android phone?

**Comment by kitao** [comment]
The current Pyxel doesn't support Android. But Pyxel only depends on Python and SDL2 basically, so it is not impossible to make Android version of Pyxel, I think.
And I've also heard that Web version of Pyxel works on Andoird browsers. So the easiest way to run Pyxel on Android is using Pyxel Web for now.

**Comment by dazui20** [comment]
Good news.
