### ISSUE TITLE
Wasm don't work on my mashine (ubuntu 20.04.5 LTS) browsers (Brave, Firefox)

### ISSUE THREAD

**Issue by mehrdad-mixtape** [kitao/pyxel#427]
Hi kitao, Can you help me to fix this problem?
When  I click on browser screen, it's just show me blank screen without anythings. :(
I pulled your repo on my local mashine.
![Screenshot_20221103_231508](https://user-images.githubusercontent.com/71973800/199820528-4463433b-9482-4b4f-ac00-5d7cb8c40a72.png)
After click
![Screenshot_20221103_232327](https://user-images.githubusercontent.com/71973800/199820875-2cb9f85c-8485-4a42-9fdb-bba5f35f1afc.png)

**Comment by km19809** [comment]
Please check your DevTools error.
Also, you better not use `file://` for the web version.
I recommend you to use `python3 -m http.server` in the pyxel directory.
It launches a simple static HTTP server, then you can access the example via localhost.
