### ISSUE TITLE
pyxel edit: Unsupported resource file version

### ISSUE THREAD

**Issue by Intermarch3** [kitao/pyxel#429]
Hello,
I am creating my own video game, everything was fine until today when I try to launch my game or edit my resources with "pyxel edit file.pyxres" , this error appears: 
![image](https://user-images.githubusercontent.com/78302154/204085511-37fa447f-f933-45ce-a60d-b6d96b431563.png)
I'm on windows 10 up to date, with python 3.10.4 and the latest version of pyxel.

My project: https://github.com/Intermarch3/stickman_adventure

**Comment by Intermarch3** [comment]
I forgot to say that I work on different PC which are not necessarily all up to date

**Comment by kitao** [comment]
Could you tell me which version of Pyxel you used before updating to the latest one?

**Comment by Intermarch3** [comment]
i don't know why but i reinstall pyxel and now it work

**Comment by Intermarch3** [comment]
> Could you tell me which version of Pyxel you used before updating to the latest one?

i was 1.8.21
