### ISSUE TITLE
Rendered elements disappear near screen edges

### ISSUE THREAD

**Issue by paulsheridan** [kitao/pyxel#43]
As far as I can tell, both shapes and images that exist at the edges of the screen are not rendered past a certain point.  I've included an example below: 
![pyxel-180808-093649](https://user-images.githubusercontent.com/4859769/43851307-262ef7d0-9aef-11e8-9993-2d0153b33594.gif)
As you can see, rendered elements pop out at the right and left edges as the screen scrolls.  It seems to be when they're more than 50% off screen.  Is this intentional or is it something that could be updated to allow smoother screen transitions.  A link to the project in the image above is here: https://github.com/paulsheridan/pyxel-projects/tree/master/side_scroller

OS: macOS 10.13.5
Hardware: AMD Radeon R9 M370X
Pyxel Version: 0.7.7
Python: 3.6.5

**Comment by timbledum** [comment]
Just jumping in - this behaviour does not happen on my machine. 

Looks awesome btw - super cool!

**Comment by kitao** [comment]
@paulsheridan For your information. I'm using MacBook (Retina, 12-inch, 2017) and macOS 10.13.6. And your code works as expected.

**Comment by paulsheridan** [comment]
Out of curiosity, which version of Python are you using?

**Comment by kitao** [comment]
@paulsheridan  Same with you. Python version is 3.6.5.

**Comment by paulsheridan** [comment]
Oh interesting.  Happy to know that it's local to my environment.  I'll try a clean install tonight.  Thanks!
