### ISSUE TITLE
Pyxel can't be compiled on Intel Mac

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#431]
On Intel Mac with the recent Xcode environment, Pyxel can't be compiled. The situation is similar for Github Actions' hosted runner.
The error happens while compiling SDL2 via rust-sdl2 and the error message is ``ld: library not found for -lstdc++``.

In the case of declaring ``CXXFLAGS="-stdlib=libc++"``, compilation itself is finished without errors, but runtime error ``symbol not found in flat namespace'___isPlatformVersionAtLeast'`` happens when the Python module wrapped by PyO3 and Maturin is imported.

Regardless of declaring the env variable, Pyxel can be compiled and works on Apple Silicon Mac.

Does anyone know how to resolve this issue?
(Especially @messense , do you have any idea?)

**Comment by messense** [comment]
Can you try `maturin==0.13.7`? I suspect it has something to do with `MACOSX_DEPLOYMENT_TARGET` set to 10.7 by default on x86_64 macOS in maturin 0.14.

> symbol not found in flat namespace'___isPlatformVersionAtLeast'

It's the same issue as https://github.com/alexcrichton/curl-rust/issues/279, can be resolved by linking to `clang_rt`.

**Comment by messense** [comment]
> Regardless of declaring the env variable, Pyxel can be compiled and works on Apple Silicon Mac.

> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

arm64 macOS uses `MACOSX_DEPLOYMENT_TARGET=11.0` you can try set `MACOSX_DEPLOYMENT_TARGET=10.9` on x86_64 macOS.

**Comment by kitao** [comment]
@messense Maturin 0.13.7 worked!

**Comment by kitao** [comment]
The environments I tried were macos-12 for aarch64-apple-darwin and macos-12 for x86_64-apple-darwin on GitHub Actions. The built binaries worked on my M1 Mac on Ventura and Intel Mac on Ventura respectively.

**Comment by kitao** [comment]
@messense Should I keep to use Maturin 0.13.7 or update the latest one?

**Comment by messense** [comment]
I think you can stick with 0.13.7 for now, upgrade to new version until https://github.com/PyO3/maturin/issues/1252 is implemented.

If you want to use the latest version, add the `MACOSX_DEPLOYMENT_TARGET=10.9` (or other macOS version, maybe `10.12` is a good choice given https://github.com/rust-lang/rust/pull/104385) environment variable should work.

**Comment by messense** [comment]
BTW, this behavior change in 0.14 is now documented in https://www.maturin.rs/migration.html#macos-deployment-target-version-defaults-what-rustc-supports
