### ISSUE TITLE
Change palette colors in Pyxres editor?

### ISSUE THREAD

**Issue by paul59** [kitao/pyxel#432]
Is this possible? I know I can load an image but that kind of defeats the object of using the editor if the image gas to be created elsewhere. I know colors can be set programmatically but that doesn't really help either.

**Comment by merwok** [comment]
We have to edit pyxel editor source code to support this, see https://github.com/kitao/pyxel/issues/315 and the linked PR.

**Comment by paul59** [comment]
Ok I've read those comments. Having the resource editor use the same palette probably wasn't a good design choice. I can't think of an easy solution to allow changing the palette within the editor :(

**Comment by merwok** [comment]
What about my suggestion: edit the code of pyxel editor?

**Comment by paul59** [comment]
> What about my suggestion: edit the code of pyxel editor?

I understand but it's too clunky IMO, palette change needs to be in the editor... somehow!

**Comment by paul59** [comment]
I just found out that drag and dropping an image into the the resource editor doesn't change the palette either. Instead, the image is adjusted to conform to the editor's palette - not what I was expecting and it makes the editor redundant unless one is prepared to stick to the built-in palette.

**Comment by kitao** [comment]
I'm planning to palette change feature to the next version of Pyxel. Please look forward to it!

**Comment by paul59** [comment]
> I'm planning to palette change feature to the next version of Pyxel. Please look forward to it!

That's good news, thank you! I have one other 'feature request' which probably isn't worth putting in its own thread - can we have a custom splash screen option for HTML5 instead of the Pyxel logo? (Maybe that's already possible and I just haven't figured it out yet!).

**Comment by kitao** [comment]
In Pyxel 1.9.7. You can change the palette on Pyxel Editor with .pyxpal file.
.pyxpal file looks this:
```
ffffff
110011
00ffff
# continues for 16 colors
```
If you put the palette file as the same name of the resource file (.pyxres), the palette file will be loaded when the resource file is loaded.

**Comment by kitao** [comment]
Pyxel palette file (.pyxpal) is a kind of supplemental file for Pyxel resource file (.pyxres).
For primitive drawing, please use `pyxel.colors` list.

**Comment by paul59** [comment]
I see, thank you :D

**Comment by jamad** [comment]
I tried pyxel.colors and found its length has 32 colors. I wonder if there is any plan to support 32 colors in the future? (If so, it would be cool)
