### ISSUE TITLE
rust-sdl2 from master and dynamic linking with libsdl2 < 2.0.12

### ISSUE THREAD

**Issue by comick** [kitao/pyxel#438]
I'm using ubuntu 20.04, shipping with libsdl 2.0.10.
In the crates project for pyxel-core and pyxel extension are found:
```
[patch.crates-io]
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2.git", branch = "master" }
```
which override the rust-sdl2 binding with whatever in on top of master branch. It turns out that HEAD of master introduced bindings unavailable in libsdl 2.0.10, thus failing linking at runtime.

@kitao what is the reason for having the rust-sdl2 dependency overridden with head of master instead of using the latest version released on crates.io? The change seems to be older that 4 months and, at least on Ubuntu 20.04, that seems to be unnecessary. Maybe rust-sdl2 master has some unreleased fix for windows/mac?

**Comment by kitao** [comment]
The reason is to support Emscripten (Web) version of SDL2.
Unfortunately the latest tagged version of Rust-SDL2 doesn't use the SDL2 which supports Emscripten.

**Comment by comick** [comment]
Thanks for the explanation. Ubuntu 20.04 is anyway previous LTS, so no actual concern, closing.
