### ISSUE TITLE
cant run pyxel command

### ISSUE THREAD

**Issue by QuantumV2** [kitao/pyxel#439]
![image](https://user-images.githubusercontent.com/83087109/210148725-2907bf00-36a6-4853-b2dc-f66098b88255.png)

**Comment by QuantumV2** [comment]
when reinstalling this happens
![image](https://user-images.githubusercontent.com/83087109/210148987-964e8e50-9925-4f9e-9c98-9e7dd8e0e944.png)

**Comment by kra53n** [comment]
I'm not sure but this can happen if multiple Python are installed. How many versions of Python do you have?

**Comment by QuantumV2** [comment]
> 

the same thing happens, it didnt help
