### ISSUE TITLE
Add an image programmatically into a resource file

### ISSUE THREAD

**Issue by laurentabbal** [kitao/pyxel#441]
Hi,
The documentation says "By dragging and dropping an image file (png/gif/jpeg) onto the Image Editor screen, the image can be loaded into the currently selected image bank.".
Is it possible to do the same programmatically ? 
Thanks

**Comment by rafrafek** [comment]
Can it be programatically saved as `.pyxres`?

**Comment by kitao** [comment]
Yes. `pyxel.save` function exists.

Please check https://github.com/kitao/pyxel/blob/main/python/pyxel/__init__.pyi

**Comment by rafrafek** [comment]
Thanks!
