### ISSUE TITLE
Support MicroPython  on ESP32 machine ?

### ISSUE THREAD

**Issue by makelove** [kitao/pyxel#443]
I has some ESP32 machine with oled display,arduino
MicroPython programming
How can I develop some pixel game on these tiny machines?
such as Tamagotch in Japan,Electronic pets

**Comment by cemrehancavdar** [comment]
It would be great for also micropython based pyscript. it would like instant games for web.

**Comment by kitao** [comment]
MicroPython seems interesting. However, currently, the minimum platform supported by Pyxel is Raspberry Pi. Including devices with lower specifications would require significant architectural changes and lead to certain features becoming unusable.
