### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by mehrdad-mixtape** [kitao/pyxel#445]
Hi, how can I solve this error?
![Screenshot_2023-01-26-19-02-24-56_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/71973800/214878876-23265cd0-a8f3-4982-a3bb-020b1fee8a2a.jpg)

Gamepad not supported?

**Comment by kitao** [comment]
Could you tell me which OS and web browser you use?

**Comment by mehrdad-mixtape** [comment]
> Could you tell me which OS and web browser you use?

1. I runned web-server on **kubuntu 20.04** with *python*, and I could access to my "game.html" file.
2. After that, I opened my **firefox** browser on **android 12 phone**. I clicked on my "game.html" file to play my game on browser.
I made my "game.html" file with these commands:
```bash
pyxel package ./ game.py
pyxel app2html game.pyxapp
```

**Comment by kitao** [comment]
Could you check this on the latest Pyxel? I added some code to handle this situation.

**Comment by mehrdad-mixtape** [comment]
Ok 👌 I will check ☺️

**Comment by mehrdad-mixtape** [comment]
> this

Hell yes It is working 👍🏻
