### ISSUE TITLE
Unable to save images/sounds etc...

### ISSUE THREAD

**Issue by dorianmorel** [kitao/pyxel#446]
Hello, 

I don't know if i'm in the right place to ask my question, but here's my issue : 

I am currently coding a pacman game, just for training, and i would like to create images and sounds. 

The **"pyxel edit "path/to/the/file"** command does not work on my IDE...

But I still managed to open the editor by running the cli.py file, and then in the Python Console, running **"edit_pyxel_resource()"**.

When I want to save my image, I get the following error : 
![error pyxel](https://user-images.githubusercontent.com/83545355/215714901-2d787501-4391-4512-a6c6-15bd74259992.png)

I would like to know how to fix that, or how to change the directory where the file is saved, if possible...

Thank you in advance.

EDIT : I managed to "create" music thanks to strings with pyxel.sound(x).set(), but I would like to create and save musics in the Music Editor ahah

**Comment by km19809** [comment]
> The "pyxel edit "path/to/the/file" command does not work on my IDE...
What happened exactly? What IDEs did you use? 
The error occurred because cli.py was executed with the wrong argument.
`pyxel edit` should work, and if it does not, we should fix it.
I do not recommend importing the `cli.py` directly.

**Comment by kitao** [comment]
I don't have detailed information about the situation, and since Pyxel has been updated to version 2 with significant internal changes, I will close this issue.
