### ISSUE TITLE
Feature request: Screen content

### ISSUE THREAD

**Issue by matteoturini** [kitao/pyxel#447]
I propose an API to read and write the entire screen's color data, to allow better optimized code for effects and drawing different objects. 

```py
# Draw to screen an entire frame
pyxel.fset(int[][])
# Get the entire contents of the frame
pyxel.fget(): int[][]
```

This way more effects could be created, like glitching effects, warping and distorting the screen, and much more.

**Comment by kitao** [comment]
I agree with you to add an less overhead interface to access raw data of image/screen.

Regarding the function names and the type of returned value, I'd like to hear the opinions of various people.
"fget" looks like file operation function and native c pointer type can be better python array.
We also need to think about how to convert Rust's two-dimension Vec with as little overhead as possible.

**Comment by matteoturini** [comment]
Maybe this?

```py
# Draw to screen an entire screen
pyxel.sset(int[][])
# Get the entire contents of the screen
pyxel.sget(): int[][]
```

**Comment by merwok** [comment]
What if the screen could be mapped to an `Image` ?

**Comment by matteoturini** [comment]
Like mapping the screen to image -1 or something along those lines?

**Comment by matteoturini** [comment]
Actually, that wouldn't work, images have a size of 256x256.

**Comment by kitao** [comment]
Screen is an instance of Image class and has the same methods of it.
So you can use Image class methods like this:
``pyxel.screen.pset(1, 1, 1)``

**Comment by kitao** [comment]
In Pyxel 1.9.13, ``data_ptr`` method is added to the Image class.

You can get the pointer to data like this:
```python
ptr1 = pyxel.tilemap(0).data_ptr()
ptr2 = pyxel.screen.data_ptr()
```

The type of pointer is POINTER(c_ubyte). So you can also make Numpy array by using it.

**Comment by matteoturini** [comment]
Wow, very nice. Can you write to that data pointer?

**Comment by kitao** [comment]
Please check new example, https://github.com/kitao/pyxel/blob/main/python/pyxel/examples/13_bitmap_font.py
