### ISSUE TITLE
Is there a Tetris example named “Pytris”?

### ISSUE THREAD

**Issue by malespiaut** [kitao/pyxel#448]
![2023-02-19_14-58](https://user-images.githubusercontent.com/76531574/219953147-4f580773-d42e-4df5-9161-065b387dd229.png)

Everything is in that picture.

**Comment by DiddiLeija** [comment]
As far as I know, there's no such thing like that, at least in the pyxel repo :man_shrugging:

**Comment by merwok** [comment]
The picture looks like one of these bots that generate more or less real-sounding replies to any question, so you can’t expect the contents to make sense or be accurate.

**Comment by kitao** [comment]
Why don't you check Pyxel User Examples page?
At least, there are two tetris clones.

https://github.com/kitao/pyxel/wiki/Pyxel-User-Examples

**Comment by malespiaut** [comment]
Hello,

Just to clarify for the curious: this issue was indeed made to be taken as a joke. I was pleasantly surprised that ChatGPT could come off with an example using pyxel that seemed possible.

Thank you @kitao for pointing the Pyxel User Examples page, I was unaware of it.

Best regards.
