### ISSUE TITLE
Cannot operate when embedding iframes

### ISSUE THREAD

**Issue by k0range** [kitao/pyxel#449]
When embedding a Pyxel game in an iframe, if you focus on another element and then focus again on the game in the iframe, the game will become inoperable.
However, the game can be operated only when the bottom part of the iframe is focused.
![2023-02-20_20h28_28](https://user-images.githubusercontent.com/93308122/220097713-e63a8ec2-7cea-4ba9-9e29-a9e70f8fe54d.png)

## Reproduction procedure
1. access the HTML code below to start the game in the iframe.
2. When the game loads, focus on the `<p>` element.
3. When you focus on the game in the iframe again, the game is not operable.

## Code that caused the problem
This is the code that embeds 30SecondsOfDaylight in Examples.
This code using Bootstrap.
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
        <title>Pyxel Test</title>
    </head>
    <body>
        <div class="container mt-4 mx-5 px-5 w-75 mx-auto">
                    <div class="ratio ratio-4x3" id="game">
                        <iframe class="rounded" src="https://kitao.github.io/pyxel/wasm/examples/30SecondsOfDaylight.html" frameborder="0"></iframe>
                    </div>
                <p>TEXT TEXT TEXT TEXT</p>
        </div>
    </body>
</html>
```

## Execution environment
Windows 11, Firefox 109.0.1

**Comment by km19809** [comment]
This is perfectly normal.
First, only [focused elements can fire `keydown` events](https://developer.mozilla.org/ko/docs/Web/API/Element/keydown_event). (See the `target` row.)
So, the game cannot detect any key event without focus.
Second, <canvas> is not focusable by default. (Check [this table](https://allyjs.io/data-tables/focusable.html) of focusable elements.)
In other words, you cannot focus on <iframe> by clicking <canvas>.
In your example, <canvas> takes the most area of <iframe>:
![image](https://user-images.githubusercontent.com/20869932/222455277-38a8ce71-4c14-49c2-ba91-4f650620ef8e.png)
So, you have to click the bottom of <iframe> to focus on it.
