### ISSUE TITLE
Some elements are drawn partially

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#45]
https://github.com/kitao/pyxel/issues/25#issuecomment-410445049

**Comment by kitao** [comment]
![image](https://user-images.githubusercontent.com/678802/43867022-bea1fcac-9ba2-11e8-9e36-c3c6ff7ed6ff.png)

@matju Other examples works well?

**Comment by matju** [comment]
Sorry to be a pain! Let me test out the other examples...

Example 1 shows the logo but no flashing text
Example 2 looks Ok as far as I can see...
Example 3 - see above
Example 4 plays some sounds but doesn't write any text to the screen (see screenshot)
![pyxel-180809-001049](https://user-images.githubusercontent.com/42091194/43867232-c63a3fb8-9b68-11e8-8870-abd6e7e6afb0.png)
Example 5 prints the colours without any text (see screenshot)
![pyxel-180809-001154](https://user-images.githubusercontent.com/42091194/43867262-e47558f0-9b68-11e8-96f3-393ebae7918b.png)

**Comment by kitao** [comment]
@matju Thank you!
What I don't understand most is that only small circles are drawn and on the other hand, all `pix` are not drawn. Those commands don't use texture image. So maybe they are caused by specific size, position, or timing.
I'll continue to investigate...

**Comment by kitao** [comment]
Pyxel has been updated a lot, so please tell me again as a new issue if the same problem occurs in the latest version.
