### ISSUE TITLE
Poor performance when porting TIC-80 code to Pyxel

### ISSUE THREAD

**Issue by malespiaut** [kitao/pyxel#450]
Hello,

As a learning exercise, I've decided to port a TIC-80 game to Pyxel.

I've chosen the game [“star travel” by visy](https://tic80.com/play?cart=3154), and I came up with this code:

```python
import math
import pyxel
import random


class App:
    def __init__(self):
        # Initialize variables
        self.t = 0
        self.x = 96
        self.y = 24
        self.stars = []
        self.starcount = 1024
        self.camera = {"x": 0, "y": 0}
        self.min_z = 15
        self.max_z = 50
        self.delta_time = 0
        self.previous_time = 0

        # Create stars
        for i in range(self.starcount):
            self.stars.append({
                "size": 2,
                "x": random.random() * 320,
                "y": random.random() * 128,
                "z": 32 * random.random() * (self.max_z - self.min_z) + self.min_z,
                "x_rotation": 0,
                "y_rotation": 0
            })

        # Initialize Pyxel
        pyxel.init(240, 136, title="Particle test", fps=60)
        pyxel.run(self.update, self.draw)

    # Get current time
    def time(self):
        # Number of frames times the duration of a frame in milliseconds
        return pyxel.frame_count * 1/60

    # Update function
    def update(self):
        # Calculate time delta
        self.delta_time = self.time() - self.previous_time
        self.previous_time = self.time()

        # Quit if Q is pressed
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

    # Draw stars
    def draw_stars(self):
        camera_x_offset = -128
        camera_y_offset = -64
        camera_zoom = 5 + math.cos(self.time() * 0.0001) * 8

        # Draw each star
        for i in range(self.starcount):
            # Calculate star angle
            angle = math.cos(self.time() * 0.0001 + math.sin(self.time() * 0.0001) + self.stars[i]["z"] * 0.004) * math.pi
            sin = math.sin(angle) * camera_zoom
            cos = math.cos(angle) * camera_zoom

            # Calculate star position and size
            self.stars[i]["x_rotation"] = ((camera_x_offset + self.stars[i]["x"]) * cos - (camera_y_offset + self.stars[i]["y"]) * sin) - camera_x_offset
            self.stars[i]["y_rotation"] = ((camera_y_offset + self.stars[i]["y"]) * cos + (camera_x_offset + self.stars[i]["x"]) * sin) - camera_y_offset
            self.stars[i]["z"] = (self.stars[i]["z"] - self.delta_time * 0.1) % 256
            proj_z = self.stars[i]["z"] / self.max_z
            star_position = {"x": (128 - self.stars[i]["x_rotation"]) / proj_z, "y": (64 - self.stars[i]["y_rotation"]) / proj_z}
            star_size = self.stars[i]["size"] / proj_z

            # Draw star
            pyxel.elli(128 + star_position["x"] - star_size / 2, 64 + star_position["y"] - star_size / 2, star_size, star_size, math.floor(16 - self.stars[i]["z"] / 32))

    # Draw function
    def draw(self):
        pyxel.cls(0)
        self.draw_stars()


# Start the app
App()
```

While the code works, it quickly hangs and uses maximum CPU.

**Comment by km19809** [comment]
This will perhaps `Arc<Mutex<T>>` problem.
In pyxel, many types use `Arc<Mutex<T>>` (via `shared_type!` in utils).
However, `Arc<T>`, the "atomic" reference counter, is more expensive than `Rc<T>`.

For each `pyxel.elli()` function call, the function locks the screen to modify it.
Because we call it 60 * 1024 = 60144 times per second, it can be a HUGE performance burden. 

Of course, this is my hypothesis. I need to verify it by benchmarking it.
But, pyxel might need a more efficient way to draw elements.

**Comment by km19809** [comment]
In a web browser, it gets slower and slower at each frame.
![image](https://user-images.githubusercontent.com/20869932/222641055-a51d49ae-28ab-45dc-9e5b-a7a690867df8.png)
I haven't figured it out yet, but something in the loop hangs.

![image](https://user-images.githubusercontent.com/20869932/222647175-8a4cd01f-0441-42eb-ab9d-c27bfe226f00.png)
Another weird thing is its pattern.
The drawing time continually grows, then suddenly drops.

I have to examine it further.

**Comment by malespiaut** [comment]
Thank you for your investigation. I'm eager to see what you can find. Hopefully this helps uncovering some performance issue in Pyxel, and not in the code I've written.

**Comment by malespiaut** [comment]
@km19809 are there any news on that situation?

**Comment by km19809** [comment]
@malespiaut 
Not much. 
I am sorry to say but I spent a hard time these days.
I enrolled in a Ph.D. degree program this year, so I barely examined this issue.
What I found is, it still has a performance issue when I tried to "buffer" the draw calls.
Instead of acquiring the Mutex lock each time, I draw all the calls in the buffer and then copy it to the screen once in a frame.
Although the time acquiring the lock is reduced, it cannot draw the stars.
I should perform more thorough benchmarks and find out how other frameworks work.
However, as I mentioned, it is not easy for me... 😂

**Comment by kitao** [comment]
Certainly, there is some overhead with Mutex, but in Pyxel, we use the lightweight Mutex from the parking_lot crate, which minimizes this load. On my machine, even drawing 100 times more stars (102,400 in total) in this code does not cause it to stop functioning.

In this code, the line star_size = self.stars[i]["size"] / proj_z involves division even when proj_z is almost zero, resulting in extremely large radii for ellipses, like 1 or 2 million, which can cause the program to stop working.

Unfortunately, in Pyxel, drawing many ellipses with a radius of 2 million significantly slows down the rendering speed.
