### ISSUE TITLE
Cannot Load Pyxel Editor Resources

### ISSUE THREAD

**Issue by AufNoder** [kitao/pyxel#451]
As i said in the caption, i cannot load the files i made in pyxel editor. 

I always get the error message: "pyo3_runtime.PanicException: Unable to open file"

I cant find anything that would be even remotely helpfull on google so i thought id ask here.

**Comment by km19809** [comment]
We need more context to inspect the issue.
- What command did you use?
- Which one is your OS? (Windows, Mac OS, or Linux)
- Can you tell me your pyxel version?
- Have you checked the file's existence and permission?

**Comment by AufNoder** [comment]
My Command is:

        load(
        filename: qwert.pyxres,
        *,
        image: 0,
        tilemap: False,
        sound: False,
        music: False,
        ): ...

I am on Windows and use IDLE Version 3.10.10, my Pyxel Version is 1.9.12 . Its my first time using Pyxel so im sorry for any beginner Errors. I have checked the Files Existence, i am not quite sure what you mean with permission but i looked and it should be allowed to be opened by any User or Programm on my Computer.

**Comment by merwok** [comment]
That looks like code to define a function, but it is invalid code to call one.  Can you try: `pyxel.load("qwert.pyxres")` ?

**Comment by AufNoder** [comment]
So i have used a example code from kitao himself and added `pyxel.load("qwert.pyxres")`

Now it looks like this

```
import pyxel


class App:
    def __init__(self):
        pyxel.init(160, 120, "Hello Pyxel")
        pyxel.load("qwert.pyxres")
        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

    def draw(self):
        pyxel.cls(0)
        pyxel.text(55, 41, "Hello, Pyxel!", pyxel.frame_count % 16)
        pyxel.blt(61, 66, 0, 0, 0, 38, 16)


App()
```

The Application starts but there is only blank white and puts out this:
```
Traceback (most recent call last):
  File "D:/Eigene Dateien/Desktop/test.py", line 20, in <module>
    App()
  File "D:/Eigene Dateien/Desktop/test.py", line 7, in __init__
    pyxel.load("qwert.pyxres")
pyo3_runtime.PanicException: Unable to open file 'qwert.pyxres'
```

As soon as i remove `pyxel.load` it starts just fine

**Comment by merwok** [comment]
Do you have a file named `qwert.pyxres` in your directory?

**Comment by AufNoder** [comment]
Im not sure what you mean with that? Which directory?

I have searched for it and it is under C:\Benutzer\Marina\qwert.pyxres     (Benutzer is \Users\) if you meant that

**Comment by merwok** [comment]
So you saved the pyxres file in your home directory, the game is in your desktop directory, and you use a relative path in the code.  That can’t work!  Try moving the pyxres file next to the code.

**Comment by AufNoder** [comment]
So i put the File next to the Code File and it works! Thank you so much! ^^
