### ISSUE TITLE
Is it possible to distinguish between `pyxel run` vs `pyxel play` in the code?

### ISSUE THREAD

**Issue by brettchalupa** [kitao/pyxel#460]
I've really been enjoying learning and use Pyxel! It's intuitive and simple while being flexible. Something I've been wondering as I learn the library is if there's a way to distinguish between debug and release builds?

In the Python, is there a way to do something like this?

``` python
def draw():
    if pyxel.debug_build:
        # draw hitboxes
```

Checking if the current running game is via `pyxel run` or `pyxel play` would be great for assisting the game development process. I'd like to use it to add an invincibility toggle, display hitboxes, and quickly modify game info that I don't want players to have but would make it easier to make the game.

I searched around and couldn't find anything like this. If it doesn't exist, I'd be happy to help contribute something along these lines. Thanks!

**Comment by brettchalupa** [comment]
I figured out a solution that works for me and accomplishes what I'm hoping for, so I'm going to close this out. Because `pyxel run` and `pyxel watch` can have a script specified, I just made two entry points into the game and change which one I run/use for building. Example: `pyxel run dev.py` while working on the game and then `pyxel package . main.py` to package the game.

in `main.py`:
``` python
import game

game.Game()
```

in `dev.py`:
``` python
import game

game.Game(True)
```

in `game.py`:
``` python
import pyxel
WIDTH = 120
HEIGHT = 160
FPS = 60
TRANSPARENT_COLOR = 0

dev_mode = False
render_dev_mode = False

class Game:
    def __init__(self, _dev_mode = False):
        global dev_mode
        dev_mode = _dev_mode
        if not dev_mode:
            global render_dev_mode
            render_dev_mode = False
        pyxel.init(WIDTH, HEIGHT, "PYXSHMUP", FPS)
        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

        if dev_mode and pyxel.btnp(pyxel.KEY_0):
            global render_dev_mode
            render_dev_mode = not render_dev_mode

    def draw(self):
        pyxel.cls(0)
        if render_dev_mode:
            pyxel.text(0, 0, "dev mode", 4)
```

I don't know Python very well, so I can't say if this code follows standards, but it seems to be working from experimenting and running it.

**Comment by merwok** [comment]
That’s one way of doing it!

Only thing is that using globals is generally discouraged, and not needed here at all since you have made a class for the Game.
