### ISSUE TITLE
How to use with an gamepad

### ISSUE THREAD

**Issue by BloomyInDev** [kitao/pyxel#465]
I discovered Pyxel not that long ago, but i didn't understand how to use the joystick from an gamepad (i've used buttons and dpad actually)
Can someone help me ?

**Comment by brettchalupa** [comment]
@BloomyInDev happy to help ya' out! So you can use `pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTX)` and `pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTY)` to get the analog value of the left stick (swap `LEFT` with `RIGHT` to get the right stick value). For a Sony DualShock 4, this returns a number between about -32000 and positive 32000, dependent on the direction of the stick and how far it is pressed. You can then use that value, along with checking for a deadzone, to determine whether or not to register an input. For example, here's a simple program that outputs the value and moves a rectangle around:

``` python
import pyxel

class App:
    def __init__(self):
        pyxel.init(160, 120)
        self.x = 10
        self.y = 10
        self.speed = 5
        self.deadzone = 2000
        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_Q):
            pyxel.quit()

        if pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTX) > self.deadzone:
            self.x += self.speed
        elif pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTX) < -self.deadzone:
            self.x -= self.speed

        if pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTY) > self.deadzone:
            self.y += self.speed
        elif pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTY) < -self.deadzone:
            self.y -= self.speed

    def draw(self):
        pyxel.cls(0)
        pyxel.rect(self.x, self.y, 20, 20, 11)
        pyxel.text(60, 60, "X: " + str(pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTX)), 2)
        pyxel.text(60, 72, "Y: " + str(pyxel.btnv(pyxel.GAMEPAD1_AXIS_LEFTY)), 2)

App()
```

And here's a video of what it produces showing the values and the rectangle moving:

https://user-images.githubusercontent.com/928367/234116475-a62e38df-fcdf-440c-b257-3325c3e6b97b.mov

Hope that helps! `pyxel.btnv` (button value) is the secret to the puzzle here, I think.

**Comment by BloomyInDev** [comment]
Thanks you !
I think it would be better to add this to the documentation !
Maybe i will make an pr to add this part to the documentation
