### ISSUE TITLE
pyxel app2exe doesn't build correctly

### ISSUE THREAD

**Issue by BloomyInDev** [kitao/pyxel#468]
Pyxel seems to compile into an exe file but it wont launch
There is the error when i execute the exe file that appear quickly (can be seen if launched from cmd). It is
> Traceback (most recent call last):
>   File "game.py", line 1, in <module>
> ModuleNotFoundError: No module named 'pyxel'
> [33164] Failed to execute script 'game' due to unhandled exception!

How can i fix that ?

**Comment by BloomyInDev** [comment]
I search a little and found the problem, pyinstaller does not include pyxel in the package so i need to add it as an hidden import
Here is my command to compile the game
> pyinstaller --noconfirm --onefile --windowed --name "Name of the file" --hidden-import "pyxel" --add-data "./resources.pyxres;."  "./main.py"

I might add that i run that on windows 10

**Comment by kitao** [comment]
I tried the feature on my environment (Mac) and it worked.
So could you try it with Pyxel's megaball.pyxapp example like `pyxel app2exe megaball.pyxapp`?

**Comment by BloomyInDev** [comment]
On my laptop (with a session name with space, my biggest error when i configured it), i have another error that doesn't allow it to build.

> (venv) C:\jeualautre\pyxel_examples>pyxel app2exe megaball.pyxapp
> 944 INFO: PyInstaller: 5.10.1
> 944 INFO: Python: 3.11.1
> 973 INFO: Platform: Windows-10-10.0.19045-SP0
> 976 INFO: wrote C:\jeualautre\pyxel_examples\XOX.spec
> 984 INFO: UPX is not available.
> script 'C:\Users\XOX' not found
> 
> (venv) C:\jeualautre\pyxel_examples>

(My session name is something like 'XOX OXO' that i used here to not share my name)

**Comment by kitao** [comment]
@BloomyInDev In 1.9.17, app2exe is changed to support a virtual environment. Please try it.
