### ISSUE TITLE
`nseed` function not working

### ISSUE THREAD

**Issue by nifouprog** [kitao/pyxel#469]
The[ `Perlin::set_seed`](https://docs.rs/noise/0.7.0/noise/struct.Perlin.html#method.set_seed) function used in the `nseed` function returns a new `Perlin` instance which is not assigned to the `Math` instance, so the Perlin seed is not really changed.  https://github.com/kitao/pyxel/blob/779dc3ff29b01289cf3217610e6fdbd947cbc027/crates/pyxel-core/src/math.rs#L79  To fix it, it is possible to use an approach similar to the `rseed` function like:

```rust
fn nseed(seed: u32) {
    let instance = Math::instance();
    instance.perlin = instance.perlin.set_seed(seed);
}
```

Or using the latest `noise` version (0.8.2):

```rust
fn nseed(seed: u32) {
    Math::instance().perlin = Perlin::new(seed);
}
```

**Comment by kitao** [comment]
Thank you for your report.
If the easiest way to fix it is updating the version of the noise crate, I'll do it.
Is my understanding right?

**Comment by nifouprog** [comment]
Yes, it is the cleanest way to keep using a one-liner. However, another small change is required because the call to `Perlin::new` needs to be replaced with `Perlin::default`
I'll update the pull-request

**Comment by kitao** [comment]
I merged your code and found the latest noise crate didn't work for WASM. So I downgraded the version of noise crate.
Could you check it works? It's on the develop branch (not on the master branch). Thank you.

**Comment by nifouprog** [comment]
Thank you for quickly fixing this issue!
