### ISSUE TITLE
Unable to run updated game with web launcher

### ISSUE THREAD

**Issue by lynn2910** [kitao/pyxel#471]
Hello, for a school project, my teacher needs a link to let people try the game, using the web launcher.

But, after a first test with the web launcher, my friends and I updated the game, but when we generate the link with the web launcher (https://kitao.github.io/pyxel/wasm/launcher/), the game is not updated!

First, we thought that there was an error while uploading the update, so we updated the repository again and cloned the repository afterwards to check, and the code is correct.
But the update is not sent to the web launcher...

The source code :
https://github.com/Sedorikku1949/PyxelCuvier/blob/main/6_metres_a_3/ndc.py 

Does anyone know how to solve this problem?

**Comment by kitao** [comment]
Pyxel Web Launcher doesn't keep any code. It just downloads code every time.
So if the code didn't looks updated, it's because of the browsers' cache feature.
For example, If you use Chrome, you can disable it from its developer menu.

But I also would like to disable browsers' cache feature except Pyxel and Pyodide code.
So it would be welcome if there's any idea to realize it.

**Comment by Sedorikku1949** [comment]
I tried to clear the browsers's cache, but now i get this error
```py
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 3, in 
  File "/lib/python3.11/site-packages/pyxel/cli.py", line 166, in run_python_script
    runpy.run_path(python_script_file, run_name="__main__")
  File "", line 291, in run_path
  File "", line 98, in _run_module_code
  File "", line 88, in _run_code
  File "ndc.py", line 3, in 
    from background import Background
ModuleNotFoundError: No module named 'background'
```
(but i work perfectly on my computer)

**Comment by merwok** [comment]
How do you export your game to HTML?  (full command)
You need to pass the right options so that all your modules are included.

**Comment by Sedorikku1949** [comment]
> How do you export your game to HTML?  (full command)
> You need to pass the right options so that all your modules are included.


What do you mean by exporting the game to html ? 
In the documentation, it is said that we can put the source code in a repository and use the link to the startup file, so this is what I did...

**Comment by merwok** [comment]
OK, you never said how you were making the game playable in HTML!
Error reports need to include all relevant info so that people can help.

The `ndc` module you linked too does not have imports from a module named `background`.
Can you provide the actual link of the game?

**Comment by kitao** [comment]
Since there has been no change in the situation and I haven't received similar reports (there are many web launcher users), this matter will be closed. If the same situation occurs with Pyxel 2+, please raise a new issue.
