### ISSUE TITLE
Multiple Gamepads

### ISSUE THREAD

**Issue by csevier** [kitao/pyxel#476]
I am just curious, from a quick glance at the code it would appear that only 2 gamepads are supported. Is this the case?

**Comment by csevier** [comment]
Id also like to add questions regarding custom input devices, things like trackballs/joysticks, could this be possible? I believe they are supported by SDL if I am not mistaken.

**Comment by kitao** [comment]
Pyxel 2+ supports 4 gamepads. And regarding trackball/joystick support, it is difficult to implement because I don't have those input devices.
