### ISSUE TITLE
[WASM] Unable to use the keyboard when the graphic editor is running

### ISSUE THREAD

**Issue by laurentabbal** [kitao/pyxel#479]
Hi,

On a webpage, I'm trying to have the graphics editor and a form with an  input side by side. But when the editor is open, the keyboard no longer works. I can't write in the input.
Is there a way to activate the keyboard when trying to write in the input?

Laurent

**Comment by cperrod** [comment]
Same problem here, but with a Pyxel script running in a div side by side a Codemirror editor...no keyboard once the script running...

**Comment by kitao** [comment]
The only thing Pyxel does for key inputs on browsers is preventing from Ctrl+S input and other keys are not affected.
https://github.com/kitao/pyxel/blob/main/wasm/pyxel.js#L404

I think SDL2 used in Pyxel captures the key inputs.

**Comment by kitao** [comment]
Let me close this issue because there is nothing I can do from the Pyxel side.
