### ISSUE TITLE
3D library now available for pyxel

### ISSUE THREAD

**Issue by marespiaut** [kitao/pyxel#48]
*This is **not** a bug report!*

Just a quick note to tell you that I've ported @josefnpat [3D library for PICO-8](https://github.com/josefnpat/picocam) to Pyxel.

**pycocam** is now available at https://github.com/marespiaut/pycocam under the public domain.

Best regards!

**Comment by timbledum** [comment]
I'm still boggling on how this + the demo can fit in 100 lines of code.

**Comment by marespiaut** [comment]
@timbledum I've only made a translation from Lua to Python, so I'm not the original designer of this code. I don't know if it can fit in less lines than that.

Aside from that, you'll see that the library is only focusing on translating points from 3D to 2D. So, starting from that, making lines is not difficult, you just have to translate a couple of 2 points from 3D to 2D.

The library doesn't do anything else, that's why it's so short.

**Comment by paulsheridan** [comment]
This is spectacular!  Awesome work!

**Comment by kitao** [comment]
Thank you for translation!

**Comment by josefnpat** [comment]
Oh cool - can someone post a screenshot?
