### ISSUE TITLE
Show(), displaying the bottom right of the screen incorrectly

### ISSUE THREAD

**Issue by tmetzler** [kitao/pyxel#481]
I was playing around with Archimedean spirals when, due to performance issues, I wanted to use the show() function. It displayed the image fine, except for the entire bottom right of the screen, where the x and y coordinates were flipped.

I then used run() to do the same thing but passing update() and draw(), and it worked seamlessly. Please fix this, this is my code:

import pyxel

polar_coods = []
coords = []
current_dot = 0
n_dots = 1000000
arc_angle = 3.1415926
between_distace = 0.1

for number in range(1, n_dots):
    polar_coods.append((between_distace*number, arc_angle*number))

for polar_coord in polar_coods:
    coords.append((polar_coord[0]*pyxel.cos(polar_coord[1]), polar_coord[0]*pyxel.sin(polar_coord[1])))

pyxel.init(500, 500, "Archimedia Spiral", 2000, pyxel.KEY_Q,)

pyxel.camera(-pyxel.width/2, -pyxel.height/2)

for coord in coords:
    pyxel.rect(coord[0], coord[1], 1, 1, 3)

pyxel.draw()

**Comment by kitao** [comment]
This code includes syntax errors and functions Pyxel doesn't support.
Please check a correct code on Pyxel 2+ and post an issue again if you still have some trouble.
