### ISSUE TITLE
Some sort of error with SDL

### ISSUE THREAD

**Issue by po-a-ai** [kitao/pyxel#484]
OS: Bodhi Linux 6.0
Python: 3.11

I tried to learn pyxel but whenever I run main.py I get this error:
```
Traceback (most recent call last):
  File "/home/cloneboy2116/Programming/Pyxel First Game/main.py", line 1, in <module>
    import pyxel
  File "/home/cloneboy2116/.local/share/virtualenvs/Pyxel_First_Game-ofts5D0t/lib/python3.11/site-packages/pyxel/__init__.py", line 1, in <module>
    from .pyxel_extension import *  # type: ignore  # noqa F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/cloneboy2116/.local/share/virtualenvs/Pyxel_First_Game-ofts5D0t/lib/python3.11/site-packages/pyxel/pyxel_extension.abi3.so: undefined symbol: SDL_Metal_DestroyView
```

_**Note: I have libsdl2-dev installed**_

**Comment by NeKroFR** [comment]
I think it's an issue with the last version of pyxel.
I solved this issue by installing the **1.9.0**:
```
pip install pyxel==1.9.0
```

Hope it will work for you too :)
@po-a-ai

**Comment by mgmalheiros** [comment]
I have tracked it down, and the symbol `SDL_Metal_DestroyView` appears in all Pyxel versions >= 1.9.8 .

Therefore, as @NeKroFR said, using an older Pyxel is a temporary workaround. At maximum version 1.9.7 should run ok:

```
pip install pyxel==1.9.7
```

It seems a new version of SDL got incorporated in Pyodide-SDL2. When you are running in an older system with older SDL2 libraries, that symbol is not found and Pyxel does not run.

It seems `SDL_Metal_DestroyView` was added in SDL 2.0.12, so ideally Pyxel should be linked to SDL 2.0.11, which would prevent such errors.

I had the same problem in older Ubuntu 18.04 (2.0.8) and 20.04 (which has 2.0.10). I solved by manually compiling and installing a newer SDL2 library on my systems.

As Ubuntu 20.04 LTS is still actively maintained, would it be possible to revert Pyxel to use an older SDL2 version, @kitao ?

**Comment by kitao** [comment]
Does the situation changed on Pyxel 2+? I took care of SDL2 version for Linux.

**Comment by mgmalheiros** [comment]
Thank you for seeing this!

I can confirm that Pyxel runs fine with current Ubuntu Jammy (22.04 LTS) version. You only need the distribution-provided **libsdl2-2.0-0** to be installed.

I will check later on an older Ubuntu version too.
