### ISSUE TITLE
Pyxel window thinks it's always on top (Linux)

### ISSUE THREAD

**Issue by paul59** [kitao/pyxel#488]
If I have a window overlapping the Pyxel editor as in this screenshot, then hold the mouse cursor in the indicated position, the music patterns can be heard. It applies when any part of any app window is overlapping, including the title bar.

I'm running MX Linux. Not sure if it's OS or Pyxel related but might be worth knowing about!

![SS-2023-07-29_19-40](https://github.com/kitao/pyxel/assets/3756822/f60f2e16-50d6-4736-8df5-3ec1440cd69f)

**Comment by DiddiLeija** [comment]
I can reproduce this on Windows, so I guess this is Pyxel-related rather than OS-related :)

**Comment by paul59** [comment]
> I can reproduce this on Windows, so I guess this is Pyxel-related rather than OS-related :)
Good. Or bad, I'm not sure which but at least it isn't just me!

**Comment by kitao** [comment]
Fixed in Pyxel 2.0.3. When focus is lost, mouse position event doesn't occur any more.
