### ISSUE TITLE
Segfault when calling `init()`

### ISSUE THREAD

**Issue by xlambein** [kitao/pyxel#49]
Hello,

Your library seems really neat!  Unfortunately, I've been unable to use it, because I get a segfault as soon as I run the `pyxel.init()` function.  Here's the minimal code that produces the segfault:
```python
import pyxel
pyxel.init(160, 120)
```
and here's the error message I get from my shell:
```
[1]    25268 segmentation fault (core dumped)  python pyxel_test.py
```

I am on Manjaro (i.e. Arch).  I have python 3.6.6 with conda, glfw-x11 version 3.2.1-1, and python-glfw version 1.7.0-1, as well as python-pyxel version 0.7.3-4 from the AUR.  I don't know what else to tell you.

Thanks in advance!

**Comment by Rutrus** [comment]
Similar issue happens to me:

```
import-im6.q16: not authorized `pyxel' @ error/constitute.c/WriteImage/1037.
./base.py: línea 3: error sintáctico cerca del elemento inesperado `160,'
./base.py: línea 3: `pyxel.init(160, 120)'
```

**Comment by Rutrus** [comment]
Something wrong happens with python3.6 (3.6.6) I installed python3.7 and it worked fine.
```
python3.7 -m pip install pyxel
```

**Comment by xlambein** [comment]
Yep that fixed it for me too, thanks!
