### ISSUE TITLE
How to import python script to run in web?

### ISSUE THREAD

**Issue by s1tf** [kitao/pyxel#490]
In my main python file I'm importing another file called `constants.py` with `import constants`. But it doesn't work when I run project in web. How can I import file properly?

The error is:

```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 3, in 
  File "/lib/python3.11/site-packages/pyxel/cli.py", line 167, in run_python_script
    runpy.run_path(python_script_file, run_name="__main__")
  File "", line 291, in run_path
  File "", line 98, in _run_module_code
  File "", line 88, in _run_code
  File "main.py", line 3, in 
    import constants
ModuleNotFoundError: No module named 'constants'
```

Web launcher: https://kitao.github.io/pyxel/wasm/launcher/?run=s1tf.test.main
Source code: https://github.com/s1tf/test/blob/main/main.py

**Comment by s1tf** [comment]
> Have you tried?
> 
> `import ./constants`

Same error. You can try it here: https://kitao.github.io/pyxel/wasm/launcher/?run=s1tf.test.main

**Comment by BloomyInDev** [comment]
I've made a game that used multiples files (like you i think), i've imported all my files with
`from constants import *`
[you can also see here](https://github.com/BloomyInDev/Dungeon-Adventure/blob/master/game/main.py)

**Comment by alderven** [comment]
> I've made a game that used multiples files (like you i think), i've imported all my files with

But does it work when you run your project in web?

**Comment by s1tf** [comment]
> I've made a game that used multiples files (like you i think), i've imported all my files with
> `from constants import *`

This would work locally.
But would it work in the web?

**Comment by kitao** [comment]
Due to the web spec's limitation, Pyxel can't download files freely without any hints.
If you would like to run Pyxel with wildcard imports, please package files as Pyxel app (.pyxapp) and run it on web.

**Comment by s1tf** [comment]
What about non wildcard import such as 

`import constants` or `from constaints import game_api`?

**Comment by merwok** [comment]
The form of the import is not the issue.
Pyxel web can only use one file, that’s it.  If you need multiple modules, make a pyxapp file and run it with the web runner.

**Comment by kitao** [comment]
@s1tf I recommend .pyxapp style, but you can tell a file to be loaded to Pyxel by calling some file-related function like this:
```python
import os
os.path.isfile("./your_module_file.py")

import your_module_file
```

**Comment by s1tf** [comment]
Thanks!
Probably worth mention it in documentation.
