### ISSUE TITLE
Con‘t Run On My Laptop,it show something error on my bash

### ISSUE THREAD

**Issue by LingYiWu015** [kitao/pyxel#491]
## when i run this on my terminal

'''
pyxel edit PYXEL_RESOURCE_FILE
'''

## it give me some mistake as below

'''
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  167
  Current serial number in output stream:  168
'''

## i try to run the basic program.like this

'''
import pyxel

pyxel.init(160,120)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)
    pyxel.rect(10, 10, 20, 20, 11)

pyxel.run(update, draw)
'''

## it give me the same error tip

![basic program error](https://github.com/kitao/pyxel/assets/141961630/3cb7af1e-53aa-4edf-a047-ad7bf3a79fc3)

![Error picture on terminal](https://github.com/kitao/pyxel/assets/141961630/da25a71e-d232-4b20-b5d5-4b4393961525)

**Comment by LingYiWu015** [comment]
i got a mistake!
i am new in python and linux,when i want to code a 2d-game for myself,i choose pyxel.but it can't run it,there are some tips below

**Comment by LingYiWu015** [comment]
# so what can i do ?

**Comment by LingYiWu015** [comment]
thank you if you can answer my question.
also thank who create this great game engine

**Comment by merwok** [comment]
Your installation of OpenGL libraries seems messed up!

**Comment by LingYiWu015** [comment]
> 您的OpenGL库安装似乎搞砸了！

Thanks for your reply,but i can't get my Personal Computer in a short time,i will try to reinstall OpenGL to see if it's still wrong
thanks again

**Comment by kitao** [comment]
This issue pertains to a specific individual environment and, as there has been no change in circumstances, it will be closed.
