### ISSUE TITLE
Support for 32 colors

### ISSUE THREAD

**Issue by musjj** [kitao/pyxel#495]
pico-8 allows up to 32 colors through an [undocumented hack](https://pico-8.fandom.com/wiki/Palette#128..143:_Undocumented_extra_colors) that ended up being officially approved by the developer.

It'd be nice if pyxel can also support 32 colors, maybe optionally through the `.pyxpal` palette file.

**Comment by kitao** [comment]
Pyxel2 which should be released this year supports 16+ colors.

**Comment by kitao** [comment]
Now you can extend the number of colors.

```python
colors = pyxel.colors.to_list()
colors *= 2 # Just doubled num of colors
pyxel.colors.from_list(colors)
```
