### ISSUE TITLE
Support for download via homebrew

### ISSUE THREAD

**Issue by Kirito139** [kitao/pyxel#499]
Would be nice to be able to download through homebrew, thus making it easier to download pyxel and stay up-to-date. [help wanted] [enhancement]

**Comment by kitao** [comment]
Yes, I have considered making Pyxel installable via Homebrew before, thinking it might be convenient. However, Pyxel depends on Rust, Python, and others, and creating a Homebrew formula for it is fairly complicated, so I decided against it.

Moreover, from an effectiveness standpoint, currently the process is:

```bash
brew install python3
pip install pyxel
```

As opposed to just reducing it to one line with:

```bash
brew install pyxel
```

Additionally, the fact that brew's Python gets installed separately from the system's Python, and that Pyxel can be updated via both pip and brew, which could confuse users, are also reasons why I decided not to proceed with this approach.
