### ISSUE TITLE
glfw.GLFWError: (65544) b'Cocoa: Failed to retrieve display name'

### ISSUE THREAD

**Issue by jin10086** [kitao/pyxel#5]
in mac 10.13.6 (17G65)
![image](https://user-images.githubusercontent.com/15347911/43376066-526ba998-93eb-11e8-927c-1325b79bfeac.png)

I find the same error 
https://github.com/glfw/glfw/issues/958

**Comment by kitao** [comment]
Well, Pyxel just call `glfw.init()` now. 
So I should wrap it with try block and  catch `GLFWError` exception?

Because I don't have the environment raises this exception. I don't know the way to handle this exception properly.

**Comment by jin10086** [comment]
hi, when i reboot my computer,the code is work...

I don't know how it happened.
