### ISSUE TITLE
Pyxel on Firefox freezes when I shrink the screen width

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#500]
Windows 10 and Firefox seem to freeze as the screen width is reduced. This problem does not occur on the same PC with browsers other than Firefox, e.g. Edge.

**Comment by salazarbarrera** [comment]
I think it is a bug from [Pyodide](https://github.com/pyodide/) more than Pyxel

![imagen](https://github.com/kitao/pyxel/assets/68821455/cedc1858-e175-42d8-a872-c422460a7dba)

Maybe calling a less minified Pyodide it could be possible to parse what's happening? Not sure if possible.

**Comment by salazarbarrera** [comment]
Can you test if this still happens to you with 2.0? I no longer have this problem.

**Comment by shiromofufactory** [comment]
I tried with Pyxel 2.0 and the problem was solved.Thanks!

**Comment by salazarbarrera** [comment]
I'm just the messenger though, @kitao is the mastermind
