### ISSUE TITLE
Freeze when rotating screen on iOS (on web)

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#501]
On iOS, when running the Pyxel application in a browser (Safari, Chrome), the application may freeze when the screen is rotated horizontally or vertically.
If background music is playing, the background music will continue to play but the screen rendering will not update.

This problem does not occur with lightweight apps, but seems to occur with heavy processing apps.

**Comment by kitao** [comment]
It worked with Pyxel 2+. So I close this issue.
