### ISSUE TITLE
Pyxel edit crashes upon cursor entering with EXC_BAD_ACCESS (SIGBUS)

### ISSUE THREAD

**Issue by shaunabanana** [kitao/pyxel#505]
I'm having trouble running the Pyxel editor. The UI is correctly displayed as long as the cursor stays outside the window bounds, and the program crashes the moment the cursor enters.

I am using the system-provided Python 3.9, and used the following commands:
```
sudo python3 -m pip install -U pyxel
pyxel edit test.pyxres
```

Here is the full crash report:
[crash-report.txt](https://github.com/kitao/pyxel/files/13624504/crash-report.txt)

**Comment by merwok** [comment]
(Warning against using sudo pip and risking breaking your system: https://stackoverflow.com/questions/29310688/sudo-pip-install-vs-pip-install-user/49342241#49342241)

**Comment by shaunabanana** [comment]
Hi @merwok ! Thank you for pointing this out! In this case, I think maybe it makes sense to remove the following from README.md?

> If you use Python3, which is installed by default on Mac, please add `sudo` to the beginning of the above command to enable `pyxel` command.

I'm not sure why `sudo` is required — presumably for installing the command script into `/usr/local/bin`?

I have also tried without `sudo`, but the result is the same: `[1]    46844 bus error  pyxel edit test.pyxres` in terminal, and a crash report similar to the one attached above.

**Comment by shaunabanana** [comment]
Just tested the latest version (2.0.1), and the issue persists.

**Comment by kitao** [comment]
I think so. I also think this issue is nothing to do with that you installed Pyxel with `sudo`.

This is just a guess, but it seems similar to the pattern that occurs when multiple versions of the UI Framework and related drivers are mixed up when macOS is upgraded. If possible, you might try a clean install of the latest version of the OS.

**Comment by shaunabanana** [comment]
I see. As I'm working on other projects at the same time, it's a bit hard to do a clean reinstallation. However, I tried setting up a fresh VM, and indeed the issue was gone. It is quite possible that what you said was the case.

I'll mark this issue as closed in the meantime and try reinstalling when I can. Thank you again @merwok and @kitao for your help!
