### ISSUE TITLE
Pyxel 2.0.0 displays only black screen on Raspberry Pi

### ISSUE THREAD

**Issue by benjaminbellamy** [kitao/pyxel#507]
When running any program, such as 01_hello_pyxel.py, on Raspberry Pi (Raspberry Pi Zero 2 W  running 2023-12-11-raspios-bookworm-arm64-lite)  it shows only a black screen and the cursor.  
No error message is shown.

It works like a charm on the same RPi with pyxel 1.9.18.

See attached screencast.

https://github.com/kitao/pyxel/assets/1984208/ab26b95f-b37a-431d-bfd7-454e99d6e0f4

**Comment by kitao** [comment]
It seems that OpenGL ES doesn't work but I'm not sure because I don't have a Raspberry Pi environment.
Could you check key inputs works or not? You can check it by pressing ESC while an example is running.

And is there any settings to use OpenGL ES 2.0 and its GLES shaders for Raspberry Pi? The difference between Pyxel2 and Pyxel1 is using OpenGL (ES) shaders.

**Comment by benjaminbellamy** [comment]
Hello @kitao!
Key input do work indeed.
Regarding OpenGL ES 2.0 I have no idea, I'll have a look.

**Comment by benjaminbellamy** [comment]
I just tested on a Raspberry Pi 4 running raspios-bookworm-arm64-lite with pyxel-2.0.1 and it works fine.

**Comment by kitao** [comment]
Thank you for the detailed investigation!
I don't have a Raspberry Pi environment, so this is really helpful.

**Comment by benjaminbellamy** [comment]
I'll try to nail it by running some tests on all possible configurations this week-end. 
So far it does not work on RPi zero 2 W running Bookworm lite 64 bits but it works without a glitch on RPi 4 running Bookworm lite 64bits.

**Comment by benjaminbellamy** [comment]
I though the problem came from the _lite_ version but it does not: I could not make it work with the “Raspberry Pi OS with desktop” either (see screenshot below).

![2023-12-18-132527](https://github.com/kitao/pyxel/assets/1984208/092d2f4b-a33c-42b2-b91f-88ae0cbc9de5)

So there is a problem with the Raspberry Pi Zero 2 W that does not occur with the Raspberry Pi 4.

**Comment by benjaminbellamy** [comment]
I also tried both Raspberry Pi OS Bookworm (Debian 12) and Raspberry Pi OS Bullseye (Debian 11) but got the exact same results.

**Comment by kitao** [comment]
Could you try Pyxel 2.0.6? I modified OpenGL/GLES-related code. It may improve GLES handling.

**Comment by benjaminbellamy** [comment]
I will try!

**Comment by kitao** [comment]
Is there any update on the situation?

**Comment by kitao** [comment]
Let me close this issue because I already made the code fix and there is no updates.
