### ISSUE TITLE
palette only 0..254 (v2.0.2)

### ISSUE THREAD

**Issue by uu-nn** [kitao/pyxel#510]
in v200 palette is working right but break in v202 and v203,
set and access pyxel.colors[255] return range error

**Comment by kitao** [comment]
There are two reasons for this. The first is that the maximum color count for GIFs is 256, and subtracting one for transparency leaves 255 colors as the limit for creating highly compressed GIF movies. The second reason is that when performing high-speed drawing using OpenGL/ES shaders on devices like the Raspberry Pi, using an excessively large palette size is not preferable.

The ability to change the number of colors in Pyxel is not officially recommended. It's considered a hidden feature for advanced users to showcase interesting techniques.

By the way, in version 2.0.0, there was no error handling implemented yet for situations where a large number of colors were specified.

**Comment by uu-nn** [comment]
ok thanks for clarification.
