### ISSUE TITLE
Pyxel Editor crash when selecting Music Editor

### ISSUE THREAD

**Issue by fgallaire** [kitao/pyxel#512]
```
  File "/home/fgallaire/.local/lib/python3.10/site-packages/pyxel/editor/music_editor.py", line 96, in get_field
    return music.seqs[index]
IndexError: list index out of range
```

**Comment by kitao** [comment]
Let me know your platform, pyxel version, and what kind of operations you did from booting the Pyxel Editor so that I can reproduce the situation.

Though my current estimation is that old version of Pyxel opened newer version's resource data.

**Comment by fgallaire** [comment]
Pyxel 2.0.4
Ubuntu and Debian

**Comment by kitao** [comment]
Didn’t load any resource file?

**Comment by kitao** [comment]
Now I reproduced the error. Started fixing it.

**Comment by kitao** [comment]
Fixed. Please try Pyxel 2.0.5.

**Comment by fgallaire** [comment]
Works great !
