### ISSUE TITLE
command for the terminal didn't work (pycharm)

### ISSUE THREAD

**Issue by Taaniyu** [kitao/pyxel#519]
On pycharm I try to type "pyxel edit" and the link of the file but it say that "pyxel isn't recognized at a command" I tried every path at every pyxel files I have and it didn't work

**Comment by kitao** [comment]
What happens when you try `python3 -m pyxel` or `python -m pyxel`?

**Comment by kitao** [comment]
Let me close this issue because the information has not been updated.
