### ISSUE TITLE
Slide sound effect only works once

### ISSUE THREAD

**Issue by fgallaire** [kitao/pyxel#520]
```
pyxel.sounds[0].set("e2", "p", "3", "s", 20)
pyxel.play(0, pyxel.sounds[0])
pyxel.play(0, pyxel.sounds[0])
```

The sound is played "Slide" only once then is played "None".

**Comment by fgallaire** [comment]
When playing an other sound with "Slide" effect it doesn't work neither. Only changing the channel makes the "Slide" effect  works once.

**Comment by kitao** [comment]
The effect of the slide effect is to smoothly connect the sound that was played before with the next sound. Therefore, the effect will not occur unless two pitches are played. (Since there is no previous sound on the first time, it will slide from the lowest pitch.)

**Comment by fgallaire** [comment]
Thanks for the explanation. As it's not obvious, maybe something to add in the documentation ?

**Comment by kitao** [comment]
In the latest Pyxel, the slide effect works only for the second and later notes now.
I'll think about modifying documents when I remake the official API reference (it's the next major change in  Pyxel 2.x)
