### ISSUE TITLE
`pyxel.sqrt(0)` returns 1.7976931348623157e+308

### ISSUE THREAD

**Issue by DiddiLeija** [kitao/pyxel#526]
At least on the latest version of Pyxel (`2.0.7`), `pyxel.sqrt(0)` returns `1.7976931348623157e+308` instead of 0, which seems like a bug. To reproduce this issue, run:

```python
import pyxel

pyxel.init(8, 8, "Test")
# ...
print(pyxel.sqrt(0))
```

This bug was pointed previosly on Discord, but I opened this ticket to track the bug progress :wink:

**Comment by kitao** [comment]
Sorry. Maybe I'm putting this code in by mistake somehow. I will address this in the next version.

**Comment by DiddiLeija** [comment]
Thank you @kitao!
