### ISSUE TITLE
Air hockey example created from pyxel!

### ISSUE THREAD

**Issue by prashantgupta24** [kitao/pyxel#53]
Great library! I created an air hockey game as an example [here](https://github.com/prashantgupta24/python-air-hockey)

![image](https://user-images.githubusercontent.com/9909241/44077360-463dbb16-9f58-11e8-8e96-aa4a2818fd5c.png)

**Comment by timbledum** [comment]
Ahh awesome! I just started working on a pong style game too – just got collision detection working and was about to start on scoring, etc.

I wonder if we should create a repo just for showcasing games and anyone can do a pull request to get their game in there? A folder per game, with an index in the readme?

**Comment by paulsheridan** [comment]
If it helps, I've got some relatively straightforward collision detection going on a little side scroller.  I'm working on refactoring so some of the code is still a little messy: https://github.com/paulsheridan/pyxel-projects/tree/master/side_scroller

**Comment by kitao** [comment]
@prashantgupta24 I created the wiki(https://github.com/kitao/pyxel/wiki) and introduced your sample.
Thank you very much!
@paulsheridan I haven't tried your sample yet, but feel free to add link to your project in the wiki!
