### ISSUE TITLE
pyxel run of .pyxapp file results in "no such file: 'filename.pyxapp.py'

### ISSUE THREAD

**Issue by k-laig** [kitao/pyxel#534]
On Debian 12 in Fish Shell. pyxel run .py files does work.

**Comment by DiddiLeija** [comment]
To open a `.pyxapp` file, you should use `pyxel play` instead of `pyxel run` (which seems to be made for `.py` files) ;)

Seems like this is no longer mentioned in the docs (that should be the reason of your issue), so this is more a documentation issue rather than a bug.

**Comment by k-laig** [comment]
Oh yeah, tysm.
Should I open another issue to ask for docs addition?
