### ISSUE TITLE
Display Glitch with Horizontal Green Lines in ‘Hello Pyxl’ Program

### ISSUE THREAD

**Issue by herrerawilliamh** [kitao/pyxel#537]
![image](https://github.com/kitao/pyxel/assets/82005431/4fe92e1b-abd7-4c16-a4e1-18998ffad871)
I have an installation of Windows 11 Pro, when trying to launch the simulation, this pixelated and green screen appears.
My computer is an Acer Nitro 5, GTX 1650.

**Comment by Vectorredz** [comment]
Hello same issue here! how do one fix this??

**Comment by herrerawilliamh** [comment]
> Hello same issue here! how do one fix this??

I work to find a solution for this fix.

**Comment by Vectorredz** [comment]
> > Hello same issue here! how do one fix this??
> 
> I work to find a solution for this fix.

I fixed it already, I noticed that the problem was not from pyxel at all but rather revolving to my graphics driver/display drivers. I just reinstalled my dedicated and integrated display drivers (be wary of deleting intel UHD).
