### ISSUE TITLE
Packaging a pyxel game

### ISSUE THREAD

**Issue by paulsheridan** [kitao/pyxel#54]
Hi again,
I hope this is an acceptable place for a question like this, without a Pyxel related forum, it's the only place I know to ask other Pyxel devs:

Is there a reliable means of packaging a pyxel game for distribution/sharing with people who may not have python environments already set up?

I'd like to share my work but have had nothing but trouble with pyinstaller and py2app.  It seems that glfw's use of subprocess causes the issue.  I'm happy to elaborate further, but mostly I'm curious if anyone has successfully created a sharable build.

**Comment by kitao** [comment]
Let's talk about this topic in #70
