### ISSUE TITLE
Web app unable to capture input focus once lost

### ISSUE THREAD

**Issue by helpcomputer** [kitao/pyxel#540]
If you play a Pyxel web game and click outside the window you're unable to recapture input focus of the app.

I tried it with the the below games, same behaviour for both, in Chrome and Firefox:

https://fbrzd.itch.io/tiny-tale
https://helpcomputer.itch.io/vortexion

It seems fine when the game launches in full screen, for example in the case of the below game, you can click outside the game but can regain input capture:

https://aged99oow.github.io/mario/

**Comment by helpcomputer** [comment]
Just an addition to this, users also reporting the same issue with the game uploaded to itch, I think it will be worth looking into this soon to avoid further issues:
![image](https://github.com/user-attachments/assets/8ca1d128-8943-408a-ba14-c25261ed02ce)

**Comment by kitao** [comment]
I updated Emscripten and other Web-related external libraries by updating Pyxel's code.
https://fbrzd.itch.io/tiny-tale looks fine but https://helpcomputer.itch.io/vortexion doen't work (probably, by some another reason).

Please check it.

**Comment by helpcomputer** [comment]
It's a real problem that a web game can break without the developer of the game not changing anything.
