### ISSUE TITLE
Store metadata within app package (feature request)

### ISSUE THREAD

**Issue by nopid** [kitao/pyxel#541]
The Pyxel application file (.pyxapp) provides a convenient way to distribute and play Pyxel applications. In practice, it is a zip archive of the application files with a special file pointing to the startup script.

For a convenient way to archive and manage a collection of application files, I would suggest adding a metadata file inside the application file (maybe something like `pyxapp.toml`? [toml](https://toml.io/) seems to be quite popular among Python developers these days) to provide some metadata about the application. I was thinking about:
 - title
 - author
 - description
 - webpage/url
 - version
 - license
 - screenshot/gif animation provided in the pyxapp file itself
 - *etc*

Of course the authors are free to provide whatever metadata they see fit. The point of specifying the format is to ensure compatibility and promote usage. The pyxel web player could then also display this information along with the application when playing it.

**Comment by kitao** [comment]
My current idea is a way by adding meta data as comment in the startup python file like this:

```python
# title: A Game
# author: Takashi Kitao <takashi.kitao@gmail.com>
# desc: An excellent shooter
# version: 1.0
```

These information will be stored as meta data of a zip file and printed when .pyxapp is played.

**Comment by nopid** [comment]
If you plan to include it into the startup python file, it could be more Python-like to use a docstring at the beginning of the script. It would still be easy to grasp for beginners, could be parsed by your tool and would also provide an access to it from code as `__doc__`. The title key could then be extracted from metadata by `pyxel.init`.

`tri.py`:
```python
"""
title: Boring Sierpinski Triangle
author: A. Nonymous <noone@nowhere>
desc: drawing IFS using random walks
version: 0.1
"""
import pyxel
from random import choice


class Tri:
    def __init__(self):
        pyxel.init(128, 128, meta=__doc__)
        self.x = 0
        self.y = 0
        pyxel.run(self.update, self.draw)

    def update(self):
        if pyxel.btnp(pyxel.KEY_RETURN):
            pyxel.cls(0)

    def draw(self):
        for _ in range(100):
            ax, ay = choice([(0, 0), (128, 0), (0, 128)])
            self.x = (self.x + ax) // 2
            self.y = (self.y + ay) // 2
            pyxel.pset(self.x, self.y, 7)


Tri()
```

**Comment by kitao** [comment]
Thank you, but I think each format should be different. Because their purposes are different, one is for a Pyxel app, the other is  for a Python module.

**Comment by kitao** [comment]
The latest Pyxel has the metadata feature. Please check the README.
