### ISSUE TITLE
warp_mouse()

### ISSUE THREAD

**Issue by paul59** [kitao/pyxel#543]
This doesn't seem to work for me on Linux. I have 

`pyxel.init(320, 200, fps = 60, quit_key = py.KEY_ESCAPE)`

but warp_mouse (160, 100) doesn't put the cursor at screen centre - if that's what it's supposed to do? It looks as if it's placing it at window pixel (160, 100) instead ie using screen resolution.

**Comment by kitao** [comment]
I fixed the related code in the latest Pyxel. Could you try 2.1.4?

**Comment by paul59** [comment]
Yep, that's does it thank you :smile:
