### ISSUE TITLE
Empty file resource opened after save in pyxel edit

### ISSUE THREAD

**Issue by flupec** [kitao/pyxel#546]
Steps to reproduce (on version 2.1.3)
1) `pyxel edit aaa`
2) make any changes, press save, exit
3) `pyxel edit aaa.pyxres`
4) window opens without saved content, although the file exists with non-zero content

This bug cannot be reproduced on 2.1.0 version

**Comment by yougivinbeef** [comment]
Same issue here. When trying to load in __init__ I get the error 

thread '<unnamed>' panicked at pyxel-engine\src\resource.rs:48:37:
Failed to open file 'mygame.pyxres'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "PycharmProjects\pyxel_1\main\main.py", line 21, in <module>
    game()
  File "PycharmProjects\pyxel_1\main\main.py", line 9, in __init__
    pyxel.load("mygame.pyxres")
pyo3_runtime.PanicException: Failed to open file 'mygame.pyxres'

**Comment by kitao** [comment]
Thank you for your report. I fixed it in 2.1.4. Could you try it?

**Comment by flupec** [comment]
Works fine
