### ISSUE TITLE
FAQ for pyxel

### ISSUE THREAD

**Issue by rubyFeedback** [kitao/pyxel#548]
First I would like to suggest the addition of a FAQ.

Second: my question for the FAQ is this: will old games be re-recreated by pyxel too, a bit similar to what scummvm is doing for some games? E. g. it would be neat if pyxel would include all old arcade games, or, clones of it that are similar in spirit to playing it.

**Comment by kitao** [comment]
QA page exists and there is a link for it in README.
It's up to Pyxel users to recreate old games.
