### ISSUE TITLE
Keys does not honor keyboard layout

### ISSUE THREAD

**Issue by kafeinnet** [kitao/pyxel#56]
Hi,

The « KEY_ » constants does not honor keyboard layout. On my french keyboard, KEY_Q is True when I press the A key, KEY_Z is True for the W key, etc.

\fab

**Comment by kitao** [comment]
Though I'd like to fix this problem, actually I just use GLFW key definitions.
So I'll check the way to fix it on pure GLFW.

**Comment by KnutZuidema** [comment]
It would be beneficial to know what you are comparing `KEY_Q` against, since GLWF just uses the ASCII code for Q, which is 81 or the return value of `ord('Q')` in python.

**Comment by kitao** [comment]
Does the latest SDL version of Pyxel change the situation?

**Comment by kitao** [comment]
If the same issue occurs, please make new one.

**Comment by dglaude** [comment]
Tested today on Raspberry Pi and the problem is still present...
Very visible in Snake where I have to use A while in the code it say KEY_Q.
R is at the same location in QUERTY and AZERTY so that make no problem.
