### ISSUE TITLE
Palette colors not displaying correctly on Windows

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#560]
I’ve heard reports of palette colors not displaying correctly on Windows.

Please check your Pyxel app on Windows by comparing it with the attached image, and share your results along with your OS version and GPU info. Thank you.

![05_color_palette](https://github.com/user-attachments/assets/1f763531-c417-4323-8acd-b7ea9f68ee64)

**Comment by kitao** [comment]
Here's the incorrect color version on Windows
![名称未設定](https://github.com/user-attachments/assets/19034530-9ffa-4012-9bae-cf038ecb68a9)

**Comment by kra53n** [comment]
I have this problem on the my PC but when I resize the window, the color palette starts to display correctly.

OS: `Windows10`, version `22H2`

I have two GPUs on the my laptop:
1. `Intel(R) HD Graphics 620`
2. `NVIDIA GeForce GTX 950M`

**Comment by kitao** [comment]
Thank you. If possible, please try the following wheels to check the result
changes.

https://drive.google.com/file/d/1hNzTggNKFmsaE5wSsz9J5oruU4ZE-qHQ/view?usp=sharing

You can install it by pip install -U target_filename_in_zip

2024年8月17日(土) 19:46 kra53n ***@***.***>:

**Comment by kitao** [comment]
I've released Pyxel 2.1.10 which should fix the issue. Please try it.

**Comment by kra53n** [comment]
In the new Pyxel version color palette displays correctly!
