### ISSUE TITLE
Error with three arguments in pyxel.btnp() v2.1.10

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#562]
In pyxel 2.1.10, specifying three arguments to pyxel.btnp() as follows causes an error that did not occur before.

pyxel.btnp(px.KEY_UP, 8, 2)

> btnp() takes 1 positional arguments but 3 were given

Can you please make this backwards compatible and error-free if possible?

**Comment by DiddiLeija** [comment]
In the meantime, you can use `pyxel.btnp` as follows:

```python
pyxel.btnp(pyxel.KEY_UP, hold=8, repeat=2)
```

As the last 2 arguments are no longer positional.

Anyway a backwards-compatible fix or a warning would be nice as well :)

**Comment by kitao** [comment]
Due to updating Python-related library version, Pyxel's original argument setting (explicit keyword argument) is forced now.
I'll take care of backward-compatibility in the next version.

**Comment by kitao** [comment]
Fixed in 2.2.0
