### ISSUE TITLE
Colors past 15 only display as color 15

### ISSUE THREAD

**Issue by ieeemma** [kitao/pyxel#564]
I've set an array of extra colors with `pyxel.colors = list(pyxel.colors) + ...`, but higher indices always display as color 15 - has the ability to use extra colors been removed? I'm on 2.2.1.

**Comment by merwok** [comment]
I think you have to use from_list: https://github.com/kitao/pyxel?tab=readme-ov-file#graphics

**Comment by ieeemma** [comment]
thankyou!! cant believe I missed that.
