### ISSUE TITLE
Screen whiteness in certain environments.

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#569]
日本語で失礼します。
以前にDiscordなどでkitaoさんがヒアリングされていた、色合い全体が白っぽくなる問題が報告されました。
Pyxelの直接起動ではなく、ビルドしたexeファイルでの事象になります。Pyxelのバージョンは2.2.3です。

以前の問題がどういう決着をみたのか追えていないのですが、こちらは別要因となりますでしょうか。

OS：Windows 11 pro
バージョン：23H2
チップの種類：AMD Radeon Graphics Processor(0x1681)

<img width="1002" alt="SS 2024-10-11 17 52 31" src="https://github.com/user-attachments/assets/f4b3ff06-0ea1-41c3-b619-c43d62b5ff21">

**Comment by kitao** [comment]
まだ同じ原因かわからないというのが現状になります。

以前の現象は、PyxelがOpenGL ES→OpenGLの順番に初期化を試みることで対応GLのバージョンを判定していた処理が、一部Windows環境ではOpenGL ESのソフトエミュレーターを搭載しているため、GLESの初期化が通ってしまう＋GLESソフトエミュレーターだとパレットカラーの読み出しがうまくいかない（おそらくは）不具合があり、色が白くなってしまうという現象でした。

結果、OpenGL→OpenGL ESの順番で初期化を行うように変更することで正規ドライバでOpenGLが動作するようになり、Intel/NVidia/Radeonでは現象が発生しなくなったと報告をもらっています。

そういった状況なので、まずできることは以下になるかと思います。
・GPUドライバの更新をしてもらい、現象が出なくなるか確認してもらう
・他にも同様の現象が発生している環境がないか情報を集め、共通する要素を洗い出す

**Comment by shiromofufactory** [comment]
ありがとうございます。
ひとまずGPUドライバの更新をご案内しつつ、解決しなかった場合は情報収集してみます。
以下画像の表示部分からドライバの型番を確認してもらうのがよいでしょうか？

![pasted image 0](https://github.com/user-attachments/assets/23ba91ea-8c16-4999-a7f9-287c1a0bd0cb)

参考にした記事
https://jp.iobit.com/driver-update/how-to-update-graphic-drivers-127.html#p2

**Comment by kitao** [comment]
@shiromofufactory 
ドライバの型番が分かっても再現環境がないと裏どりをすることは難しいそうですね。

ただ、状況進展ありまして、GL設定を色々実験して私の環境でもそれっぽいものを再現することができました。この色の出方で一致していますでしょうか

<img width="1018" alt="スクリーンショット 2024-10-13 9 54 13" src="https://github.com/user-attachments/assets/80e8265b-b621-4fc9-ab91-c92ec9c64431">

現象が同じようであれば、OpenGL/OpenGLESのsRGB対応設定が、初期時でOffになることが規格で規定されているのに対して、ドライバや表示のユーティリティソフトの設定等で強制Onにされてしまっている結果と思われます。

もしそうだとすると、PyxelのOpenGL初期化後に明示的にglDisable(GL_FRAMEBUFFER_SRGB)を呼んでOffにすることで防げそうな気がします。上記、確証が持てそうでしたらPyxel側に該当処理を追加しますのでお伝えください。

**Comment by shiromofufactory** [comment]
@kitao 
ありがとうございます。複数の方のスクリーンショットを見ましたが、色の見え方の印象は一致しています。
お手数おかけしますが、よろしくお願いいたします。

**Comment by kitao** [comment]
Pyxelの初期化コード段で対策を入れても状況変わらない（さらにその後上書きされてしまう）可能性があるので、もう一歩確証が得られると良いのですが、色がおかしくなっている方々に何か共通点はないでしょうか。（例えばPCのカラープロファイル設定を変更しているなど）

**Comment by kitao** [comment]
@shiromofufactory 
別の更新したい件もあったので、ひとまず今回の対応を入れたPyxel 2.2.5をリリースしておきました

**Comment by shiromofufactory** [comment]
@kitao 
ありがとうございます。

> 色がおかしくなっている方々に何か共通点はないでしょうか。（例えばPCのカラープロファイル設定を変更しているなど）

これを能動的に、かつ何が手がかりになるかわからない中で情報収集するのがちょっと難しいな・・と思っていたところなので大変助かります。
2.2.5反映版をリリースして、直ったかどうか確認してみます。

**Comment by shiromofufactory** [comment]
@kitao 

2.2.5反映版で直ったとの報告を受けました。
クローズさせていただきます、ありがとうございました！
