### ISSUE TITLE
unhandled exception: called glCreateShader but it was not loaded

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#571]
今回も日本語で失礼します。

![GZ-puO4b0AQ4J7m](https://github.com/user-attachments/assets/e37edb20-dbad-494b-9847-a4116945a221)

pyxelアプリをexeファイルにしたもの（Dungeon Antiqua）をWindows上で実行した方の中に上の画面が表示されてプレイできなかった方がいらっしゃったそうです。
最後の一行は見切れていますが、このように表示されているとのこと。

pyo3_runtime.PanicException: called glCreateShader but it was not loaded.

OSはWindows 10 Homeエディション、バージョン22H2で、10年以上前のWindowsPC（win7の時代）をアプデして使っているそうなので、これも古いGPUドライバなどが原因かもしれないと考えています。

**Comment by kitao** [comment]
こちら、Pyxelが必須とするOpenGLバージョン2.1以上のAPIがなくて、そもそも初期化を始められていないという状況ですので、OpenGL 2.1以上に対応したドライバであることの確認をしていただくのが良いと思います。

（ただ、OpenGL 2.1は2006年に規格がリリースされ、2007年以降に発売されたGPUは大抵サポートしているので、15年以上前のPCでないとそういったことは起きない気はするのですが）

**Comment by kitao** [comment]
進展内容ですので、対象範囲外のハードウェアということでクローズさせていただきます。
