### ISSUE TITLE
Tiny clarification needed?

### ISSUE THREAD

**Issue by paul59** [kitao/pyxel#575]
This is in the 'Special Key Controls' section...
```
Shift+Alt(Option)+1/2/3
Save the corresponding image bank to the desktop
```
Might it be better if the text reads 'Save image bank 0, 1 or 2  to the desktop'? Or even 'n-1' ? Easier than changing the code to handle Shift+Alt(Option)+0 I guess although that would be the best option :-D

**Comment by kitao** [comment]
Thank you. I'll adopt the former idea.
