### ISSUE TITLE
Jagged screen display in smartphone browsers (2.2.7)

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#578]
In recent versions, HTML apps created with Pyxel now fill the entire screen when viewed on a smartphone. This is great!
On the other hand, the accuracy of dot rendering has become coarse. To elaborate, there seems to be a difference in the magnification per pixel.
I am posting two screenshots for comparison: the first is the latest version and the second is the previous version (every pixel is displayed at equal size).

ver. 2.2.7
![localhost_8000_(iPhone SE)](https://github.com/user-attachments/assets/f1c73447-4feb-437c-9fdf-041439a26e5b)

ver. 2.2.1
![localhost_8000_(iPhone SE) (1)](https://github.com/user-attachments/assets/281b65c4-7e60-4e87-9601-bdcb430e4889)

**Comment by kitao** [comment]
First, please note that when the screen is set to full-screen mode, pixel art scaling will not be pixel-perfect, and some distortion will occur.

Next, the resolution setting for the Web version is affected by the High DPI setting multiplier in the HTML configuration. You can adjust this multiplier as needed. Setting the multiplier to 1 will enable the use of a large canvas that utilizes the smartphone's native high resolution, which may make distortions less noticeable.

However, using a high-resolution canvas can make typical HTML UI interactions more difficult and significantly increase rendering costs, leading to risks such as performance drops or audio glitches. Therefore, I do not recommend this configuration for low-spec smartphones.


前提として画面をフルスクリーンにした場合はドット絵の拡大はピクセルパーフェクトにはならずどこかに歪みが出るということをご承知おきください。

次にWeb版の解像度設定はHTMLのHigh DPI設定の倍率によって変わりますので、必要に応じてこちらの設定を切り替えてみてください。こちらの倍率を１にすればスマートフォン本来の高解像度を使った大きなキャンバスが使えるようになり歪みが見えにくくなると思います。

ただし高解像度のキャンバスを使用すると、通常のHTMLのUIの操作が困難になることと、レンダリングコストが大幅に増えるので、処理落ち、音切れのリスクが大きくなることに注意が必要です。そのため低スペックのスマートフォンでの利用はあまりお勧めできません。

**Comment by shiromofufactory** [comment]
ありがとうございます。
前提については理解しております。
また、devicePixelRatioの設定によりスマートフォン本来の高解像度を使った表示が可能であることも理解しました。また実際に試してみると、おっしゃる通りその分処理が重くなることも体感しました。
あとは端末のスペックとアプリケーションの処理速度の問題になると思いますので、このissueはクローズいただいて大丈夫です。

Thank you.
I already understand the premise.
I also understand that the devicePixelRatio setting enables display using the original high resolution of smartphones. I also understood that the devicePixelRatio setting can be used to display images using the high resolution that smartphones are capable of.
I think the rest will be a matter of device specs and application processing speed, so you can close this issue.
