### ISSUE TITLE
RuntimeError: glfw version is lower than 3.2.1

### ISSUE THREAD

**Issue by hstk30** [kitao/pyxel#58]
my Python Version is 3.6.4,i use pip install glfw,but the glfw version is 3.1.2

```
In [5]: import glfw

In [6]: glfw.get_version_string()
Out[6]: b'3.1.2 X11 GLX clock_gettime /dev/js XI Xf86vm shared'
```

So, glfw's version can't fix the pyxel's.

**Comment by hstk30** [comment]
Oo, I know it.First, I use `apt-get` to install `glfw`, and the default version of glfw is 3.1.2.

**Comment by kitao** [comment]
Pyxel's version check of glfw is 3.1.2 now. If some problem occurs with glfw 3.1.2, please create a new issue.
