### ISSUE TITLE
Mouse coordinates are not acquired correctly in smartphone browsers

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#584]
See the image below. The lower right location is detected as pyxel.mouse_x and pyxel.mouse_y compared to the actual tapped location.
For example, if the screen is 256x256, mouse_x and mouse_y may return values such as 360.

https://github.com/user-attachments/assets/d6e2d275-a35d-4ee6-806c-857b0da9363d

**Comment by kitao** [comment]
Thank you. I fixed this issue in 2.2.8.
Actually this bug had happened on both a PC and a smartphone.
