### ISSUE TITLE
Make wiki editable

### ISSUE THREAD

**Issue by timbledum** [kitao/pyxel#60]
Hi!

Just made another game ([pong clone](https://github.com/timbledum/pong)) which I'm keen to put up to the wiki – although there is an invitation to edit, it doesn't look like it's editable.

Could you update this if this is unintentional? It looks like [this](https://help.github.com/articles/changing-access-permissions-for-wikis/) is how you do it.

**Comment by kitao** [comment]
Thank you for report!
I've not noticed that the wiki is not editable.
I changed the setting to allow it.
