### ISSUE TITLE
More audio effects?

### ISSUE THREAD

**Issue by jamesguessis** [kitao/pyxel#63]
The AudioPlayer in pyxel is very nice (would be nice if it was also it's own submodule that could be installed without the need of pyxel, but that's a really pointless suggestion). 
I really don't know much about audio and such, so, would it be possible to add the audio effects found in something like pico-8? 

from https://www.lexaloffle.com/pico-8.php?page=manual:
```
	:: Effects

		0 none
		1 slide          //  Slide to the next note and volume
		2 vibrato        //  Rapidly vary the pitch within one quarter-tone
		3 drop           //  Rapidly drop the frequency to very low values
		4 fade in        //  Ramp the volume up from 0
		5 fade out       //  Ramp the volume down to 0
		6 arpeggio fast  //  Iterate over groups of 4 notes at speed of 4
		7 arpeggio slow  //  Iterate over groups of 4 notes at speed of 8
		
		If the SFX speed is <= 8, arpeggio speeds are halved to 2, 4```

**Comment by kitao** [comment]
Yes, it's possible. 
Actually I implemented more sound effects in the first prototype. But I also found many effect can get complicated when it is edited only with text code, so I limited the number of sfx to 4 in the current version.

Now I'm developing the resource edit tool for Pyxel. After finishing it, I'll consider adding more effect.

**Comment by jamesguessis** [comment]
Have you considered this since then?
