### ISSUE TITLE
tetris-clone example

### ISSUE THREAD

**Issue by shivanju** [kitao/pyxel#65]
Hi. First of all thanks for making such an awesome framework. I've made a minimal [tetris clone](https://github.com/shivanju/tetris-clone) using pyxel. Didn't know the right place to post this hence raising an issue.

**Comment by kitao** [comment]
Hi! Could you introduce it in the Pyxel wiki?
https://github.com/kitao/pyxel/wiki

**Comment by shivanju** [comment]
Added in wiki. Closing the issue.
