### ISSUE TITLE
Possibility: add mypy.ini typings and bump to python version 3.6+

### ISSUE THREAD

**Issue by bbarker** [kitao/pyxel#66]
Hello,

I'd like to become more familiar with the pyxel code, and I love the new python typings. Would be happy to work on adding these if desirable.

**Comment by kitao** [comment]
Actually I'm not familiar with Python very much and don't know mypi.
I'll study it and if it looks useful, I'll add it.

**Comment by bbarker** [comment]
Thanks!

**Comment by kitao** [comment]
@bbarker I added type hints to functions of Pyxel 0.9.9 and checked mypy outputs no error.
Could you let me know what else I should do?
