### ISSUE TITLE
Latest glfw 3.2.1

### ISSUE THREAD

**Issue by skippa** [kitao/pyxel#67]
I'm using Elementary OS, how can I force the latest glfw? Repos say 3.1.2 is latest which throws an error when using pyxel...

I'd rather not compile from source, is there an easier way? Very keen to start building games using this beautifully simple platform :)

**Comment by kitao** [comment]
In the latest version of Pyxel (0.7.12), I loosened the version check of glfw in an attempt.
Could you check Pyxel works on your environment?

**Comment by kitao** [comment]
The current Pyxel allows glfw 3.1.2.
If same problem occurs, please make a new issue.
