### ISSUE TITLE
After warpping the glfw,it does help import pyxel,but the pyxel window doesn't work

### ISSUE THREAD

**Issue by Hyfred** [kitao/pyxel#69]
Firstly, I down the pyxel wrap, then i have try to import pyxel, but  it shows "Failed to load GLFW3".So I load the glfw, it also doesn't work. After searching the problem, i went to the computer'path add the environment of the glfw. The function of "import glfw" and "import pyxel"  does work. But after "pyxel.init(160, 120)", the pyxel window is black . Then It shows no response. Please help me solve the problem

**Comment by shivanju** [comment]
Can you post the screenshot or traceback when you try to run basic examples?

**Comment by Hyfred** [comment]
@shivanju    I forget to mention that I can't install the example, how to use the code "install_pyxel_examples"? And I just follow the "How to Use" step one "Create Pyxel Application". Then it jumps the pyxel window like that.

**Comment by Hyfred** [comment]
@shivanju sorry. my vpn has expired . The post function can't work

**Comment by Hyfred** [comment]
@shivanju 
<img width="919" alt="_20180913230742" src="https://user-images.githubusercontent.com/38806779/45684731-d263e880-bb79-11e8-96a8-eed0d425f058.png">
Could you help me?

**Comment by Hyfred** [comment]
@kitao can you help me solve this problem?

**Comment by timbledum** [comment]
That looks like it's working fine from the screenshot. What are you expecting to see?

What operating system are you using?

After installing pyxel, just type "install_pyxel_examples" at the command line / terminal. If you're really struggling, try cloning this repository and navigating to the examples folder to check the examples out.

<img width="922" alt="screen shot 2018-09-19 at 6 10 41 am" src="https://user-images.githubusercontent.com/20265151/45707399-d7a15180-bbd2-11e8-87a3-6e9baf17e4aa.png">

**Comment by shivanju** [comment]
@Hyfred  Your screenshot looks fine to me. That sample code only does that. Can you try running some examples and see if there is some problem with those.

**Comment by Hyfred** [comment]
@timbledum I use window10. And i typed "install_pyxel_examples" in the command line succseefully. But after that, i don't understand how to use the pyxel module. following the step"Create Pyxel Application". It still has something wrong. "SyntaxError: unexpected EOF while parsing"
<img width="381" alt="1" src="https://user-images.githubusercontent.com/38806779/45738693-b9b00d00-bc23-11e8-8dee-0c5b6b62118f.png">
<img width="797" alt="2" src="https://user-images.githubusercontent.com/38806779/45738754-e106da00-bc23-11e8-9f83-537b79080c63.png">
<img width="335" alt="3" src="https://user-images.githubusercontent.com/38806779/45738761-e532f780-bc23-11e8-9b41-202071b96612.png">

**Comment by timbledum** [comment]
I think the issue is with how you're running the code rather than the code itself. I think the issue is that you're running the code line by line in the console box, rather than running the whole file as a whole. 

If you go to the command line and use `python untitled1.py` once you've saved the file, that should work! I wouldn't recommend Spyder TBH. 

Try this at the command line!

```
cd pyxel_examples
python 02_jump_gamel.py
```

**Comment by Hyfred** [comment]
@shivanju thanks your instruction!! Now I can use it !! [Facepalm][Rose][Rose]
