### ISSUE TITLE
Pyxel Image Editor is Implemented! Need to add the instruction of it to the manual

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#71]
Pyxel 0.8.0 has been released and finally supports its own image editor!

![pyxel-180924-095902](https://user-images.githubusercontent.com/678802/45935260-b2528000-bfe4-11e8-9539-7d9657ee5f23.gif)

You can run the editor with `pyxeleditor` command after installation and created resource files can be used with new `save` and `load` APIs.

I'll add the instruction of it to the manual.

**Comment by timbledum** [comment]
This is soooo rad!

The placeholder for the music editor is so tantalising.
