### ISSUE TITLE
Example 2 Redraw is not working

### ISSUE THREAD

**Issue by cmcknight** [kitao/pyxel#73]
Item | Description
------------ | -------------
OS | Ubuntu 18.04.01 LTS (under VMWare Fusion 10.1.3 virtual machine, supports OpenGL 3.3)
Python | 3.6.6
Pyxel | Latest pull from HEAD

I'm getting some "interesting" results from example 02_jump_game.py (see image below). The redraw is apparently not quite working as expected.

![screenshot from 2018-10-03 19-49-47](https://user-images.githubusercontent.com/126305/46451065-5d7fd980-c749-11e8-96c6-1ceb13e50f71.png)

I won't have a chance to dig into this for a few days yet, but I wanted to post it in case someone else can get to it sooner. It works fine on macOS with Python 3.7, but I'm wondering if there is something with running under the VMware Fusion virtual machine that is causing the hiccup.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
