### ISSUE TITLE
Export games like "cartridges" and Pyxel like the "arcade machine" #Enhacement

### ISSUE THREAD

**Issue by Rutrus** [kitao/pyxel#75]
My idea is create a standard and store each game as *.zip or folder, so you can share them, and in a future download a bunch of them.

With this modular way, you can export Pyxel like the "arcade machine" with a game selector.

If there is a config and each game has its github link, they would be upgraded when they are updated from Github, ask for dependencies, etc.

Makes it sense?

**Comment by kitao** [comment]
Thank you.
I'll take care of this idea when think about #70
