### ISSUE TITLE
Use lossy GIF to reduce animated GIF

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#80]
To reduce animated GIF size, I'd like to use lossy GIF, but I seems that there's no appropriate python module for that.

The idea I have now is to use gifsicle as an external command, but Pyxel needs to include binaries of it for each environment.

Please let me know if there's other good ideas!

**Comment by ChildishGiant** [comment]
It's probably worth looking into [ImageMagick](https://www.imagemagick.org/script/index.php) and its [Animation Optimization](https://www.imagemagick.org/Usage/anim_opt/) abilities.

**Comment by kitao** [comment]
Is there any easy way to install ImageMagick with pip command?

**Comment by kitao** [comment]
New version of Pyxel, 1.1.1, has new Gif renderer in C++.
Its gif size got smaller.
