### ISSUE TITLE
PyCharm cannot find method references

### ISSUE THREAD

**Issue by Vlek** [kitao/pyxel#82]
It appears that PyCharm is looking for methods within the __init__.py file and it's not finding run, width, cls, rect, etc. I am wondering if I'm just doing something wrong, or if this is a Pyxel issue. I've created a venv, installed Pyxel through PyCharm, and gotten it set up as I normally would without any luck. I'm running Windows 10, Python 3.7.1, and PyCharm 2018.2.4.

**Comment by Vlek** [comment]
I have researched this a bit more, and I think it has to do with __all__ not having extend called to include App's methods.

**Comment by timbledum** [comment]
This is how pyxel works – it actually initiates an object and binds this object's methods to the pyxel module. Note that you can't use these methods until the init function has been called. This makes for a nice API but unfortunately not so good for static analysis.

**Comment by Vlek** [comment]
I saw that too where it used App as a module factory. Darn, I was hoping I had just overlooked something and it was a simple fix.

**Comment by kitao** [comment]
It will not solve all problems, but KEY constants are exported explicitly in Pyxel 0.9.0.
At least those constants will be recognized by PyCharm.

**Comment by Vlek** [comment]
I know this is probably a big ask, but could we possibly get a version where all of the methods are able to be seen via static analysis and also get typed parameters?

**Comment by kitao** [comment]
Actually I'm not familiar with type hinting of Python.
If I make .pyi file for Pyxel API, does it solve this issue?

**Comment by kitao** [comment]
@Vlek I added the function declaration and type hints in __init__ of Pyxel 0.9.9.
It seems that autocomplete works on PyCharm now.
Could you confirm it?

**Comment by Vlek** [comment]
Yes! Thank you so much!
