### ISSUE TITLE
Channel or forum or subreddit

### ISSUE THREAD

**Issue by shivanju** [kitao/pyxel#84]
It would be great if there is one channel or forum for the discussions around errors, trivial issues, ideas or showcasing. Now that pyxel community is growing, I am quite eager to know what other folks are making with pyxel. 
Thanks

**Comment by kitao** [comment]
Hi,
Which tool do you think I should use?
Or is it enough to simply create a new channel as an issue here?
If you have any recommendations, please let me know.

**Comment by shivanju** [comment]
I think we can start from a subreddit then. It'll server our purpose very well.

**Comment by ChildishGiant** [comment]
[done](https://www.reddit.com/r/pyxel/)

**Comment by shivanju** [comment]
Let's add that in wiki/readme, so that people get know where to find other folks. Thanks for the effort though.

**Comment by kitao** [comment]
Thank you, everyone!
I added the link to the manual.
