### ISSUE TITLE
When should draw be used and when should update?

### ISSUE THREAD

**Issue by ChildishGiant** [kitao/pyxel#88]
I don't really know the semantic difference of update and draw. I tried to do all the calculation in update but there's some overlap and I can't seem to share variables from one to the other. Thanks for the help 😄

**Comment by liquid600pgm** [comment]
You should always use `update()` for your game logic, and `draw()` for updates. To share variables from one to the other, either use a class and just set the variables using `self.my_var`, or use the `global` keyword in a function.
Here's an example of how to use the `global` keyword:
```py
import pyxel

x = 1

def update():
  global x
  x += 1

def draw():
  pyxel.rect(x, 0, 32, 32, 0xf)

```

**Comment by ChildishGiant** [comment]
But they both get run once per frame? If so I don't really see the point in having two functions

**Comment by timbledum** [comment]
1. They get called at different points of the main game event loop.
2. Having logic and display in different functions allows frames to be dropped if required without affecting the logic.

**Comment by kitao** [comment]
Yes.
If the updating time is long and can't keep the target fps, Pyxel thin out drawing to reduce processing time. 
So the update function is called periodically but the draw function is executed when there is enough processing time.
