### ISSUE TITLE
pyxeleditor and install_pyxel_examples commands are not installed properly

### ISSUE THREAD

**Issue by liquid600pgm** [kitao/pyxel#90]
I tried to run the Pyxel Editor with a fresh Pyxel install, and the commands seem to not be registered correctly.
![image](https://user-images.githubusercontent.com/16415678/47737809-0d296800-dc72-11e8-92dc-6d97c30fc789.png)
Same error for install_pyxel_examples.

 - OS: Ubuntu 18.10 Cosmic Cuttlefish
 - Python: 3.6.7rc1
 - Shell: fish

**Comment by liquid600pgm** [comment]
I just reinstalled pyxel, this time using sudo, and it seems to work properly.

**Comment by kitao** [comment]
Thank you for confirmation.
Actually I'm just using create shortcut function of pip setting file. So it means sudo command is necessary also for other pip package such as flake8 and black.
Is this assumption correct? And should I write this in the manual?

**Comment by liquid600pgm** [comment]
It seems like so. Please add that to the docs to avoid future confusion, if you can :)
