### ISSUE TITLE
Is Pyxel really working properly on Linux?

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#98]
Finally I setup the test environment for Ubuntu and started trying to run Pyxel by myself,
and I found if I install Pyxel in the "standard way" like this:
`sudo apt install python3-pip libglfw3 libportaudio2`
`sudo pip3 install pyxel`
as a result, Pyxel's rendering doen't work correctly (probably because of glfw version) and sound is not played correctly either (probably because of the sound buffer size).

Initially, Pyxel only supported Mac and Windows because I had both environments and added Linux support thanks to operation reports of Linux users. But I'm wondering if Pyxel really can support Linux, and I'm wondering if it would be better to officially say that it will not work on Linux.

So could you give me an information if Pyxel runs on your Linux environment?
Thank you.

**Comment by shivanju** [comment]
I have used pyxel in linux(Arch) and Windows both. But mostly Linux. After pyxeleditor got introduced, this is my first time using it in Linux. First obvious thing I noticed is sound and music editors are having some problem. Everything works fine in sound/music editor except it can't play any sound. It highlights the buttons being pressed but after creating a piece, you wont be able to play it. One more thing is that when I click on play button in editor, the progress bar starts and freezes  immediately (the playing action doesn't stop, I've to stop it manually). That's all I've noticed till now. In windows it's working flawlessly till now.

**Comment by Reiddragon** [comment]
I'm using Pyxel on openSUSE Tumbleweed, and everything works fine, with the exception of sound, and the sound and music editors. Just as shivanju pointed out, no sound is being played, and the sound and music editors also seem broken.

**Comment by emmalynrenato** [comment]
@kitao can you give more details on what you mean when you say pyxel is not rendering correctly?
Do you have a hardware GPU on your Linux box? In other words, I wonder whether it's the same "black screen" problem mentioned in issue #46

A simple check would be to run:

```bash
  $ LIBGL_ALWAYS_SOFTWARE=1 python3 01_hello_pyxel.py
```
This will force software rendering.

**Comment by kitao** [comment]
@emmalynrenato 
It's a little difficult to describe correct behavior but if there's some difference between your screen and screenshots (animated GIF) of the Pyxel README page, it's not expected one.
And bug what I've seen was the screen on which some objects are drawn but some objects are not drawn (it's the same bug as some users pointed already). And my Linux environment runs on VirtualBox on Windows.

**Comment by arslanalpc** [comment]
I installed it on my Ubuntu 18.04 LTS system and I've tested the sounds and sound editor. It works just fine. Maybe the README needs to be updated.

**Comment by seipy** [comment]
Works fine on my Deepin 15.8

**Comment by kitao** [comment]
Thank you, everyone.
I confirmed Pyxel works on my Linux environment. So I close this issue for now.
I also make new issue regarding the instruction of installation for Linux.
